# Statistical Analysis

In [3]:
import pandas as pd
import numpy as np
import ast
import statsmodels.api as sm
from statsmodels.stats.multitest import multipletests
from scipy import stats
import statsmodels.formula.api as smf
from statsmodels.stats.multicomp import pairwise_tukeyhsd

In [4]:
df = pd.read_parquet("../data/processed/anime_data_2.parquet")
df.info()

<class 'pandas.DataFrame'>
Index: 5338 entries, 0 to 8816
Data columns (total 76 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   mal_id                 5338 non-null   int64
 1   title                  5338 non-null   str
 2   source                 5338 non-null   str
 3   episodes               5338 non-null   float64
 4   producers              5338 non-null   object
 5   genres                 5338 non-null   object
 6   studios                5338 non-null   object
 7   demographics           5338 non-null   object
 8   themes                 5338 non-null   object
 9   rating                 5338 non-null   str
 10  sequel                 5338 non-null   bool
 11  cohort                 5338 non-null   str
 12  wc_z                   5338 non-null   float64
 13  forum_z                5338 non-null   float64
 14  favorites_z            5338 non-null   float64
 15  score_z                5338 non-null   float64
 16  drop_rate_z            5338 non-null   float64
 17  genre_action           5338 non-null   int64
 18  genre_adventure        5338 non-null   int64
 19  genre_award_winning    5338 non-null   int64
 20  genre_comedy           5338 non-null   int64
 21  genre_drama            5338 non-null   int64
 22  genre_ecchi            5338 non-null   int64
 23  genre_fantasy          5338 non-null   int64
 24  genre_gourmet          5338 non-null   int64
 25  genre_horror           5338 non-null   int64
 26  genre_mystery          5338 non-null   int64
 27  genre_other            5338 non-null   int64
 28  genre_romance          5338 non-null   int64
 29  genre_sci-fi           5338 non-null   int64
 30  genre_slice_of_life    5338 non-null   int64
 31  genre_sports           5338 non-null   int64
 32  genre_supernatural     5338 non-null   int64
 33  genre_suspense         5338 non-null   int64
 34  demo_josei             5338 non-null   int64
 35  demo_kids              5338 non-null   int64
 36  demo_seinen            5338 non-null   int64
 37  demo_shoujo            5338 non-null   int64
 38  demo_shounen           5338 non-null   int64
 39  theme_adult_cast       5338 non-null   int64
 40  theme_anthropomorphic  5338 non-null   int64
 41  theme_cgdct            5338 non-null   int64
 42  theme_detective        5338 non-null   int64
 43  theme_gag_humor        5338 non-null   int64
 44  theme_gore             5338 non-null   int64
 45  theme_harem            5338 non-null   int64
 46  theme_historical       5338 non-null   int64
 47  theme_idols_(female)   5338 non-null   int64
 48  theme_isekai           5338 non-null   int64
 49  theme_iyashikei        5338 non-null   int64
 50  theme_love_polygon     5338 non-null   int64
 51  theme_mahou_shoujo     5338 non-null   int64
 52  theme_martial_arts     5338 non-null   int64
 53  theme_mecha            5338 non-null   int64
 54  theme_military         5338 non-null   int64
 55  theme_music            5338 non-null   int64
 56  theme_mythology        5338 non-null   int64
 57  theme_organized_crime  5338 non-null   int64
 58  theme_otaku_culture    5338 non-null   int64
 59  theme_other            5338 non-null   int64
 60  theme_parody           5338 non-null   int64
 61  theme_performing_arts  5338 non-null   int64
 62  theme_pets             5338 non-null   int64
 63  theme_psychological    5338 non-null   int64
 64  theme_racing           5338 non-null   int64
 65  theme_reincarnation    5338 non-null   int64
 66  theme_samurai          5338 non-null   int64
 67  theme_school           5338 non-null   int64
 68  theme_space            5338 non-null   int64
 69  theme_strategy_game    5338 non-null   int64
 70  theme_super_power      5338 non-null   int64
 71  theme_team_sports      5338 non-null   int64
 72  theme_time_travel      5338 non-null   int64
 73  theme_urban_fantasy    5338 non-null   int64
 74  theme_vampire          5338 non-null   int64
 75  theme_workplace        5338 non-null   int64
dtypes: bool(1), float64(6), int64(60), object(5), str(4)
memory usage: 3.4+ MB

## Genre, Theme, Demographic vs. Score Z-score (Multiple Regression)

In [134]:
genre_averages = df.explode('genres').groupby('genres')['score_z'].mean().sort_values()
genre_counts = df['genres'].explode().value_counts()
print(genre_counts)
genre_averages

genres
Comedy           2128
Action           1476
Fantasy          1302
Adventure        1191
Sci-Fi            980
Romance           960
Drama             919
Supernatural      518
Mystery           376
Ecchi             334
Slice of Life     305
Sports            276
Suspense          187
Horror            155
Gourmet            78
Award Winning      59
Girls Love         48
Boys Love          37
Avant Garde        35
Erotica            12
Name: count, dtype: int64

genres
Erotica         -0.812554
Ecchi           -0.326011
Avant Garde     -0.231697
Horror          -0.164101
Comedy          -0.116571
Fantasy         -0.052621
Sci-Fi          -0.025447
Adventure        0.038360
Gourmet          0.067773
Action           0.102213
Slice of Life    0.113340
Girls Love       0.114668
Boys Love        0.134078
Romance          0.204279
Supernatural     0.229057
Sports           0.265481
Mystery          0.346265
Drama            0.429990
Suspense         0.479609
Award Winning    1.364233
Name: score_z, dtype: float64

In [135]:
genre_cols = [c for c in df.columns if c.startswith('genre_')]

# drop genres that are too rare to estimate reliably (mirrors your bucket_rare logic)
min_count = 50
valid_genres = [c for c in genre_cols if df[c].sum() >= min_count]
dropped = set(genre_cols) - set(valid_genres)
if dropped:
    print(f"Dropping {len(dropped)} rare genres from regression: {sorted(dropped)}")

X = df[valid_genres].copy()
X = sm.add_constant(X)  # intercept = baseline z-score for "no genres present" (rarely meaningful alone, but needed for coefficients to be interpretable as offsets)
y = df['score_z']

model = sm.OLS(y, X, missing='drop').fit()
print(model.summary())

results = pd.DataFrame({
    'genre': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("genre != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
results

                            OLS Regression Results
==============================================================================
Dep. Variable:                score_z   R-squared:                       0.113
Model:                            OLS   Adj. R-squared:                  0.111
Method:                 Least Squares   F-statistic:                     40.01
Date:                Sun, 16 Aug 2026   Prob (F-statistic):          3.04e-125
Time:                        18:17:49   Log-Likelihood:                -7127.3
No. Observations:                5338   AIC:                         1.429e+04
Df Residuals:                    5320   BIC:                         1.441e+04
Df Model:                          17
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
const                  -0.3153      0.031    -10.130      0.000      -0.376      -0.254
genre_action            0.2627      0.031      8.423      0.000       0.202       0.324
genre_adventure         0.1109      0.033      3.350      0.001       0.046       0.176
genre_award_winning     1.1587      0.122      9.483      0.000       0.919       1.398
genre_comedy            0.0247      0.030      0.822      0.411      -0.034       0.084
genre_drama             0.4489      0.036     12.391      0.000       0.378       0.520
genre_ecchi            -0.3793      0.054     -6.992      0.000      -0.486      -0.273
genre_fantasy          -0.0251      0.033     -0.753      0.451      -0.091       0.040
genre_gourmet           0.2053      0.106      1.939      0.053      -0.002       0.413
genre_horror           -0.4041      0.081     -4.975      0.000      -0.563      -0.245
genre_mystery           0.2771      0.053      5.256      0.000       0.174       0.380
genre_other            -0.0120      0.084     -0.143      0.886      -0.177       0.153
genre_romance           0.3320      0.035      9.427      0.000       0.263       0.401
genre_sci-fi           -0.0337      0.035     -0.976      0.329      -0.101       0.034
genre_slice_of_life     0.3728      0.060      6.242      0.000       0.256       0.490
genre_sports            0.4863      0.061      8.030      0.000       0.368       0.605
genre_supernatural      0.2518      0.046      5.418      0.000       0.161       0.343
genre_suspense          0.3689      0.074      4.974      0.000       0.224       0.514
==============================================================================
Omnibus:                       16.595   Durbin-Watson:                   1.849
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               16.726
Skew:                          -0.137   Prob(JB):                     0.000233
Kurtosis:                       2.981   Cond. No.                         12.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

,genre,coef,pval,ci_low,ci_high,pval_fdr,significant
genre_award_winning,genre_award_winning,1.158750,3.631352e-21,0.919200,1.398299,3.086650e-20,True
genre_sports,genre_sports,0.486344,1.191178e-15,0.367609,0.605079,4.050004e-15,True
genre_drama,genre_drama,0.448864,8.832475e-35,0.377846,0.519882,1.501521e-33,True
genre_slice_of_life,genre_slice_of_life,0.372804,4.662310e-10,0.255714,0.489895,1.132275e-09,True
genre_suspense,genre_suspense,0.368882,6.753841e-07,0.223503,0.514260,1.043775e-06,True
genre_romance,genre_romance,0.332028,6.121718e-21,0.262983,0.401073,3.468974e-20,True
genre_mystery,genre_mystery,0.277076,1.527153e-07,0.173737,0.380415,2.884623e-07,True
genre_action,genre_action,0.262716,4.672373e-17,0.201570,0.323863,1.985759e-16,True
genre_supernatural,genre_supernatural,0.251822,6.302210e-08,0.160700,0.342944,1.339220e-07,True
genre_gourmet,genre_gourmet,0.205276,5.261340e-02,-0.002319,0.412871,6.880214e-02,False
genre_adventure,genre_adventure,0.110946,8.130537e-04,0.046025,0.175867,1.151826e-03,True
genre_comedy,genre_comedy,0.024720,4.108531e-01,-0.034202,0.083641,4.656335e-01,False
genre_other,genre_other,-0.012044,8.862223e-01,-0.177050,0.152962,8.862223e-01,False
genre_fantasy,genre_fantasy,-0.025130,4.512159e-01,-0.090518,0.040257,4.794169e-01,False
genre_sci-fi,genre_sci-fi,-0.033716,3.292858e-01,-0.101464,0.034032,3.998470e-01,False
genre_ecchi,genre_ecchi,-0.379269,3.053266e-12,-0.485615,-0.272923,8.650921e-12,True
genre_horror,genre_horror,-0.404054,6.736224e-07,-0.563278,-0.244830,1.043775e-06,True

In [136]:
theme_cols = [c for c in df.columns if c.startswith('theme_')]

# drop genres that are too rare to estimate reliably (mirrors your bucket_rare logic)
min_count = 50
valid_themes = [c for c in theme_cols if df[c].sum() >= min_count]
dropped = set(theme_cols) - set(valid_themes)
if dropped:
    print(f"Dropping {len(dropped)} rare themes from regression: {sorted(dropped)}")

X = df[valid_themes].copy()
X = sm.add_constant(X)  # intercept = baseline z-score for "no genres present" (rarely meaningful alone, but needed for coefficients to be interpretable as offsets)
y = df['score_z']

model = sm.OLS(y, X, missing='drop').fit()
print(model.summary())

results = pd.DataFrame({
    'theme': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("theme != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
results

                            OLS Regression Results
==============================================================================
Dep. Variable:                score_z   R-squared:                       0.122
Model:                            OLS   Adj. R-squared:                  0.116
Method:                 Least Squares   F-statistic:                     19.91
Date:                Sun, 16 Aug 2026   Prob (F-statistic):          1.05e-121
Time:                        18:17:49   Log-Likelihood:                -7101.0
No. Observations:                5338   AIC:                         1.428e+04
Df Residuals:                    5300   BIC:                         1.453e+04
Df Model:                          37
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                    -0.2797      0.021    -13.481      0.000      -0.320      -0.239
theme_adult_cast          0.5558      0.057      9.784      0.000       0.444       0.667
theme_anthropomorphic    -0.0513      0.076     -0.673      0.501      -0.201       0.098
theme_cgdct               0.1186      0.086      1.373      0.170      -0.051       0.288
theme_detective          -0.0239      0.107     -0.223      0.824      -0.234       0.186
theme_gag_humor           0.5473      0.082      6.689      0.000       0.387       0.708
theme_gore                0.2677      0.094      2.838      0.005       0.083       0.453
theme_harem              -0.2326      0.060     -3.906      0.000      -0.349      -0.116
theme_historical          0.3606      0.056      6.488      0.000       0.252       0.470
theme_idols_(female)      0.1419      0.116      1.224      0.221      -0.085       0.369
theme_isekai              0.2779      0.065      4.292      0.000       0.151       0.405
theme_iyashikei           0.8762      0.105      8.379      0.000       0.671       1.081
theme_love_polygon        0.5763      0.111      5.202      0.000       0.359       0.794
theme_mahou_shoujo        0.2690      0.078      3.456      0.001       0.116       0.422
theme_martial_arts        0.0903      0.092      0.985      0.325      -0.089       0.270
theme_mecha               0.0079      0.051      0.156      0.876      -0.092       0.108
theme_military            0.3884      0.067      5.820      0.000       0.258       0.519
theme_music               0.0537      0.077      0.699      0.484      -0.097       0.204
theme_mythology           0.3263      0.070      4.662      0.000       0.189       0.463
theme_organized_crime     0.5119      0.131      3.918      0.000       0.256       0.768
theme_otaku_culture       0.4488      0.118      3.810      0.000       0.218       0.680
theme_other               0.2418      0.045      5.348      0.000       0.153       0.330
theme_parody             -0.2323      0.068     -3.412      0.001      -0.366      -0.099
theme_performing_arts     0.4418      0.121      3.658      0.000       0.205       0.679
theme_pets                0.0407      0.124      0.328      0.743      -0.203       0.284
theme_psychological       0.3560      0.077      4.642      0.000       0.206       0.506
theme_racing              0.1822      0.109      1.679      0.093      -0.031       0.395
theme_reincarnation       0.0712      0.098      0.726      0.468      -0.121       0.263
theme_samurai            -0.0264      0.106     -0.248      0.804      -0.235       0.182
theme_school              0.3254      0.035      9.406      0.000       0.258       0.393
theme_space               0.3164      0.079      4.006      0.000       0.162       0.471
theme_strategy_game      -0.2232      0.073     -3.055      0.002      -0.366      -0.080
theme_super_power         0.1194      0.062      1.925      0.054      -0.002       0.241
theme_team_sports         0.4172      0.086      4.836      0.000       0.248       0.586
theme_time_travel         0.1429      0.115      1.246      0.213      -0.082       0.368
theme_urban_fantasy       0.4449      0.087      5.111      0.000       0.274       0.616
theme_vampire             0.0384      0.108      0.358      0.721      -0.172       0.249
theme_workplace          -0.0682      0.089     -0.764      0.445      -0.243       0.107
==============================================================================
Omnibus:                       10.116   Durbin-Watson:                   1.834
Prob(Omnibus):                  0.006   Jarque-Bera (JB):               10.135
Skew:                          -0.097   Prob(JB):                      0.00630
Kurtosis:                       3.087   Cond. No.                         11.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

,theme,coef,pval,ci_low,ci_high,pval_fdr,significant
theme_iyashikei,theme_iyashikei,0.876235,6.740423e-17,0.671235,1.081234,8.313188e-16,True
theme_love_polygon,theme_love_polygon,0.576331,2.050659e-07,0.359118,0.793544,9.484297e-07,True
theme_adult_cast,theme_adult_cast,0.555758,2.040119e-22,0.444401,0.667114,7.548439e-21,True
theme_gag_humor,theme_gag_humor,0.547347,2.483440e-11,0.386924,0.707771,2.297182e-10,True
theme_organized_crime,theme_organized_crime,0.511910,9.028600e-05,0.255792,0.768028,2.193310e-04,True
theme_otaku_culture,theme_otaku_culture,0.448778,1.404226e-04,0.217875,0.679682,3.056256e-04,True
theme_urban_fantasy,theme_urban_fantasy,0.444901,3.320117e-07,0.274246,0.615556,1.364937e-06,True
theme_performing_arts,theme_performing_arts,0.441838,2.562097e-04,0.205076,0.678601,5.266532e-04,True
theme_team_sports,theme_team_sports,0.417244,1.362435e-06,0.248101,0.586387,5.041008e-06,True
theme_military,theme_military,0.388398,6.240648e-09,0.257563,0.519232,3.848400e-08,True
theme_historical,theme_historical,0.360649,9.519504e-11,0.251667,0.469631,7.044433e-10,True
theme_psychological,theme_psychological,0.356015,3.536596e-06,0.205657,0.506372,1.090450e-05,True
theme_mythology,theme_mythology,0.326273,3.204408e-06,0.189080,0.463466,1.077846e-05,True
theme_school,theme_school,0.325430,7.462611e-21,0.257606,0.393254,1.380583e-19,True
theme_space,theme_space,0.316402,6.260523e-05,0.161564,0.471239,1.654567e-04,True
theme_isekai,theme_isekai,0.277858,1.804210e-05,0.150937,0.404780,5.135059e-05,True
theme_mahou_shoujo,theme_mahou_shoujo,0.269034,5.532502e-04,0.116410,0.421659,1.077382e-03,True
theme_gore,theme_gore,0.267684,4.556661e-03,0.082777,0.452592,7.663475e-03,True
theme_other,theme_other,0.241839,9.291188e-08,0.153180,0.330497,4.911056e-07,True
theme_racing,theme_racing,0.182172,9.325717e-02,-0.030563,0.394907,1.437715e-01,False
theme_time_travel,theme_time_travel,0.142946,2.129977e-01,-0.082048,0.367939,3.029852e-01,False
theme_idols_(female),theme_idols_(female),0.141857,2.210973e-01,-0.085392,0.369106,3.029852e-01,False
theme_super_power,theme_super_power,0.119412,5.431876e-02,-0.002215,0.241039,8.738235e-02,False
theme_cgdct,theme_cgdct,0.118573,1.697733e-01,-0.050714,0.287860,2.512645e-01,False
theme_martial_arts,theme_martial_arts,0.090288,3.247351e-01,-0.089434,0.270009,4.291143e-01,False
theme_reincarnation,theme_reincarnation,0.071205,4.678220e-01,-0.121048,0.263457,5.769805e-01,False
theme_music,theme_music,0.053690,4.843752e-01,-0.096817,0.204198,5.781252e-01,False
theme_pets,theme_pets,0.040676,7.431907e-01,-0.202702,0.284055,8.087663e-01,False
theme_vampire,theme_vampire,0.038440,7.207230e-01,-0.172344,0.249223,8.080834e-01,False
theme_mecha,theme_mecha,0.007913,8.763705e-01,-0.091795,0.107621,8.763705e-01,False
theme_detective,theme_detective,-0.023871,8.239135e-01,-0.234171,0.186429,8.468000e-01,False
theme_samurai,theme_samurai,-0.026419,8.039157e-01,-0.235014,0.182175,8.468000e-01,False
theme_anthropomorphic,theme_anthropomorphic,-0.051286,5.010775e-01,-0.200714,0.098142,5.793708e-01,False
theme_workplace,theme_workplace,-0.068165,4.446743e-01,-0.242988,0.106658,5.673431e-01,False
theme_strategy_game,theme_strategy_game,-0.223241,2.260279e-03,-0.366486,-0.079995,3.982397e-03,True
theme_parody,theme_parody,-0.232294,6.499764e-04,-0.365767,-0.098822,1.202456e-03,True
theme_harem,theme_harem,-0.232581,9.484583e-05,-0.349300,-0.115861,2.193310e-04,True

In [137]:
demo_cols = [c for c in df.columns if c.startswith('demo_')]

# drop genres that are too rare to estimate reliably (mirrors your bucket_rare logic)
min_count = 50
valid_demos = [c for c in demo_cols if df[c].sum() >= min_count]
dropped = set(demo_cols) - set(valid_demos)
if dropped:
    print(f"Dropping {len(dropped)} rare demographics from regression: {sorted(dropped)}")

X = df[valid_demos].copy()
X = sm.add_constant(X)  # intercept = baseline z-score for "no genres present" (rarely meaningful alone, but needed for coefficients to be interpretable as offsets)
y = df['score_z']

model = sm.OLS(y, X, missing='drop').fit()
print(model.summary())

results = pd.DataFrame({
    'demographic': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("demographic != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
results

                            OLS Regression Results
==============================================================================
Dep. Variable:                score_z   R-squared:                       0.123
Model:                            OLS   Adj. R-squared:                  0.123
Method:                 Least Squares   F-statistic:                     150.1
Date:                Sun, 16 Aug 2026   Prob (F-statistic):          1.37e-149
Time:                        18:17:49   Log-Likelihood:                -7096.8
No. Observations:                5338   AIC:                         1.421e+04
Df Residuals:                    5332   BIC:                         1.425e+04
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -0.1503      0.016     -9.358      0.000      -0.182      -0.119
demo_josei       0.3775      0.105      3.601      0.000       0.172       0.583
demo_kids       -0.5518      0.048    -11.437      0.000      -0.646      -0.457
demo_seinen      0.5104      0.044     11.643      0.000       0.425       0.596
demo_shoujo      0.5871      0.064      9.234      0.000       0.462       0.712
demo_shounen     0.6776      0.034     19.665      0.000       0.610       0.745
==============================================================================
Omnibus:                       19.577   Durbin-Watson:                   1.838
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               19.680
Skew:                          -0.144   Prob(JB):                     5.33e-05
Kurtosis:                       3.071   Cond. No.                         8.59
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

,demographic,coef,pval,ci_low,ci_high,pval_fdr,significant
demo_shounen,demo_shounen,0.677593,3.587427e-83,0.610043,0.745142,1.793714e-82,True
demo_shoujo,demo_shoujo,0.587145,3.697029e-20,0.462486,0.711804,4.621286e-20,True
demo_seinen,demo_seinen,0.510448,5.885124e-31,0.424500,0.596395,1.471281e-30,True
demo_josei,demo_josei,0.377501,3.199612e-04,0.171983,0.583018,3.199612e-04,True
demo_kids,demo_kids,-0.551774,6.104430e-30,-0.646355,-0.457193,1.017405e-29,True

## Genre, Theme, Demographic vs. WC Z-score (Multiple Regression)

In [138]:
genre_cols = [c for c in df.columns if c.startswith('genre_')]

# drop genres that are too rare to estimate reliably (mirrors your bucket_rare logic)
min_count = 50
valid_genres = [c for c in genre_cols if df[c].sum() >= min_count]
dropped = set(genre_cols) - set(valid_genres)
if dropped:
    print(f"Dropping {len(dropped)} rare genres from regression: {sorted(dropped)}")

X = df[valid_genres].copy()
X = sm.add_constant(X)  # intercept = baseline z-score for "no genres present" (rarely meaningful alone, but needed for coefficients to be interpretable as offsets)
y = df['wc_z']

model = sm.OLS(y, X, missing='drop').fit()
print(model.summary())

results = pd.DataFrame({
    'genre': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("genre != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
results

                            OLS Regression Results
==============================================================================
Dep. Variable:                   wc_z   R-squared:                       0.215
Model:                            OLS   Adj. R-squared:                  0.213
Method:                 Least Squares   F-statistic:                     85.94
Date:                Sun, 16 Aug 2026   Prob (F-statistic):          1.73e-264
Time:                        18:17:50   Log-Likelihood:                -6800.7
No. Observations:                5338   AIC:                         1.364e+04
Df Residuals:                    5320   BIC:                         1.376e+04
Df Model:                          17
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
const                  -0.5635      0.029    -19.247      0.000      -0.621      -0.506
genre_action            0.4569      0.029     15.571      0.000       0.399       0.514
genre_adventure         0.1305      0.031      4.190      0.000       0.069       0.192
genre_award_winning     0.9021      0.115      7.848      0.000       0.677       1.127
genre_comedy           -0.0199      0.028     -0.704      0.481      -0.075       0.036
genre_drama             0.3602      0.034     10.571      0.000       0.293       0.427
genre_ecchi             0.3674      0.051      7.200      0.000       0.267       0.467
genre_fantasy           0.2862      0.031      9.121      0.000       0.225       0.348
genre_gourmet           0.2233      0.100      2.242      0.025       0.028       0.419
genre_horror           -0.0746      0.076     -0.977      0.329      -0.224       0.075
genre_mystery           0.2267      0.050      4.572      0.000       0.129       0.324
genre_other             0.3063      0.079      3.868      0.000       0.151       0.461
genre_romance           0.7056      0.033     21.299      0.000       0.641       0.771
genre_sci-fi            0.0732      0.033      2.252      0.024       0.009       0.137
genre_slice_of_life     0.0999      0.056      1.778      0.076      -0.010       0.210
genre_sports            0.4415      0.057      7.749      0.000       0.330       0.553
genre_supernatural      0.3444      0.044      7.877      0.000       0.259       0.430
genre_suspense          0.6990      0.070     10.020      0.000       0.562       0.836
==============================================================================
Omnibus:                       13.251   Durbin-Watson:                   1.792
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               13.344
Skew:                          -0.122   Prob(JB):                      0.00127
Kurtosis:                       2.974   Cond. No.                         12.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

,genre,coef,pval,ci_low,ci_high,pval_fdr,significant
genre_award_winning,genre_award_winning,0.902129,5.054692e-15,0.676793,1.127464,1.227568e-14,True
genre_romance,genre_romance,0.705622,1.148484e-96,0.640674,0.770570,1.952422e-95,True
genre_suspense,genre_suspense,0.698972,2.004338e-23,0.562220,0.835724,8.518438e-23,True
genre_action,genre_action,0.456861,1.702383e-53,0.399343,0.514379,1.447026e-52,True
genre_sports,genre_sports,0.441491,1.100465e-14,0.329802,0.553181,2.338487e-14,True
genre_ecchi,genre_ecchi,0.367393,6.866049e-13,0.267358,0.467429,1.296920e-12,True
genre_drama,genre_drama,0.360220,7.326992e-26,0.293416,0.427023,4.151962e-25,True
genre_supernatural,genre_supernatural,0.344426,4.022291e-15,0.258711,0.430141,1.139649e-14,True
genre_other,genre_other,0.306254,1.110051e-04,0.151039,0.461469,1.572572e-04,True
genre_fantasy,genre_fantasy,0.286157,1.039264e-19,0.224649,0.347665,3.533498e-19,True
genre_mystery,genre_mystery,0.226691,4.946486e-06,0.129483,0.323898,8.409026e-06,True
genre_gourmet,genre_gourmet,0.223307,2.501501e-02,0.028030,0.418583,3.037537e-02,True
genre_adventure,genre_adventure,0.130537,2.829026e-05,0.069468,0.191605,4.372132e-05,True
genre_slice_of_life,genre_slice_of_life,0.099877,7.551271e-02,-0.010266,0.210019,8.558107e-02,False
genre_sci-fi,genre_sci-fi,0.073202,2.437249e-02,0.009474,0.136930,3.037537e-02,True
genre_comedy,genre_comedy,-0.019916,4.811958e-01,-0.075341,0.035509,4.811958e-01,False
genre_horror,genre_horror,-0.074623,3.287454e-01,-0.224399,0.075153,3.492920e-01,False

In [139]:
theme_cols = [c for c in df.columns if c.startswith('theme_')]

# drop genres that are too rare to estimate reliably (mirrors your bucket_rare logic)
min_count = 50
valid_themes = [c for c in theme_cols if df[c].sum() >= min_count]
dropped = set(theme_cols) - set(valid_themes)
if dropped:
    print(f"Dropping {len(dropped)} rare themes from regression: {sorted(dropped)}")

X = df[valid_themes].copy()
X = sm.add_constant(X)  # intercept = baseline z-score for "no genres present" (rarely meaningful alone, but needed for coefficients to be interpretable as offsets)
y = df['wc_z']

model = sm.OLS(y, X, missing='drop').fit()
print(model.summary())

results = pd.DataFrame({
    'theme': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("theme != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
results

                            OLS Regression Results
==============================================================================
Dep. Variable:                   wc_z   R-squared:                       0.203
Model:                            OLS   Adj. R-squared:                  0.197
Method:                 Least Squares   F-statistic:                     36.49
Date:                Sun, 16 Aug 2026   Prob (F-statistic):          2.86e-229
Time:                        18:17:50   Log-Likelihood:                -6842.6
No. Observations:                5338   AIC:                         1.376e+04
Df Residuals:                    5300   BIC:                         1.401e+04
Df Model:                          37
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                    -0.2780      0.020    -14.060      0.000      -0.317      -0.239
theme_adult_cast          0.4449      0.054      8.222      0.000       0.339       0.551
theme_anthropomorphic    -0.2847      0.073     -3.920      0.000      -0.427      -0.142
theme_cgdct               0.0220      0.082      0.268      0.789      -0.139       0.183
theme_detective          -0.0553      0.102     -0.541      0.588      -0.256       0.145
theme_gag_humor           0.1759      0.078      2.256      0.024       0.023       0.329
theme_gore                0.7183      0.090      7.993      0.000       0.542       0.894
theme_harem               0.5231      0.057      9.222      0.000       0.412       0.634
theme_historical          0.1131      0.053      2.136      0.033       0.009       0.217
theme_idols_(female)     -0.1608      0.110     -1.456      0.145      -0.377       0.056
theme_isekai              0.6836      0.062     11.083      0.000       0.563       0.805
theme_iyashikei           0.2861      0.100      2.871      0.004       0.091       0.481
theme_love_polygon        0.7693      0.106      7.288      0.000       0.562       0.976
theme_mahou_shoujo        0.0075      0.074      0.102      0.919      -0.138       0.153
theme_martial_arts        0.2011      0.087      2.303      0.021       0.030       0.372
theme_mecha              -0.0363      0.048     -0.748      0.454      -0.131       0.059
theme_military            0.3777      0.064      5.941      0.000       0.253       0.502
theme_music              -0.2642      0.073     -3.612      0.000      -0.408      -0.121
theme_mythology           0.2325      0.067      3.487      0.000       0.102       0.363
theme_organized_crime     0.4708      0.124      3.782      0.000       0.227       0.715
theme_otaku_culture       0.5054      0.112      4.504      0.000       0.285       0.725
theme_other               0.2633      0.043      6.111      0.000       0.179       0.348
theme_parody             -0.3117      0.065     -4.806      0.000      -0.439      -0.185
theme_performing_arts     0.0607      0.115      0.528      0.598      -0.165       0.286
theme_pets               -0.6047      0.118     -5.112      0.000      -0.837      -0.373
theme_psychological       0.5890      0.073      8.060      0.000       0.446       0.732
theme_racing             -0.1759      0.103     -1.701      0.089      -0.379       0.027
theme_reincarnation       0.2795      0.093      2.991      0.003       0.096       0.463
theme_samurai            -0.0796      0.101     -0.786      0.432      -0.278       0.119
theme_school              0.4384      0.033     13.302      0.000       0.374       0.503
theme_space               0.2710      0.075      3.602      0.000       0.124       0.419
theme_strategy_game      -0.4917      0.070     -7.064      0.000      -0.628      -0.355
theme_super_power         0.2583      0.059      4.369      0.000       0.142       0.374
theme_team_sports         0.1551      0.082      1.887      0.059      -0.006       0.316
theme_time_travel         0.1774      0.109      1.622      0.105      -0.037       0.392
theme_urban_fantasy       0.5548      0.083      6.690      0.000       0.392       0.717
theme_vampire             0.4132      0.102      4.034      0.000       0.212       0.614
theme_workplace          -0.1764      0.085     -2.076      0.038      -0.343      -0.010
==============================================================================
Omnibus:                        2.796   Durbin-Watson:                   1.743
Prob(Omnibus):                  0.247   Jarque-Bera (JB):                2.742
Skew:                          -0.050   Prob(JB):                        0.254
Kurtosis:                       3.048   Cond. No.                         11.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

,theme,coef,pval,ci_low,ci_high,pval_fdr,significant
theme_love_polygon,theme_love_polygon,0.769326,3.614233e-13,0.562378,0.976275,1.910380e-12,True
theme_gore,theme_gore,0.718299,1.600749e-15,0.542130,0.894469,9.871284e-15,True
theme_isekai,theme_isekai,0.683643,3.086043e-28,0.562719,0.804567,5.709180e-27,True
theme_psychological,theme_psychological,0.588995,9.320513e-16,0.445743,0.732247,6.897179e-15,True
theme_urban_fantasy,theme_urban_fantasy,0.554843,2.462987e-11,0.392252,0.717433,1.012561e-10,True
theme_harem,theme_harem,0.523114,4.120861e-20,0.411910,0.634318,5.082396e-19,True
theme_otaku_culture,theme_otaku_culture,0.505378,6.825435e-06,0.285386,0.725370,1.803865e-05,True
theme_organized_crime,theme_organized_crime,0.470782,1.571235e-04,0.226767,0.714797,3.229761e-04,True
theme_adult_cast,theme_adult_cast,0.444950,2.498835e-16,0.338855,0.551045,2.311422e-15,True
theme_school,theme_school,0.438449,9.755981e-40,0.373830,0.503068,3.609713e-38,True
theme_vampire,theme_vampire,0.413218,5.565576e-05,0.212395,0.614041,1.287039e-04,True
theme_military,theme_military,0.377728,3.021287e-09,0.253076,0.502380,1.016251e-08,True
theme_iyashikei,theme_iyashikei,0.286062,4.104142e-03,0.090750,0.481374,6.602316e-03,True
theme_reincarnation,theme_reincarnation,0.279475,2.791826e-03,0.096308,0.462643,4.695344e-03,True
theme_space,theme_space,0.271038,3.188636e-04,0.123518,0.418559,5.898977e-04,True
theme_other,theme_other,0.263303,1.061474e-09,0.178833,0.347772,3.927453e-09,True
theme_super_power,theme_super_power,0.258256,1.271492e-05,0.142376,0.374136,3.136348e-05,True
theme_mythology,theme_mythology,0.232470,4.931368e-04,0.101760,0.363180,8.688602e-04,True
theme_martial_arts,theme_martial_arts,0.201109,2.134448e-02,0.029881,0.372338,3.290608e-02,True
theme_time_travel,theme_time_travel,0.177362,1.048535e-01,-0.036999,0.391724,1.293193e-01,False
theme_gag_humor,theme_gag_humor,0.175868,2.412752e-02,0.023025,0.328710,3.570874e-02,True
theme_team_sports,theme_team_sports,0.155094,5.925060e-02,-0.006056,0.316244,7.829543e-02,False
theme_historical,theme_historical,0.113118,3.274611e-02,0.009286,0.216950,4.660024e-02,True
theme_performing_arts,theme_performing_arts,0.060706,5.978114e-01,-0.164868,0.286281,6.319721e-01,False
theme_cgdct,theme_cgdct,0.022042,7.887747e-01,-0.139245,0.183329,8.106851e-01,False
theme_mahou_shoujo,theme_mahou_shoujo,0.007547,9.189630e-01,-0.137865,0.152959,9.189630e-01,False
theme_mecha,theme_mecha,-0.036262,4.543004e-01,-0.131258,0.058735,5.093671e-01,False
theme_detective,theme_detective,-0.055323,5.883211e-01,-0.255685,0.145039,6.319721e-01,False
theme_samurai,theme_samurai,-0.079644,4.321138e-01,-0.278382,0.119093,4.996316e-01,False
theme_idols_(female),theme_idols_(female),-0.160806,1.454429e-01,-0.377316,0.055704,1.735932e-01,False
theme_racing,theme_racing,-0.175913,8.890998e-02,-0.378595,0.026769,1.134369e-01,False
theme_workplace,theme_workplace,-0.176406,3.791587e-02,-0.342968,-0.009845,5.195878e-02,False
theme_music,theme_music,-0.264166,3.072296e-04,-0.407561,-0.120771,5.898977e-04,True
theme_anthropomorphic,theme_anthropomorphic,-0.284678,8.964063e-05,-0.427045,-0.142312,1.951002e-04,True
theme_parody,theme_parody,-0.311727,1.584840e-06,-0.438893,-0.184562,4.510699e-06,True
theme_strategy_game,theme_strategy_game,-0.491750,1.829965e-12,-0.628226,-0.355274,8.463588e-12,True
theme_pets,theme_pets,-0.604667,3.296912e-07,-0.836545,-0.372789,1.016548e-06,True

In [140]:
demo_cols = [c for c in df.columns if c.startswith('demo_')]

# drop genres that are too rare to estimate reliably (mirrors your bucket_rare logic)
min_count = 50
valid_demos = [c for c in demo_cols if df[c].sum() >= min_count]
dropped = set(demo_cols) - set(valid_demos)
if dropped:
    print(f"Dropping {len(dropped)} rare demographics from regression: {sorted(dropped)}")

X = df[valid_demos].copy()
X = sm.add_constant(X)  # intercept = baseline z-score for "no genres present" (rarely meaningful alone, but needed for coefficients to be interpretable as offsets)
y = df['wc_z']

model = sm.OLS(y, X, missing='drop').fit()
print(model.summary())

results = pd.DataFrame({
    'demographic': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("demographic != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
results

                            OLS Regression Results
==============================================================================
Dep. Variable:                   wc_z   R-squared:                       0.155
Model:                            OLS   Adj. R-squared:                  0.154
Method:                 Least Squares   F-statistic:                     195.0
Date:                Sun, 16 Aug 2026   Prob (F-statistic):          2.53e-191
Time:                        18:17:50   Log-Likelihood:                -7000.3
No. Observations:                5338   AIC:                         1.401e+04
Df Residuals:                    5332   BIC:                         1.405e+04
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -0.0838      0.016     -5.312      0.000      -0.115      -0.053
demo_josei       0.2182      0.103      2.120      0.034       0.016       0.420
demo_kids       -0.9832      0.047    -20.751      0.000      -1.076      -0.890
demo_seinen      0.3775      0.043      8.769      0.000       0.293       0.462
demo_shoujo      0.4447      0.062      7.120      0.000       0.322       0.567
demo_shounen     0.5993      0.034     17.712      0.000       0.533       0.666
==============================================================================
Omnibus:                       21.664   Durbin-Watson:                   1.757
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               21.878
Skew:                          -0.157   Prob(JB):                     1.77e-05
Kurtosis:                       2.990   Cond. No.                         8.59
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

,demographic,coef,pval,ci_low,ci_high,pval_fdr,significant
demo_shounen,demo_shounen,0.599346,2.982820e-68,0.533007,0.665685,7.457049e-68,True
demo_shoujo,demo_shoujo,0.444651,1.219810e-12,0.322227,0.567076,1.524762e-12,True
demo_seinen,demo_seinen,0.377546,2.394251e-18,0.293139,0.461953,3.990419e-18,True
demo_josei,demo_josei,0.218216,3.409230e-02,0.016382,0.420050,3.409230e-02,True
demo_kids,demo_kids,-0.983189,4.813559e-92,-1.076075,-0.890303,2.406780e-91,True

## Genre, Theme, Demographic vs. Favorites Z-score (Multiple Regression)

In [141]:
genre_cols = [c for c in df.columns if c.startswith('genre_')]

# drop genres that are too rare to estimate reliably (mirrors your bucket_rare logic)
min_count = 50
valid_genres = [c for c in genre_cols if df[c].sum() >= min_count]
dropped = set(genre_cols) - set(valid_genres)
if dropped:
    print(f"Dropping {len(dropped)} rare genres from regression: {sorted(dropped)}")

X = df[valid_genres].copy()
X = sm.add_constant(X)  # intercept = baseline z-score for "no genres present" (rarely meaningful alone, but needed for coefficients to be interpretable as offsets)
y = df['favorites_z']

model = sm.OLS(y, X, missing='drop').fit()
print(model.summary())

results = pd.DataFrame({
    'genre': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("genre != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
results

                            OLS Regression Results
==============================================================================
Dep. Variable:            favorites_z   R-squared:                       0.196
Model:                            OLS   Adj. R-squared:                  0.194
Method:                 Least Squares   F-statistic:                     76.39
Date:                Sun, 16 Aug 2026   Prob (F-statistic):          8.60e-237
Time:                        18:17:50   Log-Likelihood:                -6863.3
No. Observations:                5338   AIC:                         1.376e+04
Df Residuals:                    5320   BIC:                         1.388e+04
Df Model:                          17
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
const                  -0.4853      0.030    -16.381      0.000      -0.543      -0.427
genre_action            0.4204      0.030     14.162      0.000       0.362       0.479
genre_adventure         0.1005      0.032      3.188      0.001       0.039       0.162
genre_award_winning     1.1633      0.116     10.003      0.000       0.935       1.391
genre_comedy           -0.0647      0.029     -2.261      0.024      -0.121      -0.009
genre_drama             0.4084      0.034     11.845      0.000       0.341       0.476
genre_ecchi             0.1697      0.052      3.287      0.001       0.068       0.271
genre_fantasy           0.2049      0.032      6.454      0.000       0.143       0.267
genre_gourmet           0.1601      0.101      1.588      0.112      -0.038       0.358
genre_horror           -0.1728      0.077     -2.236      0.025      -0.324      -0.021
genre_mystery           0.2609      0.050      5.201      0.000       0.163       0.359
genre_other             0.3638      0.080      4.542      0.000       0.207       0.521
genre_romance           0.6376      0.034     19.022      0.000       0.572       0.703
genre_sci-fi            0.0398      0.033      1.209      0.227      -0.025       0.104
genre_slice_of_life     0.1440      0.057      2.533      0.011       0.033       0.255
genre_sports            0.3969      0.058      6.885      0.000       0.284       0.510
genre_supernatural      0.2848      0.044      6.437      0.000       0.198       0.371
genre_suspense          0.7362      0.071     10.431      0.000       0.598       0.875
==============================================================================
Omnibus:                       33.624   Durbin-Watson:                   1.829
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               34.128
Skew:                           0.192   Prob(JB):                     3.88e-08
Kurtosis:                       2.924   Cond. No.                         12.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

,genre,coef,pval,ci_low,ci_high,pval_fdr,significant
genre_award_winning,genre_award_winning,1.163331,2.376002e-23,0.935338,1.391325,8.078407e-23,True
genre_suspense,genre_suspense,0.736248,3.116643e-25,0.597883,0.874613,1.324573e-24,True
genre_romance,genre_romance,0.637626,4.179843e-78,0.571912,0.703340,7.105733e-77,True
genre_action,genre_action,0.420404,1.017789e-44,0.362207,0.478600,8.651208e-44,True
genre_drama,genre_drama,0.408394,5.750153e-32,0.340802,0.475986,3.258420e-31,True
genre_sports,genre_sports,0.396886,6.445169e-12,0.283879,0.509893,1.826131e-11,True
genre_other,genre_other,0.363829,5.703478e-06,0.206784,0.520875,9.695913e-06,True
genre_supernatural,genre_supernatural,0.284772,1.324351e-10,0.198045,0.371498,2.814247e-10,True
genre_mystery,genre_mystery,0.260944,2.054302e-07,0.162590,0.359298,3.880348e-07,True
genre_fantasy,genre_fantasy,0.204872,1.188536e-10,0.142639,0.267106,2.814247e-10,True
genre_ecchi,genre_ecchi,0.169687,1.020542e-03,0.068472,0.270903,1.577201e-03,True
genre_gourmet,genre_gourmet,0.160078,1.122758e-01,-0.037502,0.357658,1.192930e-01,False
genre_slice_of_life,genre_slice_of_life,0.144009,1.132779e-02,0.032567,0.255451,1.481327e-02,True
genre_adventure,genre_adventure,0.100492,1.439079e-03,0.038703,0.162281,2.038696e-03,True
genre_sci-fi,genre_sci-fi,0.039764,2.267316e-01,-0.024716,0.104243,2.267316e-01,False
genre_comedy,genre_comedy,-0.064673,2.381014e-02,-0.120752,-0.008594,2.878379e-02,True
genre_horror,genre_horror,-0.172841,2.539746e-02,-0.324384,-0.021298,2.878379e-02,True

In [142]:
theme_cols = [c for c in df.columns if c.startswith('theme_')]

# drop genres that are too rare to estimate reliably (mirrors your bucket_rare logic)
min_count = 50
valid_themes = [c for c in theme_cols if df[c].sum() >= min_count]
dropped = set(theme_cols) - set(valid_themes)
if dropped:
    print(f"Dropping {len(dropped)} rare themes from regression: {sorted(dropped)}")

X = df[valid_themes].copy()
X = sm.add_constant(X)  # intercept = baseline z-score for "no genres present" (rarely meaningful alone, but needed for coefficients to be interpretable as offsets)
y = df['favorites_z']

model = sm.OLS(y, X, missing='drop').fit()
print(model.summary())

results = pd.DataFrame({
    'theme': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("theme != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
results

                            OLS Regression Results
==============================================================================
Dep. Variable:            favorites_z   R-squared:                       0.184
Model:                            OLS   Adj. R-squared:                  0.179
Method:                 Least Squares   F-statistic:                     32.37
Date:                Sun, 16 Aug 2026   Prob (F-statistic):          2.62e-203
Time:                        18:17:50   Log-Likelihood:                -6902.4
No. Observations:                5338   AIC:                         1.388e+04
Df Residuals:                    5300   BIC:                         1.413e+04
Df Model:                          37
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                    -0.2949      0.020    -14.749      0.000      -0.334      -0.256
theme_adult_cast          0.4913      0.055      8.977      0.000       0.384       0.599
theme_anthropomorphic    -0.2145      0.073     -2.921      0.004      -0.358      -0.071
theme_cgdct              -0.0105      0.083     -0.126      0.900      -0.174       0.153
theme_detective          -0.0488      0.103     -0.472      0.637      -0.251       0.154
theme_gag_humor           0.2817      0.079      3.573      0.000       0.127       0.436
theme_gore                0.7129      0.091      7.845      0.000       0.535       0.891
theme_harem               0.3078      0.057      5.365      0.000       0.195       0.420
theme_historical          0.1775      0.054      3.314      0.001       0.072       0.282
theme_idols_(female)     -0.1954      0.112     -1.750      0.080      -0.414       0.024
theme_isekai              0.5691      0.062      9.124      0.000       0.447       0.691
theme_iyashikei           0.4938      0.101      4.902      0.000       0.296       0.691
theme_love_polygon        0.8854      0.107      8.294      0.000       0.676       1.095
theme_mahou_shoujo        0.1504      0.075      2.005      0.045       0.003       0.297
theme_martial_arts        0.1715      0.088      1.942      0.052      -0.002       0.345
theme_mecha              -0.0452      0.049     -0.922      0.356      -0.141       0.051
theme_military            0.4046      0.064      6.292      0.000       0.278       0.531
theme_music              -0.0342      0.074     -0.462      0.644      -0.179       0.111
theme_mythology           0.2125      0.067      3.152      0.002       0.080       0.345
theme_organized_crime     0.5496      0.126      4.366      0.000       0.303       0.796
theme_otaku_culture       0.4663      0.113      4.109      0.000       0.244       0.689
theme_other               0.2495      0.044      5.725      0.000       0.164       0.335
theme_parody             -0.2726      0.066     -4.156      0.000      -0.401      -0.144
theme_performing_arts     0.0811      0.116      0.697      0.486      -0.147       0.309
theme_pets               -0.4918      0.120     -4.112      0.000      -0.726      -0.257
theme_psychological       0.7060      0.074      9.553      0.000       0.561       0.851
theme_racing             -0.0736      0.105     -0.704      0.481      -0.279       0.131
theme_reincarnation       0.2418      0.094      2.559      0.011       0.057       0.427
theme_samurai            -0.0699      0.103     -0.682      0.496      -0.271       0.131
theme_school              0.4267      0.033     12.800      0.000       0.361       0.492
theme_space               0.2929      0.076      3.850      0.000       0.144       0.442
theme_strategy_game      -0.4615      0.070     -6.556      0.000      -0.600      -0.324
theme_super_power         0.2531      0.060      4.234      0.000       0.136       0.370
theme_team_sports         0.1906      0.083      2.292      0.022       0.028       0.354
theme_time_travel         0.2346      0.111      2.122      0.034       0.018       0.451
theme_urban_fantasy       0.5359      0.084      6.390      0.000       0.372       0.700
theme_vampire             0.3705      0.104      3.577      0.000       0.167       0.574
theme_workplace          -0.2174      0.086     -2.530      0.011      -0.386      -0.049
==============================================================================
Omnibus:                       54.238   Durbin-Watson:                   1.781
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               55.663
Skew:                           0.249   Prob(JB):                     8.18e-13
Kurtosis:                       3.046   Cond. No.                         11.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

,theme,coef,pval,ci_low,ci_high,pval_fdr,significant
theme_love_polygon,theme_love_polygon,0.885418,1.374458e-16,0.676137,1.094699,1.017099e-15,True
theme_gore,theme_gore,0.712918,5.201365e-15,0.534763,0.891073,3.207508e-14,True
theme_psychological,theme_psychological,0.705953,1.867771e-21,0.561087,0.850820,3.455377e-20,True
theme_isekai,theme_isekai,0.569142,1.007342e-19,0.446856,0.691429,1.242388e-18,True
theme_organized_crime,theme_organized_crime,0.549550,1.290176e-05,0.302786,0.796315,3.672039e-05,True
theme_urban_fantasy,theme_urban_fantasy,0.535938,1.800838e-10,0.371515,0.700361,8.328877e-10,True
theme_iyashikei,theme_iyashikei,0.493836,9.790966e-07,0.296323,0.691349,3.018881e-06,True
theme_adult_cast,theme_adult_cast,0.491272,3.811760e-19,0.383982,0.598562,3.525878e-18,True
theme_otaku_culture,theme_otaku_culture,0.466330,4.028489e-05,0.243859,0.688801,8.767887e-05,True
theme_school,theme_school,0.426671,5.747216e-37,0.361324,0.492018,2.126470e-35,True
theme_military,theme_military,0.404553,3.395402e-10,0.278496,0.530609,1.395887e-09,True
theme_vampire,theme_vampire,0.370504,3.512995e-04,0.167419,0.573590,6.579391e-04,True
theme_harem,theme_harem,0.307781,8.419507e-08,0.195324,0.420238,2.832016e-07,True
theme_space,theme_space,0.292945,1.197116e-04,0.143762,0.442128,2.460739e-04,True
theme_gag_humor,theme_gag_humor,0.281730,3.556428e-04,0.127165,0.436295,6.579391e-04,True
theme_super_power,theme_super_power,0.253093,2.334263e-05,0.135907,0.370278,6.169123e-05,True
theme_other,theme_other,0.249452,1.091676e-08,0.164031,0.334872,4.039200e-08,True
theme_reincarnation,theme_reincarnation,0.241770,1.053119e-02,0.056539,0.427001,1.623559e-02,True
theme_time_travel,theme_time_travel,0.234635,3.389153e-02,0.017858,0.451411,4.644395e-02,True
theme_mythology,theme_mythology,0.212547,1.628946e-03,0.080364,0.344730,2.739592e-03,True
theme_team_sports,theme_team_sports,0.190550,2.193083e-02,0.027584,0.353516,3.120926e-02,True
theme_historical,theme_historical,0.177476,9.274369e-04,0.072474,0.282478,1.634055e-03,True
theme_martial_arts,theme_martial_arts,0.171515,5.221253e-02,-0.001643,0.344673,6.661598e-02,False
theme_mahou_shoujo,theme_mahou_shoujo,0.150363,4.506013e-02,0.003312,0.297413,5.954374e-02,False
theme_performing_arts,theme_performing_arts,0.081142,4.856262e-01,-0.146974,0.309259,5.392544e-01,False
theme_cgdct,theme_cgdct,-0.010479,8.997743e-01,-0.173584,0.152626,8.997743e-01,False
theme_music,theme_music,-0.034164,6.441998e-01,-0.179175,0.110847,6.620942e-01,False
theme_mecha,theme_mecha,-0.045193,3.564436e-01,-0.141260,0.050874,4.254327e-01,False
theme_detective,theme_detective,-0.048832,6.366126e-01,-0.251452,0.153787,6.620942e-01,False
theme_samurai,theme_samurai,-0.069874,4.955310e-01,-0.270851,0.131102,5.392544e-01,False
theme_racing,theme_racing,-0.073621,4.813659e-01,-0.278587,0.131344,5.392544e-01,False
theme_idols_(female),theme_idols_(female),-0.195438,8.019396e-02,-0.414388,0.023511,9.890588e-02,False
theme_anthropomorphic,theme_anthropomorphic,-0.214517,3.503561e-03,-0.358488,-0.070546,5.636164e-03,True
theme_workplace,theme_workplace,-0.217400,1.142638e-02,-0.385839,-0.048962,1.691104e-02,True
theme_parody,theme_parody,-0.272616,3.291218e-05,-0.401214,-0.144018,8.118338e-05,True
theme_strategy_game,theme_strategy_game,-0.461520,6.066628e-11,-0.599534,-0.323506,3.206646e-10,True
theme_pets,theme_pets,-0.491848,3.981907e-05,-0.726339,-0.257357,8.767887e-05,True

In [143]:
demo_cols = [c for c in df.columns if c.startswith('demo_')]

# drop genres that are too rare to estimate reliably (mirrors your bucket_rare logic)
min_count = 50
valid_demos = [c for c in demo_cols if df[c].sum() >= min_count]
dropped = set(demo_cols) - set(valid_demos)
if dropped:
    print(f"Dropping {len(dropped)} rare demographics from regression: {sorted(dropped)}")

X = df[valid_demos].copy()
X = sm.add_constant(X)  # intercept = baseline z-score for "no genres present" (rarely meaningful alone, but needed for coefficients to be interpretable as offsets)
y = df['favorites_z']

model = sm.OLS(y, X, missing='drop').fit()
print(model.summary())

results = pd.DataFrame({
    'demographic': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("demographic != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
results

                            OLS Regression Results
==============================================================================
Dep. Variable:            favorites_z   R-squared:                       0.134
Model:                            OLS   Adj. R-squared:                  0.133
Method:                 Least Squares   F-statistic:                     164.6
Date:                Sun, 16 Aug 2026   Prob (F-statistic):          3.02e-163
Time:                        18:17:50   Log-Likelihood:                -7063.1
No. Observations:                5338   AIC:                         1.414e+04
Df Residuals:                    5332   BIC:                         1.418e+04
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -0.0998      0.016     -6.256      0.000      -0.131      -0.069
demo_josei       0.2953      0.104      2.835      0.005       0.091       0.500
demo_kids       -0.8299      0.048    -17.311      0.000      -0.924      -0.736
demo_seinen      0.3760      0.044      8.630      0.000       0.291       0.461
demo_shoujo      0.5469      0.063      8.654      0.000       0.423       0.671
demo_shounen     0.5950      0.034     17.378      0.000       0.528       0.662
==============================================================================
Omnibus:                       13.218   Durbin-Watson:                   1.791
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               13.299
Skew:                           0.118   Prob(JB):                      0.00129
Kurtosis:                       2.936   Cond. No.                         8.59
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

,demographic,coef,pval,ci_low,ci_high,pval_fdr,significant
demo_shounen,demo_shounen,0.595012,7.713787e-66,0.527888,0.662137,3.856893e-65,True
demo_shoujo,demo_shoujo,0.546860,6.470136e-18,0.422986,0.670735,9.991209e-18,True
demo_seinen,demo_seinen,0.375972,7.992967e-18,0.290566,0.461379,9.991209e-18,True
demo_josei,demo_josei,0.295301,4.604355e-03,0.091077,0.499526,4.604355e-03,True
demo_kids,demo_kids,-0.829920,2.317259e-65,-0.923906,-0.735934,5.793148e-65,True

## Genre, Theme, Demographic vs. Drop Rate Z-score (Multiple Regression)

In [5]:
genre_cols = [c for c in df.columns if c.startswith('genre_')]

# drop genres that are too rare to estimate reliably (mirrors your bucket_rare logic)
min_count = 50
valid_genres = [c for c in genre_cols if df[c].sum() >= min_count]
dropped = set(genre_cols) - set(valid_genres)
if dropped:
    print(f"Dropping {len(dropped)} rare genres from regression: {sorted(dropped)}")

X = df[valid_genres].copy()
X = sm.add_constant(X)  # intercept = baseline z-score for "no genres present" (rarely meaningful alone, but needed for coefficients to be interpretable as offsets)
y = df['drop_rate_z']

model = sm.OLS(y, X, missing='drop').fit()
print(model.summary())

results = pd.DataFrame({
    'genre': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("genre != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
results

                            OLS Regression Results
==============================================================================
Dep. Variable:            drop_rate_z   R-squared:                       0.138
Model:                            OLS   Adj. R-squared:                  0.135
Method:                 Least Squares   F-statistic:                     49.92
Date:                Wed, 19 Aug 2026   Prob (F-statistic):          1.27e-156
Time:                        23:42:06   Log-Likelihood:                -7053.3
No. Observations:                5338   AIC:                         1.414e+04
Df Residuals:                    5320   BIC:                         1.426e+04
Df Model:                          17
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
const                  -0.3898      0.031    -12.698      0.000      -0.450      -0.330
genre_action            0.3693      0.031     12.004      0.000       0.309       0.430
genre_adventure         0.0872      0.033      2.670      0.008       0.023       0.151
genre_award_winning     0.8986      0.121      7.457      0.000       0.662       1.135
genre_comedy           -0.0089      0.030     -0.302      0.763      -0.067       0.049
genre_drama             0.1576      0.036      4.411      0.000       0.088       0.228
genre_ecchi             0.1971      0.054      3.685      0.000       0.092       0.302
genre_fantasy           0.2671      0.033      8.120      0.000       0.203       0.332
genre_gourmet           0.0860      0.104      0.823      0.410      -0.119       0.291
genre_horror            0.0385      0.080      0.481      0.630      -0.118       0.196
genre_mystery           0.1580      0.052      3.039      0.002       0.056       0.260
genre_other             0.1699      0.083      2.046      0.041       0.007       0.333
genre_romance           0.5152      0.035     14.834      0.000       0.447       0.583
genre_sci-fi           -0.0107      0.034     -0.313      0.754      -0.077       0.056
genre_slice_of_life    -0.0803      0.059     -1.363      0.173      -0.196       0.035
genre_sports            0.1317      0.060      2.206      0.027       0.015       0.249
genre_supernatural      0.1945      0.046      4.242      0.000       0.105       0.284
genre_suspense          0.7945      0.073     10.863      0.000       0.651       0.938
==============================================================================
Omnibus:                     2433.755   Durbin-Watson:                   1.860
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            14395.008
Skew:                           2.126   Prob(JB):                         0.00
Kurtosis:                       9.829   Cond. No.                         12.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

,genre,coef,pval,ci_low,ci_high,pval_fdr,significant
genre_award_winning,genre_award_winning,0.898640,1.029208e-13,0.662387,1.134894,3.499309e-13,True
genre_suspense,genre_suspense,0.794491,3.331335e-27,0.651112,0.937869,1.887757e-26,True
genre_romance,genre_romance,0.515249,8.290990e-49,0.447154,0.583344,1.409468e-47,True
genre_action,genre_action,0.369267,8.926917e-33,0.308961,0.429572,7.587879e-32,True
genre_fantasy,genre_fantasy,0.267097,5.761749e-16,0.202609,0.331585,2.448743e-15,True
genre_ecchi,genre_ecchi,0.197149,2.309761e-04,0.092266,0.302032,4.908243e-04,True
genre_supernatural,genre_supernatural,0.194470,2.250886e-05,0.104602,0.284339,5.466437e-05,True
genre_other,genre_other,0.169858,4.078479e-02,0.007122,0.332594,5.777846e-02,False
genre_mystery,genre_mystery,0.158015,2.381585e-03,0.056097,0.259932,4.498549e-03,True
genre_drama,genre_drama,0.157610,1.047232e-05,0.087569,0.227651,2.967159e-05,True
genre_sports,genre_sports,0.131745,2.745796e-02,0.014643,0.248847,4.243504e-02,True
genre_adventure,genre_adventure,0.087210,7.603117e-03,0.023183,0.151238,1.292530e-02,True
genre_gourmet,genre_gourmet,0.085969,4.104473e-01,-0.118769,0.290708,4.984004e-01,False
genre_horror,genre_horror,0.038540,6.304416e-01,-0.118494,0.195573,7.145005e-01,False
genre_comedy,genre_comedy,-0.008949,7.627369e-01,-0.067060,0.049162,7.627369e-01,False
genre_sci-fi,genre_sci-fi,-0.010668,7.542945e-01,-0.077483,0.056148,7.627369e-01,False
genre_slice_of_life,genre_slice_of_life,-0.080282,1.729776e-01,-0.195761,0.035198,2.262015e-01,False

In [145]:
theme_cols = [c for c in df.columns if c.startswith('theme_')]

# drop genres that are too rare to estimate reliably (mirrors your bucket_rare logic)
min_count = 50
valid_themes = [c for c in theme_cols if df[c].sum() >= min_count]
dropped = set(theme_cols) - set(valid_themes)
if dropped:
    print(f"Dropping {len(dropped)} rare themes from regression: {sorted(dropped)}")

X = df[valid_themes].copy()
X = sm.add_constant(X)  # intercept = baseline z-score for "no genres present" (rarely meaningful alone, but needed for coefficients to be interpretable as offsets)
y = df['drop_rate_z']

model = sm.OLS(y, X, missing='drop').fit()
print(model.summary())

results = pd.DataFrame({
    'theme': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("theme != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
results

                            OLS Regression Results
==============================================================================
Dep. Variable:            drop_rate_z   R-squared:                       0.117
Model:                            OLS   Adj. R-squared:                  0.110
Method:                 Least Squares   F-statistic:                     18.91
Date:                Sun, 16 Aug 2026   Prob (F-statistic):          5.94e-115
Time:                        18:17:50   Log-Likelihood:                -7117.5
No. Observations:                5338   AIC:                         1.431e+04
Df Residuals:                    5300   BIC:                         1.456e+04
Df Model:                          37
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                    -0.1175      0.021     -5.643      0.000      -0.158      -0.077
theme_adult_cast          0.2469      0.057      4.333      0.000       0.135       0.359
theme_anthropomorphic    -0.1684      0.076     -2.203      0.028      -0.318      -0.019
theme_cgdct              -0.2067      0.087     -2.386      0.017      -0.376      -0.037
theme_detective          -0.1739      0.108     -1.616      0.106      -0.385       0.037
theme_gag_humor           0.1315      0.082      1.602      0.109      -0.029       0.292
theme_gore                0.7319      0.095      7.736      0.000       0.546       0.917
theme_harem               0.2467      0.060      4.130      0.000       0.130       0.364
theme_historical         -0.0882      0.056     -1.582      0.114      -0.198       0.021
theme_idols_(female)     -0.1924      0.116     -1.654      0.098      -0.420       0.036
theme_isekai              0.4083      0.065      6.287      0.000       0.281       0.536
theme_iyashikei          -0.1376      0.105     -1.312      0.190      -0.343       0.068
theme_love_polygon        0.7521      0.111      6.767      0.000       0.534       0.970
theme_mahou_shoujo       -0.1961      0.078     -2.511      0.012      -0.349      -0.043
theme_martial_arts        0.2017      0.092      2.194      0.028       0.021       0.382
theme_mecha              -0.1125      0.051     -2.205      0.027      -0.213      -0.012
theme_military            0.1691      0.067      2.526      0.012       0.038       0.300
theme_music              -0.3128      0.077     -4.062      0.000      -0.464      -0.162
theme_mythology           0.0832      0.070      1.185      0.236      -0.054       0.221
theme_organized_crime     0.3786      0.131      2.889      0.004       0.122       0.635
theme_otaku_culture       0.2879      0.118      2.437      0.015       0.056       0.520
theme_other               0.1363      0.045      3.004      0.003       0.047       0.225
theme_parody             -0.1281      0.068     -1.875      0.061      -0.262       0.006
theme_performing_arts    -0.1324      0.121     -1.093      0.274      -0.370       0.105
theme_pets               -0.3974      0.125     -3.191      0.001      -0.642      -0.153
theme_psychological       0.6951      0.077      9.035      0.000       0.544       0.846
theme_racing             -0.2957      0.109     -2.716      0.007      -0.509      -0.082
theme_reincarnation       0.0837      0.098      0.851      0.395      -0.109       0.277
theme_samurai            -0.0686      0.107     -0.643      0.521      -0.278       0.141
theme_school              0.2426      0.035      6.989      0.000       0.175       0.311
theme_space               0.0474      0.079      0.598      0.550      -0.108       0.203
theme_strategy_game      -0.3597      0.073     -4.908      0.000      -0.503      -0.216
theme_super_power         0.1329      0.062      2.135      0.033       0.011       0.255
theme_team_sports        -0.1351      0.087     -1.561      0.119      -0.305       0.035
theme_time_travel         0.1002      0.115      0.870      0.384      -0.126       0.326
theme_urban_fantasy       0.5455      0.087      6.247      0.000       0.374       0.717
theme_vampire             0.3073      0.108      2.849      0.004       0.096       0.519
theme_workplace          -0.2254      0.089     -2.520      0.012      -0.401      -0.050
==============================================================================
Omnibus:                     2556.184   Durbin-Watson:                   1.834
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            16556.230
Skew:                           2.220   Prob(JB):                         0.00
Kurtosis:                      10.398   Cond. No.                         11.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

,theme,coef,pval,ci_low,ci_high,pval_fdr,significant
theme_love_polygon,theme_love_polygon,0.752053,1.460973e-11,0.534169,0.969937,1.351400e-10,True
theme_gore,theme_gore,0.731905,1.221402e-14,0.546426,0.917384,2.259594e-13,True
theme_psychological,theme_psychological,0.695075,2.261642e-19,0.544253,0.845897,8.368076e-18,True
theme_urban_fantasy,theme_urban_fantasy,0.545522,4.498546e-10,0.374339,0.716704,2.774103e-09,True
theme_isekai,theme_isekai,0.408287,3.497399e-10,0.280973,0.535600,2.588075e-09,True
theme_organized_crime,theme_organized_crime,0.378561,3.883875e-03,0.121653,0.635470,1.105411e-02,True
theme_vampire,theme_vampire,0.307282,4.401179e-03,0.095847,0.518716,1.163169e-02,True
theme_otaku_culture,theme_otaku_culture,0.287915,1.484546e-02,0.056299,0.519532,2.890959e-02,True
theme_adult_cast,theme_adult_cast,0.246907,1.495759e-05,0.135206,0.358607,6.917887e-05,True
theme_harem,theme_harem,0.246673,3.677981e-05,0.129593,0.363753,1.512059e-04,True
theme_school,theme_school,0.242560,3.100281e-12,0.174527,0.310594,3.823680e-11,True
theme_martial_arts,theme_martial_arts,0.201728,2.830148e-02,0.021451,0.382004,4.552846e-02,True
theme_military,theme_military,0.169080,1.157644e-02,0.037841,0.300318,2.479784e-02,True
theme_other,theme_other,0.136281,2.675694e-03,0.047348,0.225213,8.250058e-03,True
theme_super_power,theme_super_power,0.132892,3.277526e-02,0.010889,0.254895,5.052852e-02,False
theme_gag_humor,theme_gag_humor,0.131498,1.092169e-01,-0.029421,0.292418,1.443223e-01,False
theme_time_travel,theme_time_travel,0.100153,3.843606e-01,-0.125536,0.325841,4.173824e-01,False
theme_reincarnation,theme_reincarnation,0.083711,3.948212e-01,-0.109136,0.276557,4.173824e-01,False
theme_mythology,theme_mythology,0.083216,2.358936e-01,-0.054401,0.220833,2.727519e-01,False
theme_space,theme_space,0.047381,5.498326e-01,-0.107935,0.202697,5.498326e-01,False
theme_samurai,theme_samurai,-0.068585,5.205191e-01,-0.277824,0.140654,5.349780e-01,False
theme_historical,theme_historical,-0.088240,1.136142e-01,-0.197558,0.021078,1.449561e-01,False
theme_mecha,theme_mecha,-0.112509,2.747714e-02,-0.212525,-0.012493,4.552846e-02,True
theme_parody,theme_parody,-0.128056,6.083908e-02,-0.261940,0.005829,9.004184e-02,False
theme_performing_arts,theme_performing_arts,-0.132433,2.743648e-01,-0.369927,0.105061,3.076211e-01,False
theme_team_sports,theme_team_sports,-0.135092,1.186003e-01,-0.304757,0.034574,1.462737e-01,False
theme_iyashikei,theme_iyashikei,-0.137585,1.896855e-01,-0.343218,0.068047,2.263988e-01,False
theme_anthropomorphic,theme_anthropomorphic,-0.168442,2.763309e-02,-0.318331,-0.018553,4.552846e-02,True
theme_detective,theme_detective,-0.173929,1.060726e-01,-0.384879,0.037020,1.443223e-01,False
theme_idols_(female),theme_idols_(female),-0.192367,9.810785e-02,-0.420318,0.035583,1.396150e-01,False
theme_mahou_shoujo,theme_mahou_shoujo,-0.196104,1.206381e-02,-0.349200,-0.043008,2.479784e-02,True
theme_cgdct,theme_cgdct,-0.206678,1.706553e-02,-0.376488,-0.036868,3.157123e-02,True
theme_workplace,theme_workplace,-0.225380,1.177932e-02,-0.400743,-0.050017,2.479784e-02,True
theme_racing,theme_racing,-0.295676,6.622197e-03,-0.509068,-0.082283,1.633475e-02,True
theme_music,theme_music,-0.312831,4.931754e-05,-0.463804,-0.161859,1.824749e-04,True
theme_strategy_game,theme_strategy_game,-0.359704,9.493769e-07,-0.503392,-0.216017,5.018135e-06,True
theme_pets,theme_pets,-0.397386,1.425693e-03,-0.641517,-0.153256,4.795513e-03,True

In [146]:
demo_cols = [c for c in df.columns if c.startswith('demo_')]

# drop genres that are too rare to estimate reliably (mirrors your bucket_rare logic)
min_count = 50
valid_demos = [c for c in demo_cols if df[c].sum() >= min_count]
dropped = set(demo_cols) - set(valid_demos)
if dropped:
    print(f"Dropping {len(dropped)} rare demographics from regression: {sorted(dropped)}")

X = df[valid_demos].copy()
X = sm.add_constant(X)  # intercept = baseline z-score for "no genres present" (rarely meaningful alone, but needed for coefficients to be interpretable as offsets)
y = df['drop_rate_z']

model = sm.OLS(y, X, missing='drop').fit()
print(model.summary())

results = pd.DataFrame({
    'demographic': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("demographic != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
results

                            OLS Regression Results
==============================================================================
Dep. Variable:            drop_rate_z   R-squared:                       0.056
Model:                            OLS   Adj. R-squared:                  0.055
Method:                 Least Squares   F-statistic:                     63.35
Date:                Sun, 16 Aug 2026   Prob (F-statistic):           2.13e-64
Time:                        18:17:50   Log-Likelihood:                -7294.4
No. Observations:                5338   AIC:                         1.460e+04
Df Residuals:                    5332   BIC:                         1.464e+04
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -0.0767      0.017     -4.605      0.000      -0.109      -0.044
demo_josei      -0.1105      0.109     -1.016      0.310      -0.324       0.103
demo_kids       -0.4455      0.050     -8.898      0.000      -0.544      -0.347
demo_seinen      0.2229      0.045      4.899      0.000       0.134       0.312
demo_shoujo      0.3372      0.066      5.111      0.000       0.208       0.467
demo_shounen     0.4578      0.036     12.805      0.000       0.388       0.528
==============================================================================
Omnibus:                     2381.369   Durbin-Watson:                   1.827
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            12748.080
Skew:                           2.114   Prob(JB):                         0.00
Kurtosis:                       9.281   Cond. No.                         8.59
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

,demographic,coef,pval,ci_low,ci_high,pval_fdr,significant
demo_shounen,demo_shounen,0.457845,5.389373e-37,0.387748,0.527941,2.694687e-36,True
demo_shoujo,demo_shoujo,0.337238,3.320474e-07,0.207879,0.466597,5.534124e-07,True
demo_seinen,demo_seinen,0.222881,9.914440e-07,0.133693,0.312069,1.239305e-06,True
demo_josei,demo_josei,-0.110539,3.096266e-01,-0.323805,0.102728,3.096266e-01,False
demo_kids,demo_kids,-0.445490,7.643060e-19,-0.543638,-0.347343,1.910765e-18,True

## Genre, Theme, Demographic vs. Forum Z-score (Multiple Regression)

In [147]:
genre_cols = [c for c in df.columns if c.startswith('genre_')]

# drop genres that are too rare to estimate reliably (mirrors your bucket_rare logic)
min_count = 50
valid_genres = [c for c in genre_cols if df[c].sum() >= min_count]
dropped = set(genre_cols) - set(valid_genres)
if dropped:
    print(f"Dropping {len(dropped)} rare genres from regression: {sorted(dropped)}")

X = df[valid_genres].copy()
X = sm.add_constant(X)  # intercept = baseline z-score for "no genres present" (rarely meaningful alone, but needed for coefficients to be interpretable as offsets)
y = df['forum_z']

model = sm.OLS(y, X, missing='drop').fit()
print(model.summary())

results = pd.DataFrame({
    'genre': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("genre != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
results

                            OLS Regression Results
==============================================================================
Dep. Variable:                forum_z   R-squared:                       0.183
Model:                            OLS   Adj. R-squared:                  0.180
Method:                 Least Squares   F-statistic:                     70.10
Date:                Sun, 16 Aug 2026   Prob (F-statistic):          3.39e-218
Time:                        18:17:50   Log-Likelihood:                -6896.3
No. Observations:                5338   AIC:                         1.383e+04
Df Residuals:                    5320   BIC:                         1.395e+04
Df Model:                          17
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
const                  -0.4767      0.030    -15.992      0.000      -0.535      -0.418
genre_action            0.3634      0.030     12.167      0.000       0.305       0.422
genre_adventure         0.0164      0.032      0.516      0.606      -0.046       0.079
genre_award_winning     0.7734      0.117      6.609      0.000       0.544       1.003
genre_comedy           -0.0823      0.029     -2.860      0.004      -0.139      -0.026
genre_drama             0.4256      0.035     12.268      0.000       0.358       0.494
genre_ecchi             0.3379      0.052      6.505      0.000       0.236       0.440
genre_fantasy           0.2026      0.032      6.343      0.000       0.140       0.265
genre_gourmet           0.2660      0.101      2.623      0.009       0.067       0.465
genre_horror            0.0757      0.078      0.974      0.330      -0.077       0.228
genre_mystery           0.3009      0.050      5.960      0.000       0.202       0.400
genre_other             0.3497      0.081      4.339      0.000       0.192       0.508
genre_romance           0.6094      0.034     18.067      0.000       0.543       0.675
genre_sci-fi            0.1850      0.033      5.590      0.000       0.120       0.250
genre_slice_of_life     0.1877      0.057      3.281      0.001       0.076       0.300
genre_sports            0.2990      0.058      5.155      0.000       0.185       0.413
genre_supernatural      0.2774      0.045      6.233      0.000       0.190       0.365
genre_suspense          0.5877      0.071      8.276      0.000       0.449       0.727
==============================================================================
Omnibus:                      622.413   Durbin-Watson:                   1.818
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              934.225
Skew:                          -0.857   Prob(JB):                    1.37e-203
Kurtosis:                       4.123   Cond. No.                         12.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

,genre,coef,pval,ci_low,ci_high,pval_fdr,significant
genre_award_winning,genre_award_winning,0.773388,4.245692e-11,0.543982,1.002794,1.443535e-10,True
genre_romance,genre_romance,0.609363,7.360397e-71,0.543242,0.675485,1.251267e-69,True
genre_suspense,genre_suspense,0.587731,1.596453e-16,0.448508,0.726954,6.784924e-16,True
genre_drama,genre_drama,0.425586,3.899955e-34,0.357576,0.493597,3.314962e-33,True
genre_action,genre_action,0.363420,1.301608e-33,0.304863,0.421977,7.375778e-33,True
genre_other,genre_other,0.349749,1.457483e-05,0.191731,0.507768,2.064768e-05,True
genre_ecchi,genre_ecchi,0.337922,8.491679e-11,0.236080,0.439765,2.405976e-10,True
genre_mystery,genre_mystery,0.300870,2.683566e-09,0.201906,0.399833,5.068958e-09,True
genre_sports,genre_sports,0.299017,2.623859e-07,0.185310,0.412725,4.055054e-07,True
genre_supernatural,genre_supernatural,0.277430,4.941934e-10,0.190166,0.364694,1.050161e-09,True
genre_gourmet,genre_gourmet,0.265970,8.747791e-03,0.067165,0.464774,9.914163e-03,True
genre_fantasy,genre_fantasy,0.202603,2.441240e-10,0.139984,0.265222,5.928727e-10,True
genre_slice_of_life,genre_slice_of_life,0.187665,1.041257e-03,0.075533,0.299798,1.361644e-03,True
genre_sci-fi,genre_sci-fi,0.184989,2.387996e-08,0.120110,0.249868,4.059593e-08,True
genre_horror,genre_horror,0.075742,3.302032e-01,-0.076740,0.228224,3.508409e-01,False
genre_adventure,genre_adventure,0.016366,6.058386e-01,-0.045806,0.078538,6.058386e-01,False
genre_comedy,genre_comedy,-0.082306,4.258978e-03,-0.138733,-0.025880,5.171617e-03,True

In [148]:
theme_cols = [c for c in df.columns if c.startswith('theme_')]

# drop genres that are too rare to estimate reliably (mirrors your bucket_rare logic)
min_count = 50
valid_themes = [c for c in theme_cols if df[c].sum() >= min_count]
dropped = set(theme_cols) - set(valid_themes)
if dropped:
    print(f"Dropping {len(dropped)} rare themes from regression: {sorted(dropped)}")

X = df[valid_themes].copy()
X = sm.add_constant(X)  # intercept = baseline z-score for "no genres present" (rarely meaningful alone, but needed for coefficients to be interpretable as offsets)
y = df['forum_z']

model = sm.OLS(y, X, missing='drop').fit()
print(model.summary())

results = pd.DataFrame({
    'theme': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("theme != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
results

                            OLS Regression Results
==============================================================================
Dep. Variable:                forum_z   R-squared:                       0.181
Model:                            OLS   Adj. R-squared:                  0.175
Method:                 Least Squares   F-statistic:                     31.56
Date:                Sun, 16 Aug 2026   Prob (F-statistic):          4.20e-198
Time:                        18:17:50   Log-Likelihood:                -6904.4
No. Observations:                5338   AIC:                         1.388e+04
Df Residuals:                    5300   BIC:                         1.413e+04
Df Model:                          37
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                    -0.2742      0.020    -13.709      0.000      -0.313      -0.235
theme_adult_cast          0.4797      0.055      8.762      0.000       0.372       0.587
theme_anthropomorphic    -0.2656      0.073     -3.616      0.000      -0.410      -0.122
theme_cgdct               0.2678      0.083      3.218      0.001       0.105       0.431
theme_detective           0.0645      0.103      0.624      0.533      -0.138       0.267
theme_gag_humor           0.1365      0.079      1.731      0.083      -0.018       0.291
theme_gore                0.5799      0.091      6.379      0.000       0.402       0.758
theme_harem               0.3595      0.057      6.265      0.000       0.247       0.472
theme_historical          0.1638      0.054      3.056      0.002       0.059       0.269
theme_idols_(female)     -0.0269      0.112     -0.241      0.810      -0.246       0.192
theme_isekai              0.5077      0.062      8.136      0.000       0.385       0.630
theme_iyashikei           0.3329      0.101      3.303      0.001       0.135       0.530
theme_love_polygon        0.6672      0.107      6.248      0.000       0.458       0.877
theme_mahou_shoujo        0.0894      0.075      1.191      0.234      -0.058       0.237
theme_martial_arts        0.1880      0.088      2.128      0.033       0.015       0.361
theme_mecha               0.0198      0.049      0.403      0.687      -0.076       0.116
theme_military            0.4408      0.064      6.853      0.000       0.315       0.567
theme_music              -0.1134      0.074     -1.533      0.125      -0.258       0.032
theme_mythology           0.2060      0.067      3.054      0.002       0.074       0.338
theme_organized_crime     0.3759      0.126      2.985      0.003       0.129       0.623
theme_otaku_culture       0.4474      0.114      3.942      0.000       0.225       0.670
theme_other               0.2532      0.044      5.808      0.000       0.168       0.339
theme_parody             -0.2633      0.066     -4.012      0.000      -0.392      -0.135
theme_performing_arts     0.2293      0.116      1.970      0.049       0.001       0.457
theme_pets               -0.6060      0.120     -5.065      0.000      -0.841      -0.371
theme_psychological       0.7127      0.074      9.641      0.000       0.568       0.858
theme_racing             -0.3275      0.105     -3.132      0.002      -0.533      -0.122
theme_reincarnation       0.1597      0.095      1.690      0.091      -0.026       0.345
theme_samurai            -0.0102      0.103     -0.099      0.921      -0.211       0.191
theme_school              0.4073      0.033     12.216      0.000       0.342       0.473
theme_space               0.4372      0.076      5.743      0.000       0.288       0.586
theme_strategy_game      -0.6585      0.070     -9.351      0.000      -0.797      -0.520
theme_super_power         0.1707      0.060      2.855      0.004       0.053       0.288
theme_team_sports         0.0413      0.083      0.496      0.620      -0.122       0.204
theme_time_travel         0.2226      0.111      2.012      0.044       0.006       0.439
theme_urban_fantasy       0.4608      0.084      5.493      0.000       0.296       0.625
theme_vampire             0.2864      0.104      2.763      0.006       0.083       0.490
theme_workplace          -0.1190      0.086     -1.384      0.166      -0.287       0.050
==============================================================================
Omnibus:                      558.933   Durbin-Watson:                   1.799
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              817.552
Skew:                          -0.797   Prob(JB):                    2.96e-178
Kurtosis:                       4.066   Cond. No.                         11.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

,theme,coef,pval,ci_low,ci_high,pval_fdr,significant
theme_psychological,theme_psychological,0.712701,8.084602e-22,0.567782,0.857620,1.495651e-20,True
theme_love_polygon,theme_love_polygon,0.667234,4.482394e-10,0.457878,0.876591,1.842762e-09,True
theme_gore,theme_gore,0.579947,1.928516e-10,0.401728,0.758166,1.019358e-09,True
theme_isekai,theme_isekai,0.507709,5.032901e-16,0.385379,0.630040,3.724346e-15,True
theme_adult_cast,theme_adult_cast,0.479709,2.541715e-18,0.372381,0.587038,2.351086e-17,True
theme_urban_fantasy,theme_urban_fantasy,0.460831,4.147472e-08,0.296349,0.625313,1.278804e-07,True
theme_otaku_culture,theme_otaku_culture,0.447450,8.201623e-05,0.224898,0.670001,2.023067e-04,True
theme_military,theme_military,0.440807,8.060929e-12,0.314705,0.566908,4.970906e-11,True
theme_space,theme_space,0.437198,9.811089e-09,0.287961,0.586435,3.300094e-08,True
theme_school,theme_school,0.407344,7.270394e-34,0.341973,0.472714,2.690046e-32,True
theme_organized_crime,theme_organized_crime,0.375921,2.844849e-03,0.129068,0.622775,4.784519e-03,True
theme_harem,theme_harem,0.359491,4.033192e-10,0.246993,0.471988,1.842762e-09,True
theme_iyashikei,theme_iyashikei,0.332906,9.626941e-04,0.135322,0.530490,2.095275e-03,True
theme_vampire,theme_vampire,0.286352,5.743611e-03,0.083193,0.489511,8.854733e-03,True
theme_cgdct,theme_cgdct,0.267833,1.298613e-03,0.104669,0.430996,2.669371e-03,True
theme_other,theme_other,0.253167,6.686404e-09,0.167716,0.338619,2.473970e-08,True
theme_performing_arts,theme_performing_arts,0.229268,4.893671e-02,0.001069,0.457466,6.706142e-02,False
theme_time_travel,theme_time_travel,0.222585,4.424812e-02,0.005730,0.439440,6.296848e-02,False
theme_mythology,theme_mythology,0.205993,2.269368e-03,0.073763,0.338224,3.998411e-03,True
theme_martial_arts,theme_martial_arts,0.188020,3.339059e-02,0.014800,0.361241,4.941807e-02,True
theme_super_power,theme_super_power,0.170702,4.324812e-03,0.053475,0.287930,6.957306e-03,True
theme_historical,theme_historical,0.163760,2.251735e-03,0.058720,0.268799,3.998411e-03,True
theme_reincarnation,theme_reincarnation,0.159736,9.109211e-02,-0.025562,0.345035,1.162210e-01,False
theme_gag_humor,theme_gag_humor,0.136550,8.345722e-02,-0.018071,0.291171,1.102828e-01,False
theme_mahou_shoujo,theme_mahou_shoujo,0.089397,2.335591e-01,-0.057706,0.236501,2.700527e-01,False
theme_detective,theme_detective,0.064497,5.327842e-01,-0.138196,0.267189,5.973641e-01,False
theme_team_sports,theme_team_sports,0.041279,6.196381e-01,-0.121746,0.204304,6.743121e-01,False
theme_mecha,theme_mecha,0.019756,6.869577e-01,-0.076345,0.115857,7.262124e-01,False
theme_samurai,theme_samurai,-0.010162,9.210733e-01,-0.211211,0.190887,9.210733e-01,False
theme_idols_(female),theme_idols_(female),-0.026930,8.095358e-01,-0.245959,0.192099,8.320229e-01,False
theme_music,theme_music,-0.113411,1.254206e-01,-0.258474,0.031652,1.546854e-01,False
theme_workplace,theme_workplace,-0.118992,1.662896e-01,-0.287491,0.049507,1.984746e-01,False
theme_parody,theme_parody,-0.263272,6.103423e-05,-0.391917,-0.134628,1.613048e-04,True
theme_anthropomorphic,theme_anthropomorphic,-0.265634,3.022447e-04,-0.409657,-0.121611,6.989409e-04,True
theme_racing,theme_racing,-0.327536,1.747981e-03,-0.532576,-0.122496,3.403963e-03,True
theme_pets,theme_pets,-0.606020,4.229471e-07,-0.840596,-0.371445,1.203772e-06,True
theme_strategy_game,theme_strategy_game,-0.658536,1.253368e-20,-0.796600,-0.520472,1.545820e-19,True

In [149]:
demo_cols = [c for c in df.columns if c.startswith('demo_')]

# drop genres that are too rare to estimate reliably (mirrors your bucket_rare logic)
min_count = 50
valid_demos = [c for c in demo_cols if df[c].sum() >= min_count]
dropped = set(demo_cols) - set(valid_demos)
if dropped:
    print(f"Dropping {len(dropped)} rare demographics from regression: {sorted(dropped)}")

X = df[valid_demos].copy()
X = sm.add_constant(X)  # intercept = baseline z-score for "no genres present" (rarely meaningful alone, but needed for coefficients to be interpretable as offsets)
y = df['forum_z']

model = sm.OLS(y, X, missing='drop').fit()
print(model.summary())

results = pd.DataFrame({
    'demographic': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("demographic != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
results

                            OLS Regression Results
==============================================================================
Dep. Variable:                forum_z   R-squared:                       0.149
Model:                            OLS   Adj. R-squared:                  0.148
Method:                 Least Squares   F-statistic:                     186.3
Date:                Sun, 16 Aug 2026   Prob (F-statistic):          2.41e-183
Time:                        18:17:50   Log-Likelihood:                -7006.1
No. Observations:                5338   AIC:                         1.402e+04
Df Residuals:                    5332   BIC:                         1.406e+04
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -0.0440      0.016     -2.788      0.005      -0.075      -0.013
demo_josei       0.2220      0.103      2.153      0.031       0.020       0.424
demo_kids       -1.1056      0.047    -23.309      0.000      -1.199      -1.013
demo_seinen      0.4018      0.043      9.321      0.000       0.317       0.486
demo_shoujo      0.3317      0.063      5.306      0.000       0.209       0.454
demo_shounen     0.4318      0.034     12.747      0.000       0.365       0.498
==============================================================================
Omnibus:                      801.106   Durbin-Watson:                   1.793
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1352.757
Skew:                          -0.995   Prob(JB):                    1.79e-294
Kurtosis:                       4.456   Cond. No.                         8.59
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

,demographic,coef,pval,ci_low,ci_high,pval_fdr,significant
demo_shounen,demo_shounen,0.431832,1.102362e-36,0.365421,0.498244,2.755906e-36,True
demo_seinen,demo_seinen,0.401770,1.646340e-20,0.317271,0.486270,2.743900e-20,True
demo_shoujo,demo_shoujo,0.331712,1.166214e-07,0.209153,0.454270,1.457767e-07,True
demo_josei,demo_josei,0.221953,3.132678e-02,0.019898,0.424008,3.132678e-02,True
demo_kids,demo_kids,-1.105615,1.611544e-114,-1.198603,-1.012627,8.057721e-114,True

## Rating, Sequel vs. Score Z-score (ANOVA + Tukey, T-test)

In [150]:
# one-way ANOVA
groups = [df.loc[df['rating'] == r, 'score_z'].dropna() for r in df['rating'].unique()]
f_stat, p_val = stats.f_oneway(*groups)
print(f"F={f_stat:.3f}, p={p_val:.4f}")

# Tukey post-hoc
tukey = pairwise_tukeyhsd(endog=df['score_z'], groups=df['rating'], alpha=0.05)
print(tukey)

F=112.488, p=0.0000
                        Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================================================================
            group1                         group2             meandiff p-adj   lower   upper  reject
----------------------------------------------------------------------------------------------------
                  G - All Ages                  PG - Children  -0.1086 0.3128 -0.2639  0.0467  False
                  G - All Ages      PG-13 - Teens 13 or older   0.4476    0.0  0.3447  0.5504   True
                  G - All Ages R - 17+ (violence & profanity)   0.8563    0.0  0.7184  0.9942   True
                  G - All Ages               R+ - Mild Nudity    0.065 0.8509 -0.1106  0.2406  False
                 PG - Children      PG-13 - Teens 13 or older   0.5562    0.0  0.4235  0.6889   True
                 PG - Children R - 17+ (violence & profanity)   0.9649    0.0  0.8035  1.1263   True
                 PG - Children               R+ - Mild Nudity   0.1736 0.1063  -0.021  0.3682  False
     PG-13 - Teens 13 or older R - 17+ (violence & profanity)   0.4087    0.0  0.2969  0.5205   True
     PG-13 - Teens 13 or older               R+ - Mild Nudity  -0.3826    0.0 -0.5385 -0.2266   True
R - 17+ (violence & profanity)               R+ - Mild Nudity  -0.7913    0.0 -0.9723 -0.6103   True
----------------------------------------------------------------------------------------------------

In [151]:
seq_yes = df.loc[df['sequel'] == 1, 'score_z'].dropna()
seq_no  = df.loc[df['sequel'] == 0, 'score_z'].dropna()

t_stat, p_val = stats.ttest_ind(seq_yes, seq_no, equal_var=False)  # Welch's, safer default
print(f"t={t_stat:.3f}, p={p_val:.4f}, mean_diff={seq_yes.mean() - seq_no.mean():.3f}")

t=11.515, p=0.0000, mean_diff=0.361

We want to also find the partial effects of ratings and sequels taking into account genres, themes, and demographics since they are likely related (e.g. demographics and age ratings definitely correlate). By "partial effects," I mean that if we keep everything else constant, what effect does it have on the score z-score?

In [152]:
rating_dummies = pd.get_dummies(df['rating'], prefix='rating', drop_first=True)
X = pd.concat([df[valid_genres], df[valid_themes], df[valid_demos], rating_dummies, df[['sequel']]], axis=1)
X = X.astype(float)
X = sm.add_constant(X)

model = sm.OLS(df['score_z'], X, missing='drop').fit(cov_type='HC3')
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                score_z   R-squared:                       0.312
Model:                            OLS   Adj. R-squared:                  0.304
Method:                 Least Squares   F-statistic:                     42.76
Date:                Sun, 16 Aug 2026   Prob (F-statistic):               0.00
Time:                        18:17:51   Log-Likelihood:                -6449.2
No. Observations:                5338   AIC:                         1.303e+04
Df Residuals:                    5273   BIC:                         1.346e+04
Df Model:                          64
Covariance Type:                  HC3
=========================================================================================================
                                            coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
const                                    -0.7802      0.045    -17.328      0.000      -0.868      -0.692
genre_action                              0.0901      0.033      2.746      0.006       0.026       0.154
genre_adventure                           0.2535      0.031      8.241      0.000       0.193       0.314
genre_award_winning                       1.0748      0.083     12.919      0.000       0.912       1.238
genre_comedy                              0.0325      0.029      1.115      0.265      -0.025       0.090
genre_drama                               0.3904      0.035     11.190      0.000       0.322       0.459
genre_ecchi                              -0.2417      0.054     -4.471      0.000      -0.348      -0.136
genre_fantasy                             0.0596      0.034      1.752      0.080      -0.007       0.126
genre_gourmet                             0.1207      0.099      1.215      0.224      -0.074       0.315
genre_horror                             -0.3753      0.087     -4.307      0.000      -0.546      -0.205
genre_mystery                             0.2839      0.058      4.912      0.000       0.171       0.397
genre_other                               0.0335      0.077      0.435      0.663      -0.117       0.184
genre_romance                             0.2023      0.036      5.676      0.000       0.132       0.272
genre_sci-fi                              0.0161      0.038      0.425      0.671      -0.058       0.090
genre_slice_of_life                       0.0955      0.065      1.469      0.142      -0.032       0.223
genre_sports                              0.3040      0.072      4.239      0.000       0.163       0.445
genre_supernatural                        0.1855      0.048      3.887      0.000       0.092       0.279
genre_suspense                            0.1474      0.110      1.343      0.179      -0.068       0.363
theme_adult_cast                          0.3904      0.054      7.200      0.000       0.284       0.497
theme_anthropomorphic                     0.1273      0.066      1.926      0.054      -0.002       0.257
theme_cgdct                               0.3085      0.069      4.449      0.000       0.173       0.444
theme_detective                          -0.2393      0.117     -2.051      0.040      -0.468      -0.011
theme_gag_humor                           0.4854      0.081      5.968      0.000       0.326       0.645
theme_gore                                0.0892      0.107      0.833      0.405      -0.121       0.299
theme_harem                              -0.1886      0.054     -3.514      0.000      -0.294      -0.083
theme_historical                          0.2587      0.054      4.793      0.000       0.153       0.364
theme_idols_(female)                      0.2398      0.099      2.416      0.016       0.045       0.434
theme_isekai                              0.2049      0.063      3.261      0.001       0.082       0.328
theme_iyashikei                           0.7686      0.097      7.948      0.000       0.579       0.958
theme_love_polygon                        0.2939      0.099      2.973      0.003       0.100       0.488
theme_mahou_shoujo                        0.4000      0.076      5.240      0.000       0.250       0.550
theme_martial_arts                       -0.1400      0.092     -1.520      0.129      -0.320       0.041
theme_mecha                               0.1493      0.052      2.851      0.004       0.047       0.252
theme_military                            0.1556      0.064      2.422      0.015       0.030       0.282
theme_music                               0.1612      0.074      2.167      0.030       0.015       0.307
theme_mythology                           0.0759      0.062      1.222      0.222      -0.046       0.198
theme_organized_crime                     0.3462      0.122      2.841      0.005       0.107       0.585
theme_otaku_culture                       0.4237      0.079      5.335      0.000       0.268       0.579
theme_other                               0.1030      0.042      2.434      0.015       0.020       0.186
theme_parody                             -0.1322      0.069     -1.916      0.055      -0.267       0.003
theme_performing_arts                     0.2976      0.110      2.709      0.007       0.082       0.513
theme_pets                                0.2626      0.105      2.499      0.012       0.057       0.469
theme_psychological                       0.0062      0.111      0.056      0.956      -0.211       0.223
theme_racing                              0.1748      0.099      1.767      0.077      -0.019       0.369
theme_reincarnation                       0.0422      0.093      0.456      0.648      -0.139       0.224
theme_samurai                            -0.1369      0.105     -1.308      0.191      -0.342       0.068
theme_school                              0.2757      0.031      8.871      0.000       0.215       0.337
theme_space                               0.2523      0.072      3.502      0.000       0.111       0.393
theme_strategy_game                      -0.1583      0.062     -2.550      0.011      -0.280      -0.037
theme_super_power                         0.0371      0.055      0.674      0.500      -0.071       0.145
theme_team_sports                         0.1089      0.105      1.038      0.299      -0.097       0.315
theme_time_travel                         0.0701      0.107      0.657      0.511      -0.139       0.279
theme_urban_fantasy                       0.3587      0.068      5.294      0.000       0.226       0.491
theme_vampire                            -0.1306      0.108     -1.206      0.228      -0.343       0.082
theme_workplace                           0.0215      0.079      0.273      0.784      -0.133       0.176
demo_josei                                0.0957      0.104      0.922      0.357      -0.108       0.299
demo_kids                                -0.2568      0.050     -5.172      0.000      -0.354      -0.160
demo_seinen                               0.3648      0.043      8.440      0.000       0.280       0.450
demo_shoujo                               0.4187      0.062      6.805      0.000       0.298       0.539
demo_shounen                              0.5984      0.032     18.419      0.000       0.535       0.662
rating_PG - Children                     -0.0866      0.049     -1.773      0.076      -0.182       0.009
rating_PG-13 - Teens 13 or older          0.0893      0.039      2.310      0.021       0.014       0.165
rating_R - 17+ (violence & profanity)     0.3842      0.057      6.768      0.000       0.273       0.496
rating_R+ - Mild Nudity                  -0.1400      0.069     -2.021      0.043      -0.276      -0.004
sequel                                    0.3219      0.026     12.222      0.000       0.270       0.373
==============================================================================
Omnibus:                       68.454   Durbin-Watson:                   1.897
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               73.410
Skew:                          -0.251   Prob(JB):                     1.15e-16
Kurtosis:                       3.278   Cond. No.                         17.2
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [153]:
results = pd.DataFrame({
    'feature': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("feature != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
print(results.loc[results['significant']==True, 'coef'].head(10))
print(results.loc[results['significant']==True, 'coef'].tail(10))

genre_award_winning                      1.074797
theme_iyashikei                          0.768610
demo_shounen                             0.598384
theme_gag_humor                          0.485374
theme_otaku_culture                      0.423685
demo_shoujo                              0.418721
theme_mahou_shoujo                       0.400001
theme_adult_cast                         0.390427
genre_drama                              0.390363
rating_R - 17+ (violence & profanity)    0.384240
Name: coef, dtype: float64
theme_military                      0.155622
theme_mecha                         0.149332
theme_other                         0.102994
genre_action                        0.090077
rating_PG-13 - Teens 13 or older    0.089288
theme_strategy_game                -0.158327
theme_harem                        -0.188629
genre_ecchi                        -0.241679
demo_kids                          -0.256844
genre_horror                       -0.375300
Name: coef, dtype: float64

The above shows the top 10 and bottom 10 coefficients for features that yielded statistically significant results $(p < 0.05)$.

## Other Metrics

For the other metrics, we will go straight to partial effects.

In [154]:
rating_dummies = pd.get_dummies(df['rating'], prefix='rating', drop_first=True)
X = pd.concat([df[valid_genres], df[valid_themes], df[valid_demos], rating_dummies, df[['sequel']]], axis=1)
X = X.astype(float)
X = sm.add_constant(X)

model = sm.OLS(df['wc_z'], X, missing='drop').fit(cov_type='HC3')
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   wc_z   R-squared:                       0.419
Model:                            OLS   Adj. R-squared:                  0.412
Method:                 Least Squares   F-statistic:                     69.32
Date:                Sun, 16 Aug 2026   Prob (F-statistic):               0.00
Time:                        18:17:51   Log-Likelihood:                -5998.0
No. Observations:                5338   AIC:                         1.213e+04
Df Residuals:                    5273   BIC:                         1.255e+04
Df Model:                          64
Covariance Type:                  HC3
=========================================================================================================
                                            coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
const                                    -0.9825      0.045    -22.009      0.000      -1.070      -0.895
genre_action                              0.2693      0.031      8.763      0.000       0.209       0.330
genre_adventure                           0.3003      0.030     10.096      0.000       0.242       0.359
genre_award_winning                       0.7808      0.095      8.198      0.000       0.594       0.967
genre_comedy                              0.0005      0.028      0.017      0.986      -0.054       0.054
genre_drama                               0.2832      0.031      9.008      0.000       0.222       0.345
genre_ecchi                               0.1628      0.050      3.267      0.001       0.065       0.260
genre_fantasy                             0.2213      0.032      6.889      0.000       0.158       0.284
genre_gourmet                             0.0963      0.081      1.186      0.236      -0.063       0.256
genre_horror                             -0.1774      0.076     -2.343      0.019      -0.326      -0.029
genre_mystery                             0.1588      0.050      3.196      0.001       0.061       0.256
genre_other                               0.1468      0.062      2.382      0.017       0.026       0.268
genre_romance                             0.3840      0.034     11.394      0.000       0.318       0.450
genre_sci-fi                              0.0246      0.034      0.726      0.468      -0.042       0.091
genre_slice_of_life                      -0.0417      0.059     -0.703      0.482      -0.158       0.074
genre_sports                              0.1905      0.070      2.732      0.006       0.054       0.327
genre_supernatural                        0.2398      0.043      5.635      0.000       0.156       0.323
genre_suspense                            0.2428      0.089      2.715      0.007       0.068       0.418
theme_adult_cast                          0.2880      0.048      5.987      0.000       0.194       0.382
theme_anthropomorphic                    -0.0060      0.070     -0.087      0.931      -0.143       0.131
theme_cgdct                               0.2400      0.057      4.219      0.000       0.129       0.352
theme_detective                          -0.1806      0.102     -1.771      0.077      -0.381       0.019
theme_gag_humor                           0.1653      0.075      2.205      0.027       0.018       0.312
theme_gore                                0.3535      0.086      4.128      0.000       0.186       0.521
theme_harem                               0.1855      0.043      4.344      0.000       0.102       0.269
theme_historical                          0.0679      0.053      1.278      0.201      -0.036       0.172
theme_idols_(female)                      0.0568      0.084      0.674      0.500      -0.108       0.222
theme_isekai                              0.4371      0.054      8.141      0.000       0.332       0.542
theme_iyashikei                           0.4644      0.094      4.954      0.000       0.281       0.648
theme_love_polygon                        0.3882      0.071      5.495      0.000       0.250       0.527
theme_mahou_shoujo                        0.2689      0.069      3.909      0.000       0.134       0.404
theme_martial_arts                       -0.2258      0.099     -2.280      0.023      -0.420      -0.032
theme_mecha                               0.1416      0.047      2.981      0.003       0.048       0.235
theme_military                            0.0565      0.054      1.049      0.294      -0.049       0.162
theme_music                              -0.1131      0.063     -1.783      0.075      -0.237       0.011
theme_mythology                          -0.0927      0.056     -1.652      0.099      -0.203       0.017
theme_organized_crime                     0.2190      0.096      2.270      0.023       0.030       0.408
theme_otaku_culture                       0.5003      0.078      6.449      0.000       0.348       0.652
theme_other                               0.1145      0.039      2.968      0.003       0.039       0.190
theme_parody                             -0.1773      0.059     -3.004      0.003      -0.293      -0.062
theme_performing_arts                     0.0260      0.082      0.318      0.750      -0.134       0.186
theme_pets                               -0.0354      0.112     -0.316      0.752      -0.255       0.184
theme_psychological                       0.1750      0.089      1.967      0.049       0.001       0.349
theme_racing                              0.0186      0.099      0.189      0.850      -0.175       0.212
theme_reincarnation                       0.1701      0.069      2.474      0.013       0.035       0.305
theme_samurai                            -0.2702      0.097     -2.779      0.005      -0.461      -0.080
theme_school                              0.3532      0.029     12.284      0.000       0.297       0.410
theme_space                               0.2089      0.065      3.202      0.001       0.081       0.337
theme_strategy_game                      -0.3181      0.063     -5.054      0.000      -0.441      -0.195
theme_super_power                         0.1315      0.055      2.392      0.017       0.024       0.239
theme_team_sports                         0.1419      0.100      1.422      0.155      -0.054       0.337
theme_time_travel                         0.0481      0.094      0.513      0.608      -0.136       0.232
theme_urban_fantasy                       0.2406      0.065      3.688      0.000       0.113       0.369
theme_vampire                             0.1074      0.067      1.600      0.110      -0.024       0.239
theme_workplace                          -0.0528      0.075     -0.707      0.480      -0.199       0.094
demo_josei                                0.0288      0.076      0.378      0.706      -0.121       0.178
demo_kids                                -0.3258      0.052     -6.219      0.000      -0.428      -0.223
demo_seinen                               0.2153      0.036      5.903      0.000       0.144       0.287
demo_shoujo                               0.3061      0.061      5.044      0.000       0.187       0.425
demo_shounen                              0.4767      0.031     15.244      0.000       0.415       0.538
rating_PG - Children                     -0.0833      0.050     -1.674      0.094      -0.181       0.014
rating_PG-13 - Teens 13 or older          0.3838      0.038     10.017      0.000       0.309       0.459
rating_R - 17+ (violence & profanity)     0.7161      0.051     13.967      0.000       0.616       0.817
rating_R+ - Mild Nudity                   0.3858      0.066      5.867      0.000       0.257       0.515
sequel                                   -0.0396      0.024     -1.622      0.105      -0.088       0.008
==============================================================================
Omnibus:                       34.517   Durbin-Watson:                   1.787
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               50.239
Skew:                           0.036   Prob(JB):                     1.23e-11
Kurtosis:                       3.470   Cond. No.                         17.2
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [155]:
results = pd.DataFrame({
    'feature': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("feature != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
print(results.loc[results['significant']==True, 'coef'].head(10))
print(results.loc[results['significant']==True, 'coef'].tail(10))

genre_award_winning                      0.780794
rating_R - 17+ (violence & profanity)    0.716094
theme_otaku_culture                      0.500328
demo_shounen                             0.476691
theme_iyashikei                          0.464410
theme_isekai                             0.437054
theme_love_polygon                       0.388165
rating_R+ - Mild Nudity                  0.385825
genre_romance                            0.383997
rating_PG-13 - Teens 13 or older         0.383752
Name: coef, dtype: float64
genre_other            0.146844
theme_mecha            0.141556
theme_super_power      0.131495
theme_other            0.114457
theme_parody          -0.177288
genre_horror          -0.177430
theme_martial_arts    -0.225836
theme_samurai         -0.270150
theme_strategy_game   -0.318106
demo_kids             -0.325816
Name: coef, dtype: float64

In [156]:
rating_dummies = pd.get_dummies(df['rating'], prefix='rating', drop_first=True)
X = pd.concat([df[valid_genres], df[valid_themes], df[valid_demos], rating_dummies, df[['sequel']]], axis=1)
X = X.astype(float)
X = sm.add_constant(X)

model = sm.OLS(df['favorites_z'], X, missing='drop').fit(cov_type='HC3')
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            favorites_z   R-squared:                       0.385
Model:                            OLS   Adj. R-squared:                  0.378
Method:                 Least Squares   F-statistic:                     60.02
Date:                Sun, 16 Aug 2026   Prob (F-statistic):               0.00
Time:                        18:17:51   Log-Likelihood:                -6147.1
No. Observations:                5338   AIC:                         1.242e+04
Df Residuals:                    5273   BIC:                         1.285e+04
Df Model:                          64
Covariance Type:                  HC3
=========================================================================================================
                                            coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
const                                    -0.8982      0.042    -21.343      0.000      -0.981      -0.816
genre_action                              0.2524      0.031      8.076      0.000       0.191       0.314
genre_adventure                           0.2669      0.030      9.027      0.000       0.209       0.325
genre_award_winning                       1.0248      0.096     10.650      0.000       0.836       1.213
genre_comedy                             -0.0441      0.028     -1.601      0.109      -0.098       0.010
genre_drama                               0.3347      0.034      9.799      0.000       0.268       0.402
genre_ecchi                               0.0245      0.052      0.470      0.638      -0.078       0.127
genre_fantasy                             0.1862      0.032      5.875      0.000       0.124       0.248
genre_gourmet                             0.0727      0.090      0.806      0.420      -0.104       0.250
genre_horror                             -0.2829      0.076     -3.741      0.000      -0.431      -0.135
genre_mystery                             0.2094      0.053      3.916      0.000       0.105       0.314
genre_other                               0.2554      0.065      3.942      0.000       0.128       0.382
genre_romance                             0.3600      0.036     10.060      0.000       0.290       0.430
genre_sci-fi                              0.0256      0.035      0.724      0.469      -0.044       0.095
genre_slice_of_life                      -0.0249      0.059     -0.420      0.675      -0.141       0.091
genre_sports                              0.1885      0.073      2.591      0.010       0.046       0.331
genre_supernatural                        0.2054      0.045      4.594      0.000       0.118       0.293
genre_suspense                            0.2300      0.094      2.456      0.014       0.046       0.414
theme_adult_cast                          0.3416      0.052      6.514      0.000       0.239       0.444
theme_anthropomorphic                     0.0366      0.069      0.531      0.595      -0.098       0.171
theme_cgdct                               0.2359      0.068      3.485      0.000       0.103       0.369
theme_detective                          -0.2286      0.105     -2.174      0.030      -0.435      -0.023
theme_gag_humor                           0.3054      0.082      3.736      0.000       0.145       0.466
theme_gore                                0.3666      0.092      3.977      0.000       0.186       0.547
theme_harem                               0.0815      0.047      1.727      0.084      -0.011       0.174
theme_historical                          0.0971      0.051      1.897      0.058      -0.003       0.197
theme_idols_(female)                      0.0110      0.092      0.120      0.905      -0.169       0.191
theme_isekai                              0.3838      0.057      6.753      0.000       0.272       0.495
theme_iyashikei                           0.6290      0.103      6.111      0.000       0.427       0.831
theme_love_polygon                        0.5035      0.083      6.073      0.000       0.341       0.666
theme_mahou_shoujo                        0.3818      0.068      5.623      0.000       0.249       0.515
theme_martial_arts                       -0.1980      0.097     -2.034      0.042      -0.389      -0.007
theme_mecha                               0.1205      0.049      2.448      0.014       0.024       0.217
theme_military                            0.0861      0.059      1.468      0.142      -0.029       0.201
theme_music                               0.1099      0.067      1.634      0.102      -0.022       0.242
theme_mythology                          -0.0714      0.061     -1.180      0.238      -0.190       0.047
theme_organized_crime                     0.2692      0.113      2.375      0.018       0.047       0.491
theme_otaku_culture                       0.4879      0.091      5.353      0.000       0.309       0.666
theme_other                               0.1048      0.040      2.605      0.009       0.026       0.184
theme_parody                             -0.1027      0.060     -1.699      0.089      -0.221       0.016
theme_performing_arts                     0.0282      0.099      0.284      0.776      -0.166       0.223
theme_pets                                0.0019      0.104      0.018      0.985      -0.202       0.206
theme_psychological                       0.2429      0.095      2.544      0.011       0.056       0.430
theme_racing                              0.0742      0.098      0.759      0.448      -0.118       0.266
theme_reincarnation                       0.1431      0.078      1.846      0.065      -0.009       0.295
theme_samurai                            -0.2360      0.096     -2.461      0.014      -0.424      -0.048
theme_school                              0.3599      0.031     11.777      0.000       0.300       0.420
theme_space                               0.2297      0.069      3.330      0.001       0.095       0.365
theme_strategy_game                      -0.2910      0.060     -4.811      0.000      -0.410      -0.172
theme_super_power                         0.1291      0.057      2.282      0.022       0.018       0.240
theme_team_sports                         0.1545      0.100      1.541      0.123      -0.042       0.351
theme_time_travel                         0.1102      0.097      1.141      0.254      -0.079       0.299
theme_urban_fantasy                       0.2629      0.072      3.674      0.000       0.123       0.403
theme_vampire                             0.0757      0.079      0.955      0.340      -0.080       0.231
theme_workplace                          -0.0809      0.080     -1.014      0.310      -0.237       0.075
demo_josei                                0.0800      0.083      0.968      0.333      -0.082       0.242
demo_kids                                -0.2142      0.046     -4.611      0.000      -0.305      -0.123
demo_seinen                               0.2079      0.041      5.057      0.000       0.127       0.288
demo_shoujo                               0.3760      0.064      5.846      0.000       0.250       0.502
demo_shounen                              0.5101      0.033     15.465      0.000       0.445       0.575
rating_PG - Children                     -0.0708      0.045     -1.575      0.115      -0.159       0.017
rating_PG-13 - Teens 13 or older          0.2774      0.036      7.687      0.000       0.207       0.348
rating_R - 17+ (violence & profanity)     0.6852      0.053     13.036      0.000       0.582       0.788
rating_R+ - Mild Nudity                   0.3022      0.065      4.676      0.000       0.176       0.429
sequel                                   -0.1060      0.025     -4.219      0.000      -0.155      -0.057
==============================================================================
Omnibus:                       55.219   Durbin-Watson:                   1.852
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               59.202
Skew:                           0.220   Prob(JB):                     1.39e-13
Kurtosis:                       3.269   Cond. No.                         17.2
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [157]:
results = pd.DataFrame({
    'feature': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("feature != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
print(results.loc[results['significant']==True, 'coef'].head(10))
print(results.loc[results['significant']==True, 'coef'].tail(10))

genre_award_winning                      1.024755
rating_R - 17+ (violence & profanity)    0.685179
theme_iyashikei                          0.628964
demo_shounen                             0.510101
theme_love_polygon                       0.503539
theme_otaku_culture                      0.487852
theme_isekai                             0.383777
theme_mahou_shoujo                       0.381767
demo_shoujo                              0.376007
theme_gore                               0.366633
Name: coef, dtype: float64
genre_fantasy          0.186174
theme_super_power      0.129063
theme_mecha            0.120504
theme_other            0.104804
sequel                -0.106048
demo_kids             -0.214185
theme_detective       -0.228623
theme_samurai         -0.235981
genre_horror          -0.282922
theme_strategy_game   -0.290967
Name: coef, dtype: float64

In [158]:
rating_dummies = pd.get_dummies(df['rating'], prefix='rating', drop_first=True)
X = pd.concat([df[valid_genres], df[valid_themes], df[valid_demos], rating_dummies, df[['sequel']]], axis=1)
X = X.astype(float)
X = sm.add_constant(X)

model = sm.OLS(df['drop_rate_z'], X, missing='drop').fit(cov_type='HC3')
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            drop_rate_z   R-squared:                       0.257
Model:                            OLS   Adj. R-squared:                  0.248
Method:                 Least Squares   F-statistic:                     27.79
Date:                Sun, 16 Aug 2026   Prob (F-statistic):               0.00
Time:                        18:17:51   Log-Likelihood:                -6655.1
No. Observations:                5338   AIC:                         1.344e+04
Df Residuals:                    5273   BIC:                         1.387e+04
Df Model:                          64
Covariance Type:                  HC3
=========================================================================================================
                                            coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
const                                    -0.5020      0.038    -13.171      0.000      -0.577      -0.427
genre_action                              0.3059      0.036      8.559      0.000       0.236       0.376
genre_adventure                           0.1715      0.032      5.301      0.000       0.108       0.235
genre_award_winning                       0.7833      0.187      4.180      0.000       0.416       1.151
genre_comedy                             -0.0221      0.029     -0.759      0.448      -0.079       0.035
genre_drama                               0.1201      0.038      3.197      0.001       0.046       0.194
genre_ecchi                               0.0574      0.069      0.829      0.407      -0.078       0.193
genre_fantasy                             0.2034      0.035      5.825      0.000       0.135       0.272
genre_gourmet                            -0.0031      0.083     -0.038      0.970      -0.165       0.159
genre_horror                             -0.1358      0.088     -1.550      0.121      -0.308       0.036
genre_mystery                             0.1335      0.071      1.892      0.059      -0.005       0.272
genre_other                               0.0633      0.077      0.821      0.412      -0.088       0.214
genre_romance                             0.3091      0.043      7.247      0.000       0.226       0.393
genre_sci-fi                             -0.0689      0.038     -1.791      0.073      -0.144       0.006
genre_slice_of_life                      -0.0826      0.051     -1.633      0.102      -0.182       0.017
genre_sports                             -0.0204      0.065     -0.313      0.754      -0.148       0.107
genre_supernatural                        0.1495      0.054      2.764      0.006       0.043       0.256
genre_suspense                            0.2911      0.124      2.341      0.019       0.047       0.535
theme_adult_cast                          0.2091      0.063      3.319      0.001       0.086       0.333
theme_anthropomorphic                     0.0006      0.057      0.011      0.991      -0.111       0.112
theme_cgdct                              -0.0163      0.061     -0.269      0.788      -0.136       0.103
theme_detective                          -0.2851      0.125     -2.276      0.023      -0.531      -0.040
theme_gag_humor                           0.1773      0.091      1.954      0.051      -0.001       0.355
theme_gore                                0.4676      0.136      3.435      0.001       0.201       0.734
theme_harem                               0.0228      0.062      0.371      0.711      -0.098       0.144
theme_historical                         -0.1153      0.049     -2.370      0.018      -0.211      -0.020
theme_idols_(female)                      0.0047      0.072      0.066      0.948      -0.136       0.145
theme_isekai                              0.2363      0.070      3.397      0.001       0.100       0.373
theme_iyashikei                           0.0955      0.083      1.144      0.252      -0.068       0.259
theme_love_polygon                        0.5265      0.125      4.209      0.000       0.281       0.772
theme_mahou_shoujo                       -0.0048      0.063     -0.076      0.939      -0.129       0.119
theme_martial_arts                       -0.1091      0.136     -0.804      0.421      -0.375       0.157
theme_mecha                               0.0989      0.049      2.009      0.045       0.002       0.195
theme_military                           -0.0145      0.070     -0.208      0.835      -0.152       0.123
theme_music                              -0.1486      0.060     -2.493      0.013      -0.265      -0.032
theme_mythology                          -0.1251      0.080     -1.568      0.117      -0.281       0.031
theme_organized_crime                     0.1359      0.153      0.891      0.373      -0.163       0.435
theme_otaku_culture                       0.3206      0.115      2.797      0.005       0.096       0.545
theme_other                               0.0546      0.047      1.164      0.244      -0.037       0.146
theme_parody                              0.0083      0.064      0.129      0.897      -0.117       0.134
theme_performing_arts                    -0.0712      0.087     -0.822      0.411      -0.241       0.099
theme_pets                                0.0244      0.077      0.317      0.751      -0.126       0.175
theme_psychological                       0.3788      0.133      2.845      0.004       0.118       0.640
theme_racing                             -0.1251      0.061     -2.063      0.039      -0.244      -0.006
theme_reincarnation                       0.0086      0.094      0.092      0.927      -0.175       0.192
theme_samurai                            -0.1900      0.102     -1.863      0.063      -0.390       0.010
theme_school                              0.2074      0.036      5.778      0.000       0.137       0.278
theme_space                               0.0631      0.069      0.915      0.360      -0.072       0.198
theme_strategy_game                      -0.2084      0.058     -3.607      0.000      -0.322      -0.095
theme_super_power                         0.0473      0.067      0.702      0.483      -0.085       0.179
theme_team_sports                         0.0510      0.093      0.550      0.582      -0.131       0.233
theme_time_travel                         0.0249      0.115      0.216      0.829      -0.201       0.251
theme_urban_fantasy                       0.2916      0.118      2.462      0.014       0.059       0.524
theme_vampire                             0.0786      0.118      0.666      0.505      -0.153       0.310
theme_workplace                          -0.1193      0.070     -1.705      0.088      -0.256       0.018
demo_josei                               -0.1991      0.064     -3.101      0.002      -0.325      -0.073
demo_kids                                -0.0173      0.035     -0.495      0.620      -0.086       0.051
demo_seinen                               0.1074      0.044      2.465      0.014       0.022       0.193
demo_shoujo                               0.2393      0.067      3.563      0.000       0.108       0.371
demo_shounen                              0.4055      0.044      9.188      0.000       0.319       0.492
rating_PG - Children                     -0.0213      0.035     -0.611      0.541      -0.090       0.047
rating_PG-13 - Teens 13 or older          0.2009      0.030      6.617      0.000       0.141       0.260
rating_R - 17+ (violence & profanity)     0.4025      0.062      6.543      0.000       0.282       0.523
rating_R+ - Mild Nudity                   0.2510      0.074      3.372      0.001       0.105       0.397
sequel                                   -0.4538      0.027    -16.935      0.000      -0.506      -0.401
==============================================================================
Omnibus:                     2519.646   Durbin-Watson:                   1.877
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            17294.618
Skew:                           2.155   Prob(JB):                         0.00
Kurtosis:                      10.693   Cond. No.                         17.2
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [159]:
results = pd.DataFrame({
    'feature': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("feature != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
print(results.loc[results['significant']==True, 'coef'].head(10))
print(results.loc[results['significant']==True, 'coef'].tail(10))

genre_award_winning                      0.783274
theme_love_polygon                       0.526465
theme_gore                               0.467623
demo_shounen                             0.405482
rating_R - 17+ (violence & profanity)    0.402549
theme_psychological                      0.378825
theme_otaku_culture                      0.320602
genre_romance                            0.309139
genre_action                             0.305905
theme_urban_fantasy                      0.291567
Name: coef, dtype: float64
rating_PG-13 - Teens 13 or older    0.200851
genre_adventure                     0.171460
genre_supernatural                  0.149490
genre_drama                         0.120077
demo_seinen                         0.107411
theme_historical                   -0.115307
theme_music                        -0.148612
demo_josei                         -0.199067
theme_strategy_game                -0.208382
sequel                             -0.453779
Name: coef, dtype: float64

In [160]:
rating_dummies = pd.get_dummies(df['rating'], prefix='rating', drop_first=True)
X = pd.concat([df[valid_genres], df[valid_themes], df[valid_demos], rating_dummies, df[['sequel']]], axis=1)
X = X.astype(float)
X = sm.add_constant(X)

model = sm.OLS(df['forum_z'], X, missing='drop').fit(cov_type='HC3')
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                forum_z   R-squared:                       0.392
Model:                            OLS   Adj. R-squared:                  0.385
Method:                 Least Squares   F-statistic:                     58.72
Date:                Sun, 16 Aug 2026   Prob (F-statistic):               0.00
Time:                        18:17:52   Log-Likelihood:                -6107.3
No. Observations:                5338   AIC:                         1.234e+04
Df Residuals:                    5273   BIC:                         1.277e+04
Df Model:                          64
Covariance Type:                  HC3
=========================================================================================================
                                            coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
const                                    -0.9198      0.048    -19.169      0.000      -1.014      -0.826
genre_action                              0.1889      0.030      6.239      0.000       0.130       0.248
genre_adventure                           0.2013      0.029      6.844      0.000       0.144       0.259
genre_award_winning                       0.5924      0.066      8.909      0.000       0.462       0.723
genre_comedy                             -0.0563      0.028     -1.991      0.047      -0.112      -0.001
genre_drama                               0.3138      0.030     10.534      0.000       0.255       0.372
genre_ecchi                               0.1702      0.049      3.489      0.000       0.075       0.266
genre_fantasy                             0.1755      0.033      5.348      0.000       0.111       0.240
genre_gourmet                             0.1122      0.092      1.214      0.225      -0.069       0.293
genre_horror                             -0.0032      0.062     -0.052      0.958      -0.125       0.118
genre_mystery                             0.2229      0.047      4.729      0.000       0.131       0.315
genre_other                               0.1732      0.065      2.664      0.008       0.046       0.301
genre_romance                             0.3215      0.033      9.817      0.000       0.257       0.386
genre_sci-fi                              0.1143      0.035      3.282      0.001       0.046       0.183
genre_slice_of_life                       0.0210      0.066      0.318      0.750      -0.108       0.150
genre_sports                              0.1366      0.068      1.996      0.046       0.002       0.271
genre_supernatural                        0.1920      0.042      4.556      0.000       0.109       0.275
genre_suspense                            0.1633      0.086      1.908      0.056      -0.004       0.331
theme_adult_cast                          0.2869      0.045      6.391      0.000       0.199       0.375
theme_anthropomorphic                     0.0106      0.076      0.140      0.889      -0.138       0.159
theme_cgdct                               0.4210      0.056      7.497      0.000       0.311       0.531
theme_detective                          -0.1313      0.096     -1.372      0.170      -0.319       0.056
theme_gag_humor                           0.1401      0.077      1.810      0.070      -0.012       0.292
theme_gore                                0.1809      0.067      2.708      0.007       0.050       0.312
theme_harem                               0.0530      0.045      1.188      0.235      -0.034       0.140
theme_historical                          0.1175      0.051      2.309      0.021       0.018       0.217
theme_idols_(female)                      0.1678      0.100      1.679      0.093      -0.028       0.364
theme_isekai                              0.3317      0.055      6.062      0.000       0.224       0.439
theme_iyashikei                           0.4215      0.104      4.069      0.000       0.218       0.625
theme_love_polygon                        0.2774      0.065      4.256      0.000       0.150       0.405
theme_mahou_shoujo                        0.3889      0.078      5.005      0.000       0.237       0.541
theme_martial_arts                       -0.1673      0.093     -1.796      0.073      -0.350       0.015
theme_mecha                               0.0876      0.051      1.723      0.085      -0.012       0.187
theme_military                            0.1161      0.050      2.302      0.021       0.017       0.215
theme_music                              -0.0207      0.065     -0.319      0.750      -0.148       0.107
theme_mythology                          -0.0858      0.052     -1.649      0.099      -0.188       0.016
theme_organized_crime                     0.1404      0.079      1.779      0.075      -0.014       0.295
theme_otaku_culture                       0.4311      0.071      6.044      0.000       0.291       0.571
theme_other                               0.0984      0.037      2.688      0.007       0.027       0.170
theme_parody                             -0.1274      0.062     -2.047      0.041      -0.249      -0.005
theme_performing_arts                     0.1258      0.088      1.430      0.153      -0.047       0.298
theme_pets                               -0.1030      0.139     -0.740      0.459      -0.376       0.170
theme_psychological                       0.2191      0.077      2.848      0.004       0.068       0.370
theme_racing                             -0.1309      0.107     -1.218      0.223      -0.342       0.080
theme_reincarnation                       0.0141      0.069      0.204      0.839      -0.121       0.149
theme_samurai                            -0.1826      0.098     -1.854      0.064      -0.376       0.010
theme_school                              0.3029      0.029     10.542      0.000       0.247       0.359
theme_space                               0.3267      0.066      4.982      0.000       0.198       0.455
theme_strategy_game                      -0.4268      0.069     -6.155      0.000      -0.563      -0.291
theme_super_power                         0.0392      0.052      0.759      0.448      -0.062       0.140
theme_team_sports                         0.0452      0.092      0.491      0.624      -0.135       0.226
theme_time_travel                         0.0796      0.087      0.913      0.361      -0.091       0.250
theme_urban_fantasy                       0.1792      0.059      3.035      0.002       0.063       0.295
theme_vampire                            -0.0233      0.074     -0.314      0.753      -0.169       0.122
theme_workplace                          -0.0503      0.085     -0.589      0.556      -0.218       0.117
demo_josei                                0.0374      0.076      0.492      0.623      -0.112       0.187
demo_kids                                -0.2987      0.054     -5.558      0.000      -0.404      -0.193
demo_seinen                               0.2431      0.038      6.361      0.000       0.168       0.318
demo_shoujo                               0.2129      0.060      3.520      0.000       0.094       0.331
demo_shounen                              0.3700      0.030     12.254      0.000       0.311       0.429
rating_PG - Children                     -0.1692      0.054     -3.125      0.002      -0.275      -0.063
rating_PG-13 - Teens 13 or older          0.4850      0.042     11.572      0.000       0.403       0.567
rating_R - 17+ (violence & profanity)     0.7800      0.051     15.383      0.000       0.681       0.879
rating_R+ - Mild Nudity                   0.4657      0.069      6.748      0.000       0.330       0.601
sequel                                   -0.1333      0.025     -5.351      0.000      -0.182      -0.084
==============================================================================
Omnibus:                      796.225   Durbin-Watson:                   1.852
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1848.586
Skew:                          -0.861   Prob(JB):                         0.00
Kurtosis:                       5.312   Cond. No.                         17.2
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [161]:
results = pd.DataFrame({
    'feature': model.params.index,
    'coef': model.params.values,
    'pval': model.pvalues.values,
    'ci_low': model.conf_int()[0],
    'ci_high': model.conf_int()[1],
}).query("feature != 'const'")

# FDR correction across all genre coefficients (Benjamini-Hochberg)
from statsmodels.stats.multitest import multipletests
results['pval_fdr'] = multipletests(results['pval'], method='fdr_bh')[1]
results['significant'] = results['pval_fdr'] < 0.05

results = results.sort_values('coef', ascending=False)
print(results.loc[results['significant']==True, 'coef'].head(10))
print(results.loc[results['significant']==True, 'coef'].tail(10))

rating_R - 17+ (violence & profanity)    0.780008
genre_award_winning                      0.592356
rating_PG-13 - Teens 13 or older         0.485001
rating_R+ - Mild Nudity                  0.465697
theme_otaku_culture                      0.431052
theme_iyashikei                          0.421501
theme_cgdct                              0.420974
theme_mahou_shoujo                       0.388882
demo_shounen                             0.369987
theme_isekai                             0.331714
Name: coef, dtype: float64
genre_other             0.173249
genre_ecchi             0.170231
theme_historical        0.117533
theme_military          0.116115
genre_sci-fi            0.114320
theme_other             0.098395
sequel                 -0.133295
rating_PG - Children   -0.169228
demo_kids              -0.298705
theme_strategy_game    -0.426843
Name: coef, dtype: float64