# Machine Learning

In [56]:
import os
os.environ["SCIPY_ARRAY_API"] = "1"

In [57]:
import sklearn
sklearn.set_config(array_api_dispatch=True)

In [ ]:
import cupy as cp
import pandas as pd
import numpy as np
from sklearn.model_selection import (
    train_test_split,
    PredefinedSplit,
    RandomizedSearchCV
)
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    mean_squared_error, 
    r2_score
)
from sklearn.multioutput import MultiOutputRegressor
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
import xgboost as xgb
from scipy.stats import (
    uniform, 
    randint,
    loguniform
)
import matplotlib.pyplot as plt
import copy
from pprint import pprint
import json
from statsmodels.stats.outliers_influence import variance_inflation_factor
import torch
from xgboost import XGBRegressor

In [59]:
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

In [60]:
initial_df = pd.read_parquet("../data/processed/anime_data_2.parquet")
initial_df.info()

<class 'pandas.DataFrame'>
Index: 5350 entries, 0 to 71
Data columns (total 87 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   mal_id                  5350 non-null   int64
 1   title                   5350 non-null   str
 2   producers               5350 non-null   object
 3   genres                  5350 non-null   object
 4   studios                 5350 non-null   object
 5   demographics            5350 non-null   object
 6   themes                  5350 non-null   object
 7   rating                  5309 non-null   str
 8   sequel                  5350 non-null   bool
 9   members                 5350 non-null   int64
 10  thumbnail               5350 non-null   bool
 11  prequel_score           1388 non-null   float64
 12  prequel_members         1402 non-null   float64
 13  prequel_type            1402 non-null   str
 14  cohort                  5350 non-null   str
 15  drop_rate               5340 non-null   float64
 16  wc_z                    5350 non-null   float64
 17  forum_z                 5350 non-null   float64
 18  favorites_z             5350 non-null   float64
 19  score_z                 5350 non-null   float64
 20  dropped_z               5350 non-null   float64
 21  drop_rate_z             5350 non-null   float64
 22  adaptation_score        2753 non-null   float64
 23  adaptation_members      3486 non-null   float64
 24  has_adaptation_score    5350 non-null   int64
 25  has_adaptation_members  5350 non-null   int64
 26  has_prequel_score       5350 non-null   int64
 27  has_prequel_members     5350 non-null   int64
 28  has_prequel_type        5350 non-null   int64
 29  genre_Action            5350 non-null   int64
 30  genre_Adventure         5350 non-null   int64
 31  genre_Comedy            5350 non-null   int64
 32  genre_Drama             5350 non-null   int64
 33  genre_Ecchi             5350 non-null   int64
 34  genre_Fantasy           5350 non-null   int64
 35  genre_Gourmet           5350 non-null   int64
 36  genre_Horror            5350 non-null   int64
 37  genre_Mystery           5350 non-null   int64
 38  genre_Other             5350 non-null   int64
 39  genre_Romance           5350 non-null   int64
 40  genre_Sci-Fi            5350 non-null   int64
 41  genre_Slice_of_Life     5350 non-null   int64
 42  genre_Sports            5350 non-null   int64
 43  genre_Supernatural      5350 non-null   int64
 44  genre_Suspense          5350 non-null   int64
 45  theme_Adult_Cast        5350 non-null   int64
 46  theme_Anthropomorphic   5350 non-null   int64
 47  theme_CGDCT             5350 non-null   int64
 48  theme_Detective         5350 non-null   int64
 49  theme_Gag_Humor         5350 non-null   int64
 50  theme_Gore              5350 non-null   int64
 51  theme_Harem             5350 non-null   int64
 52  theme_Historical        5350 non-null   int64
 53  theme_Idols_(Female)    5350 non-null   int64
 54  theme_Isekai            5350 non-null   int64
 55  theme_Iyashikei         5350 non-null   int64
 56  theme_Love_Polygon      5350 non-null   int64
 57  theme_Mahou_Shoujo      5350 non-null   int64
 58  theme_Martial_Arts      5350 non-null   int64
 59  theme_Mecha             5350 non-null   int64
 60  theme_Military          5350 non-null   int64
 61  theme_Music             5350 non-null   int64
 62  theme_Mythology         5350 non-null   int64
 63  theme_Organized_Crime   5350 non-null   int64
 64  theme_Otaku_Culture     5350 non-null   int64
 65  theme_Other             5350 non-null   int64
 66  theme_Parody            5350 non-null   int64
 67  theme_Performing_Arts   5350 non-null   int64
 68  theme_Pets              5350 non-null   int64
 69  theme_Psychological     5350 non-null   int64
 70  theme_Racing            5350 non-null   int64
 71  theme_Reincarnation     5350 non-null   int64
 72  theme_Samurai           5350 non-null   int64
 73  theme_School            5350 non-null   int64
 74  theme_Space             5350 non-null   int64
 75  theme_Strategy_Game     5350 non-null   int64
 76  theme_Super_Power       5350 non-null   int64
 77  theme_Team_Sports       5350 non-null   int64
 78  theme_Time_Travel       5350 non-null   int64
 79  theme_Urban_Fantasy     5350 non-null   int64
 80  theme_Vampire           5350 non-null   int64
 81  theme_Workplace         5350 non-null   int64
 82  demo_Josei              5350 non-null   int64
 83  demo_Kids               5350 non-null   int64
 84  demo_Seinen             5350 non-null   int64
 85  demo_Shoujo             5350 non-null   int64
 86  demo_Shounen            5350 non-null   int64
dtypes: bool(2), float64(11), int64(65), object(5), str(4)
memory usage: 3.8+ MB

In [61]:
df = initial_df.head(5278)
real_df = initial_df.tail(72)

print(df.info())
print(real_df.info())

<class 'pandas.DataFrame'>
Index: 5278 entries, 0 to 5307
Data columns (total 87 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   mal_id                  5278 non-null   int64
 1   title                   5278 non-null   str
 2   producers               5278 non-null   object
 3   genres                  5278 non-null   object
 4   studios                 5278 non-null   object
 5   demographics            5278 non-null   object
 6   themes                  5278 non-null   object
 7   rating                  5278 non-null   str
 8   sequel                  5278 non-null   bool
 9   members                 5278 non-null   int64
 10  thumbnail               5278 non-null   bool
 11  prequel_score           1364 non-null   float64
 12  prequel_members         1376 non-null   float64
 13  prequel_type            1376 non-null   str
 14  cohort                  5278 non-null   str
 15  drop_rate               5278 non-null   float64
 16  wc_z                    5278 non-null   float64
 17  forum_z                 5278 non-null   float64
 18  favorites_z             5278 non-null   float64
 19  score_z                 5278 non-null   float64
 20  dropped_z               5278 non-null   float64
 21  drop_rate_z             5278 non-null   float64
 22  adaptation_score        2706 non-null   float64
 23  adaptation_members      3428 non-null   float64
 24  has_adaptation_score    5278 non-null   int64
 25  has_adaptation_members  5278 non-null   int64
 26  has_prequel_score       5278 non-null   int64
 27  has_prequel_members     5278 non-null   int64
 28  has_prequel_type        5278 non-null   int64
 29  genre_Action            5278 non-null   int64
 30  genre_Adventure         5278 non-null   int64
 31  genre_Comedy            5278 non-null   int64
 32  genre_Drama             5278 non-null   int64
 33  genre_Ecchi             5278 non-null   int64
 34  genre_Fantasy           5278 non-null   int64
 35  genre_Gourmet           5278 non-null   int64
 36  genre_Horror            5278 non-null   int64
 37  genre_Mystery           5278 non-null   int64
 38  genre_Other             5278 non-null   int64
 39  genre_Romance           5278 non-null   int64
 40  genre_Sci-Fi            5278 non-null   int64
 41  genre_Slice_of_Life     5278 non-null   int64
 42  genre_Sports            5278 non-null   int64
 43  genre_Supernatural      5278 non-null   int64
 44  genre_Suspense          5278 non-null   int64
 45  theme_Adult_Cast        5278 non-null   int64
 46  theme_Anthropomorphic   5278 non-null   int64
 47  theme_CGDCT             5278 non-null   int64
 48  theme_Detective         5278 non-null   int64
 49  theme_Gag_Humor         5278 non-null   int64
 50  theme_Gore              5278 non-null   int64
 51  theme_Harem             5278 non-null   int64
 52  theme_Historical        5278 non-null   int64
 53  theme_Idols_(Female)    5278 non-null   int64
 54  theme_Isekai            5278 non-null   int64
 55  theme_Iyashikei         5278 non-null   int64
 56  theme_Love_Polygon      5278 non-null   int64
 57  theme_Mahou_Shoujo      5278 non-null   int64
 58  theme_Martial_Arts      5278 non-null   int64
 59  theme_Mecha             5278 non-null   int64
 60  theme_Military          5278 non-null   int64
 61  theme_Music             5278 non-null   int64
 62  theme_Mythology         5278 non-null   int64
 63  theme_Organized_Crime   5278 non-null   int64
 64  theme_Otaku_Culture     5278 non-null   int64
 65  theme_Other             5278 non-null   int64
 66  theme_Parody            5278 non-null   int64
 67  theme_Performing_Arts   5278 non-null   int64
 68  theme_Pets              5278 non-null   int64
 69  theme_Psychological     5278 non-null   int64
 70  theme_Racing            5278 non-null   int64
 71  theme_Reincarnation     5278 non-null   int64
 72  theme_Samurai           5278 non-null   int64
 73  theme_School            5278 non-null   int64
 74  theme_Space             5278 non-null   int64
 75  theme_Strategy_Game     5278 non-null   int64
 76  theme_Super_Power       5278 non-null   int64
 77  theme_Team_Sports       5278 non-null   int64
 78  theme_Time_Travel       5278 non-null   int64
 79  theme_Urban_Fantasy     5278 non-null   int64
 80  theme_Vampire           5278 non-null   int64
 81  theme_Workplace         5278 non-null   int64
 82  demo_Josei              5278 non-null   int64
 83  demo_Kids               5278 non-null   int64
 84  demo_Seinen             5278 non-null   int64
 85  demo_Shoujo             5278 non-null   int64
 86  demo_Shounen            5278 non-null   int64
dtypes: bool(2), float64(11), int64(65), object(5), str(4)
memory usage: 3.8+ MB
None
<class 'pandas.DataFrame'>
Index: 72 entries, 0 to 71
Data columns (total 87 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   mal_id                  72 non-null     int64
 1   title                   72 non-null     str
 2   producers               72 non-null     object
 3   genres                  72 non-null     object
 4   studios                 72 non-null     object
 5   demographics            72 non-null     object
 6   themes                  72 non-null     object
 7   rating                  31 non-null     str
 8   sequel                  72 non-null     bool
 9   members                 72 non-null     int64
 10  thumbnail               72 non-null     bool
 11  prequel_score           24 non-null     float64
 12  prequel_members         26 non-null     float64
 13  prequel_type            26 non-null     str
 14  cohort                  72 non-null     str
 15  drop_rate               62 non-null     float64
 16  wc_z                    72 non-null     float64
 17  forum_z                 72 non-null     float64
 18  favorites_z             72 non-null     float64
 19  score_z                 72 non-null     float64
 20  dropped_z               72 non-null     float64
 21  drop_rate_z             72 non-null     float64
 22  adaptation_score        47 non-null     float64
 23  adaptation_members      58 non-null     float64
 24  has_adaptation_score    72 non-null     int64
 25  has_adaptation_members  72 non-null     int64
 26  has_prequel_score       72 non-null     int64
 27  has_prequel_members     72 non-null     int64
 28  has_prequel_type        72 non-null     int64
 29  genre_Action            72 non-null     int64
 30  genre_Adventure         72 non-null     int64
 31  genre_Comedy            72 non-null     int64
 32  genre_Drama             72 non-null     int64
 33  genre_Ecchi             72 non-null     int64
 34  genre_Fantasy           72 non-null     int64
 35  genre_Gourmet           72 non-null     int64
 36  genre_Horror            72 non-null     int64
 37  genre_Mystery           72 non-null     int64
 38  genre_Other             72 non-null     int64
 39  genre_Romance           72 non-null     int64
 40  genre_Sci-Fi            72 non-null     int64
 41  genre_Slice_of_Life     72 non-null     int64
 42  genre_Sports            72 non-null     int64
 43  genre_Supernatural      72 non-null     int64
 44  genre_Suspense          72 non-null     int64
 45  theme_Adult_Cast        72 non-null     int64
 46  theme_Anthropomorphic   72 non-null     int64
 47  theme_CGDCT             72 non-null     int64
 48  theme_Detective         72 non-null     int64
 49  theme_Gag_Humor         72 non-null     int64
 50  theme_Gore              72 non-null     int64
 51  theme_Harem             72 non-null     int64
 52  theme_Historical        72 non-null     int64
 53  theme_Idols_(Female)    72 non-null     int64
 54  theme_Isekai            72 non-null     int64
 55  theme_Iyashikei         72 non-null     int64
 56  theme_Love_Polygon      72 non-null     int64
 57  theme_Mahou_Shoujo      72 non-null     int64
 58  theme_Martial_Arts      72 non-null     int64
 59  theme_Mecha             72 non-null     int64
 60  theme_Military          72 non-null     int64
 61  theme_Music             72 non-null     int64
 62  theme_Mythology         72 non-null     int64
 63  theme_Organized_Crime   72 non-null     int64
 64  theme_Otaku_Culture     72 non-null     int64
 65  theme_Other             72 non-null     int64
 66  theme_Parody            72 non-null     int64
 67  theme_Performing_Arts   72 non-null     int64
 68  theme_Pets              72 non-null     int64
 69  theme_Psychological     72 non-null     int64
 70  theme_Racing            72 non-null     int64
 71  theme_Reincarnation     72 non-null     int64
 72  theme_Samurai           72 non-null     int64
 73  theme_School            72 non-null     int64
 74  theme_Space             72 non-null     int64
 75  theme_Strategy_Game     72 non-null     int64
 76  theme_Super_Power       72 non-null     int64
 77  theme_Team_Sports       72 non-null     int64
 78  theme_Time_Travel       72 non-null     int64
 79  theme_Urban_Fantasy     72 non-null     int64
 80  theme_Vampire           72 non-null     int64
 81  theme_Workplace         72 non-null     int64
 82  demo_Josei              72 non-null     int64
 83  demo_Kids               72 non-null     int64
 84  demo_Seinen             72 non-null     int64
 85  demo_Shoujo             72 non-null     int64
 86  demo_Shounen            72 non-null     int64
dtypes: bool(2), float64(11), int64(65), object(5), str(4)
memory usage: 52.4+ KB
None

## Input Preparation

Plan:
* adaptation_members and prequel_members obey a power law, which could be problematic
* fill NaN values with zeroes and let the model learn from the bools (this imputation will be handled in notebook 1 soon)

In [62]:
df = df.reset_index(drop=True)

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5278 entries, 0 to 5277
Data columns (total 87 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   mal_id                  5278 non-null   int64
 1   title                   5278 non-null   str
 2   producers               5278 non-null   object
 3   genres                  5278 non-null   object
 4   studios                 5278 non-null   object
 5   demographics            5278 non-null   object
 6   themes                  5278 non-null   object
 7   rating                  5278 non-null   str
 8   sequel                  5278 non-null   bool
 9   members                 5278 non-null   int64
 10  thumbnail               5278 non-null   bool
 11  prequel_score           1364 non-null   float64
 12  prequel_members         1376 non-null   float64
 13  prequel_type            1376 non-null   str
 14  cohort                  5278 non-null   str
 15  drop_rate               5278 non-null   float64
 16  wc_z                    5278 non-null   float64
 17  forum_z                 5278 non-null   float64
 18  favorites_z             5278 non-null   float64
 19  score_z                 5278 non-null   float64
 20  dropped_z               5278 non-null   float64
 21  drop_rate_z             5278 non-null   float64
 22  adaptation_score        2706 non-null   float64
 23  adaptation_members      3428 non-null   float64
 24  has_adaptation_score    5278 non-null   int64
 25  has_adaptation_members  5278 non-null   int64
 26  has_prequel_score       5278 non-null   int64
 27  has_prequel_members     5278 non-null   int64
 28  has_prequel_type        5278 non-null   int64
 29  genre_Action            5278 non-null   int64
 30  genre_Adventure         5278 non-null   int64
 31  genre_Comedy            5278 non-null   int64
 32  genre_Drama             5278 non-null   int64
 33  genre_Ecchi             5278 non-null   int64
 34  genre_Fantasy           5278 non-null   int64
 35  genre_Gourmet           5278 non-null   int64
 36  genre_Horror            5278 non-null   int64
 37  genre_Mystery           5278 non-null   int64
 38  genre_Other             5278 non-null   int64
 39  genre_Romance           5278 non-null   int64
 40  genre_Sci-Fi            5278 non-null   int64
 41  genre_Slice_of_Life     5278 non-null   int64
 42  genre_Sports            5278 non-null   int64
 43  genre_Supernatural      5278 non-null   int64
 44  genre_Suspense          5278 non-null   int64
 45  theme_Adult_Cast        5278 non-null   int64
 46  theme_Anthropomorphic   5278 non-null   int64
 47  theme_CGDCT             5278 non-null   int64
 48  theme_Detective         5278 non-null   int64
 49  theme_Gag_Humor         5278 non-null   int64
 50  theme_Gore              5278 non-null   int64
 51  theme_Harem             5278 non-null   int64
 52  theme_Historical        5278 non-null   int64
 53  theme_Idols_(Female)    5278 non-null   int64
 54  theme_Isekai            5278 non-null   int64
 55  theme_Iyashikei         5278 non-null   int64
 56  theme_Love_Polygon      5278 non-null   int64
 57  theme_Mahou_Shoujo      5278 non-null   int64
 58  theme_Martial_Arts      5278 non-null   int64
 59  theme_Mecha             5278 non-null   int64
 60  theme_Military          5278 non-null   int64
 61  theme_Music             5278 non-null   int64
 62  theme_Mythology         5278 non-null   int64
 63  theme_Organized_Crime   5278 non-null   int64
 64  theme_Otaku_Culture     5278 non-null   int64
 65  theme_Other             5278 non-null   int64
 66  theme_Parody            5278 non-null   int64
 67  theme_Performing_Arts   5278 non-null   int64
 68  theme_Pets              5278 non-null   int64
 69  theme_Psychological     5278 non-null   int64
 70  theme_Racing            5278 non-null   int64
 71  theme_Reincarnation     5278 non-null   int64
 72  theme_Samurai           5278 non-null   int64
 73  theme_School            5278 non-null   int64
 74  theme_Space             5278 non-null   int64
 75  theme_Strategy_Game     5278 non-null   int64
 76  theme_Super_Power       5278 non-null   int64
 77  theme_Team_Sports       5278 non-null   int64
 78  theme_Time_Travel       5278 non-null   int64
 79  theme_Urban_Fantasy     5278 non-null   int64
 80  theme_Vampire           5278 non-null   int64
 81  theme_Workplace         5278 non-null   int64
 82  demo_Josei              5278 non-null   int64
 83  demo_Kids               5278 non-null   int64
 84  demo_Seinen             5278 non-null   int64
 85  demo_Shoujo             5278 non-null   int64
 86  demo_Shounen            5278 non-null   int64
dtypes: bool(2), float64(11), int64(65), object(5), str(4)
memory usage: 3.7+ MB

In [64]:
df = df.fillna({'prequel_score': 0, 'prequel_members': 0, 'prequel_type': "", 'adaptation_score': 0,'adaptation_members': 0})
real_df = real_df.fillna({'prequel_score': 0, 'prequel_members': 0, 'prequel_type': "", 'adaptation_score': 0,'adaptation_members': 0})

cols_to_log = ['prequel_members'] # this will change in the third data pass!
df[cols_to_log] = np.log1p(df[cols_to_log])
real_df[cols_to_log] = np.log1p(real_df[cols_to_log])
print(df[cols_to_log].describe())
print(real_df[cols_to_log].describe())

       prequel_members
count      5278.000000
mean          2.800895
std           4.852111
min           0.000000
25%           0.000000
50%           0.000000
75%           6.769399
max          15.300479
       prequel_members
count        72.000000
mean          3.993404
std           5.503425
min           0.000000
25%           0.000000
50%           0.000000
75%          10.334042
max          14.474516

Let's test for alignment:

In [65]:
print(df.info())
print(real_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 5278 entries, 0 to 5277
Data columns (total 87 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   mal_id                  5278 non-null   int64
 1   title                   5278 non-null   str
 2   producers               5278 non-null   object
 3   genres                  5278 non-null   object
 4   studios                 5278 non-null   object
 5   demographics            5278 non-null   object
 6   themes                  5278 non-null   object
 7   rating                  5278 non-null   str
 8   sequel                  5278 non-null   bool
 9   members                 5278 non-null   int64
 10  thumbnail               5278 non-null   bool
 11  prequel_score           5278 non-null   float64
 12  prequel_members         5278 non-null   float64
 13  prequel_type            5278 non-null   str
 14  cohort                  5278 non-null   str
 15  drop_rate               5278 non-null   float64
 16  wc_z                    5278 non-null   float64
 17  forum_z                 5278 non-null   float64
 18  favorites_z             5278 non-null   float64
 19  score_z                 5278 non-null   float64
 20  dropped_z               5278 non-null   float64
 21  drop_rate_z             5278 non-null   float64
 22  adaptation_score        5278 non-null   float64
 23  adaptation_members      5278 non-null   float64
 24  has_adaptation_score    5278 non-null   int64
 25  has_adaptation_members  5278 non-null   int64
 26  has_prequel_score       5278 non-null   int64
 27  has_prequel_members     5278 non-null   int64
 28  has_prequel_type        5278 non-null   int64
 29  genre_Action            5278 non-null   int64
 30  genre_Adventure         5278 non-null   int64
 31  genre_Comedy            5278 non-null   int64
 32  genre_Drama             5278 non-null   int64
 33  genre_Ecchi             5278 non-null   int64
 34  genre_Fantasy           5278 non-null   int64
 35  genre_Gourmet           5278 non-null   int64
 36  genre_Horror            5278 non-null   int64
 37  genre_Mystery           5278 non-null   int64
 38  genre_Other             5278 non-null   int64
 39  genre_Romance           5278 non-null   int64
 40  genre_Sci-Fi            5278 non-null   int64
 41  genre_Slice_of_Life     5278 non-null   int64
 42  genre_Sports            5278 non-null   int64
 43  genre_Supernatural      5278 non-null   int64
 44  genre_Suspense          5278 non-null   int64
 45  theme_Adult_Cast        5278 non-null   int64
 46  theme_Anthropomorphic   5278 non-null   int64
 47  theme_CGDCT             5278 non-null   int64
 48  theme_Detective         5278 non-null   int64
 49  theme_Gag_Humor         5278 non-null   int64
 50  theme_Gore              5278 non-null   int64
 51  theme_Harem             5278 non-null   int64
 52  theme_Historical        5278 non-null   int64
 53  theme_Idols_(Female)    5278 non-null   int64
 54  theme_Isekai            5278 non-null   int64
 55  theme_Iyashikei         5278 non-null   int64
 56  theme_Love_Polygon      5278 non-null   int64
 57  theme_Mahou_Shoujo      5278 non-null   int64
 58  theme_Martial_Arts      5278 non-null   int64
 59  theme_Mecha             5278 non-null   int64
 60  theme_Military          5278 non-null   int64
 61  theme_Music             5278 non-null   int64
 62  theme_Mythology         5278 non-null   int64
 63  theme_Organized_Crime   5278 non-null   int64
 64  theme_Otaku_Culture     5278 non-null   int64
 65  theme_Other             5278 non-null   int64
 66  theme_Parody            5278 non-null   int64
 67  theme_Performing_Arts   5278 non-null   int64
 68  theme_Pets              5278 non-null   int64
 69  theme_Psychological     5278 non-null   int64
 70  theme_Racing            5278 non-null   int64
 71  theme_Reincarnation     5278 non-null   int64
 72  theme_Samurai           5278 non-null   int64
 73  theme_School            5278 non-null   int64
 74  theme_Space             5278 non-null   int64
 75  theme_Strategy_Game     5278 non-null   int64
 76  theme_Super_Power       5278 non-null   int64
 77  theme_Team_Sports       5278 non-null   int64
 78  theme_Time_Travel       5278 non-null   int64
 79  theme_Urban_Fantasy     5278 non-null   int64
 80  theme_Vampire           5278 non-null   int64
 81  theme_Workplace         5278 non-null   int64
 82  demo_Josei              5278 non-null   int64
 83  demo_Kids               5278 non-null   int64
 84  demo_Seinen             5278 non-null   int64
 85  demo_Shoujo             5278 non-null   int64
 86  demo_Shounen            5278 non-null   int64
dtypes: bool(2), float64(11), int64(65), object(5), str(4)
memory usage: 3.7+ MB
None
<class 'pandas.DataFrame'>
Index: 72 entries, 0 to 71
Data columns (total 87 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   mal_id                  72 non-null     int64
 1   title                   72 non-null     str
 2   producers               72 non-null     object
 3   genres                  72 non-null     object
 4   studios                 72 non-null     object
 5   demographics            72 non-null     object
 6   themes                  72 non-null     object
 7   rating                  31 non-null     str
 8   sequel                  72 non-null     bool
 9   members                 72 non-null     int64
 10  thumbnail               72 non-null     bool
 11  prequel_score           72 non-null     float64
 12  prequel_members         72 non-null     float64
 13  prequel_type            72 non-null     str
 14  cohort                  72 non-null     str
 15  drop_rate               62 non-null     float64
 16  wc_z                    72 non-null     float64
 17  forum_z                 72 non-null     float64
 18  favorites_z             72 non-null     float64
 19  score_z                 72 non-null     float64
 20  dropped_z               72 non-null     float64
 21  drop_rate_z             72 non-null     float64
 22  adaptation_score        72 non-null     float64
 23  adaptation_members      72 non-null     float64
 24  has_adaptation_score    72 non-null     int64
 25  has_adaptation_members  72 non-null     int64
 26  has_prequel_score       72 non-null     int64
 27  has_prequel_members     72 non-null     int64
 28  has_prequel_type        72 non-null     int64
 29  genre_Action            72 non-null     int64
 30  genre_Adventure         72 non-null     int64
 31  genre_Comedy            72 non-null     int64
 32  genre_Drama             72 non-null     int64
 33  genre_Ecchi             72 non-null     int64
 34  genre_Fantasy           72 non-null     int64
 35  genre_Gourmet           72 non-null     int64
 36  genre_Horror            72 non-null     int64
 37  genre_Mystery           72 non-null     int64
 38  genre_Other             72 non-null     int64
 39  genre_Romance           72 non-null     int64
 40  genre_Sci-Fi            72 non-null     int64
 41  genre_Slice_of_Life     72 non-null     int64
 42  genre_Sports            72 non-null     int64
 43  genre_Supernatural      72 non-null     int64
 44  genre_Suspense          72 non-null     int64
 45  theme_Adult_Cast        72 non-null     int64
 46  theme_Anthropomorphic   72 non-null     int64
 47  theme_CGDCT             72 non-null     int64
 48  theme_Detective         72 non-null     int64
 49  theme_Gag_Humor         72 non-null     int64
 50  theme_Gore              72 non-null     int64
 51  theme_Harem             72 non-null     int64
 52  theme_Historical        72 non-null     int64
 53  theme_Idols_(Female)    72 non-null     int64
 54  theme_Isekai            72 non-null     int64
 55  theme_Iyashikei         72 non-null     int64
 56  theme_Love_Polygon      72 non-null     int64
 57  theme_Mahou_Shoujo      72 non-null     int64
 58  theme_Martial_Arts      72 non-null     int64
 59  theme_Mecha             72 non-null     int64
 60  theme_Military          72 non-null     int64
 61  theme_Music             72 non-null     int64
 62  theme_Mythology         72 non-null     int64
 63  theme_Organized_Crime   72 non-null     int64
 64  theme_Otaku_Culture     72 non-null     int64
 65  theme_Other             72 non-null     int64
 66  theme_Parody            72 non-null     int64
 67  theme_Performing_Arts   72 non-null     int64
 68  theme_Pets              72 non-null     int64
 69  theme_Psychological     72 non-null     int64
 70  theme_Racing            72 non-null     int64
 71  theme_Reincarnation     72 non-null     int64
 72  theme_Samurai           72 non-null     int64
 73  theme_School            72 non-null     int64
 74  theme_Space             72 non-null     int64
 75  theme_Strategy_Game     72 non-null     int64
 76  theme_Super_Power       72 non-null     int64
 77  theme_Team_Sports       72 non-null     int64
 78  theme_Time_Travel       72 non-null     int64
 79  theme_Urban_Fantasy     72 non-null     int64
 80  theme_Vampire           72 non-null     int64
 81  theme_Workplace         72 non-null     int64
 82  demo_Josei              72 non-null     int64
 83  demo_Kids               72 non-null     int64
 84  demo_Seinen             72 non-null     int64
 85  demo_Shoujo             72 non-null     int64
 86  demo_Shounen            72 non-null     int64
dtypes: bool(2), float64(11), int64(65), object(5), str(4)
memory usage: 52.3+ KB
None

In [66]:
X_other_pre = df.drop(columns=['thumbnail', 'members', 'title', 'mal_id', 'cohort', 'producers', 'genres', 'studios', 'demographics', 'themes', 'score_z', 'wc_z', 'favorites_z', 'dropped_z', 'drop_rate', 'drop_rate_z', 'forum_z'])
X_other_pre = X_other_pre.reset_index(drop=True)
X_other_pre = pd.get_dummies(X_other_pre, columns=['rating'], dtype=int, drop_first=True)
X_other_pre = pd.get_dummies(X_other_pre, columns=['prequel_type'], dtype=int, drop_first=True)
X_other_pre['sequel'] = X_other_pre['sequel'].astype(int)
X_other_pre.columns = X_other_pre.columns.str.replace(' ', '_')
print(X_other_pre.info())

real_other_pre = real_df.drop(columns=['thumbnail', 'members', 'title',  'mal_id', 'cohort', 'producers', 'genres', 'studios', 'demographics', 'themes', 'score_z', 'wc_z', 'favorites_z', 'dropped_z', 'drop_rate', 'drop_rate_z','forum_z'])
real_other_pre = real_other_pre.reset_index(drop=True)
real_other_pre = pd.get_dummies(real_other_pre, columns=['rating'], dtype=int)
real_other_pre = pd.get_dummies(real_other_pre, columns=['prequel_type'], dtype=int)
real_other_pre['sequel'] = real_other_pre['sequel'].astype(int)
real_other_pre.columns = real_other_pre.columns.str.replace(' ', '_')
print(real_other_pre.info())

<class 'pandas.DataFrame'>
RangeIndex: 5278 entries, 0 to 5277
Data columns (total 80 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   sequel                                 5278 non-null   int64
 1   prequel_score                          5278 non-null   float64
 2   prequel_members                        5278 non-null   float64
 3   adaptation_score                       5278 non-null   float64
 4   adaptation_members                     5278 non-null   float64
 5   has_adaptation_score                   5278 non-null   int64
 6   has_adaptation_members                 5278 non-null   int64
 7   has_prequel_score                      5278 non-null   int64
 8   has_prequel_members                    5278 non-null   int64
 9   has_prequel_type                       5278 non-null   int64
 10  genre_Action                           5278 non-null   int64
 11  genre_Adventure                        5278 non-null   int64
 12  genre_Comedy                           5278 non-null   int64
 13  genre_Drama                            5278 non-null   int64
 14  genre_Ecchi                            5278 non-null   int64
 15  genre_Fantasy                          5278 non-null   int64
 16  genre_Gourmet                          5278 non-null   int64
 17  genre_Horror                           5278 non-null   int64
 18  genre_Mystery                          5278 non-null   int64
 19  genre_Other                            5278 non-null   int64
 20  genre_Romance                          5278 non-null   int64
 21  genre_Sci-Fi                           5278 non-null   int64
 22  genre_Slice_of_Life                    5278 non-null   int64
 23  genre_Sports                           5278 non-null   int64
 24  genre_Supernatural                     5278 non-null   int64
 25  genre_Suspense                         5278 non-null   int64
 26  theme_Adult_Cast                       5278 non-null   int64
 27  theme_Anthropomorphic                  5278 non-null   int64
 28  theme_CGDCT                            5278 non-null   int64
 29  theme_Detective                        5278 non-null   int64
 30  theme_Gag_Humor                        5278 non-null   int64
 31  theme_Gore                             5278 non-null   int64
 32  theme_Harem                            5278 non-null   int64
 33  theme_Historical                       5278 non-null   int64
 34  theme_Idols_(Female)                   5278 non-null   int64
 35  theme_Isekai                           5278 non-null   int64
 36  theme_Iyashikei                        5278 non-null   int64
 37  theme_Love_Polygon                     5278 non-null   int64
 38  theme_Mahou_Shoujo                     5278 non-null   int64
 39  theme_Martial_Arts                     5278 non-null   int64
 40  theme_Mecha                            5278 non-null   int64
 41  theme_Military                         5278 non-null   int64
 42  theme_Music                            5278 non-null   int64
 43  theme_Mythology                        5278 non-null   int64
 44  theme_Organized_Crime                  5278 non-null   int64
 45  theme_Otaku_Culture                    5278 non-null   int64
 46  theme_Other                            5278 non-null   int64
 47  theme_Parody                           5278 non-null   int64
 48  theme_Performing_Arts                  5278 non-null   int64
 49  theme_Pets                             5278 non-null   int64
 50  theme_Psychological                    5278 non-null   int64
 51  theme_Racing                           5278 non-null   int64
 52  theme_Reincarnation                    5278 non-null   int64
 53  theme_Samurai                          5278 non-null   int64
 54  theme_School                           5278 non-null   int64
 55  theme_Space                            5278 non-null   int64
 56  theme_Strategy_Game                    5278 non-null   int64
 57  theme_Super_Power                      5278 non-null   int64
 58  theme_Team_Sports                      5278 non-null   int64
 59  theme_Time_Travel                      5278 non-null   int64
 60  theme_Urban_Fantasy                    5278 non-null   int64
 61  theme_Vampire                          5278 non-null   int64
 62  theme_Workplace                        5278 non-null   int64
 63  demo_Josei                             5278 non-null   int64
 64  demo_Kids                              5278 non-null   int64
 65  demo_Seinen                            5278 non-null   int64
 66  demo_Shoujo                            5278 non-null   int64
 67  demo_Shounen                           5278 non-null   int64
 68  rating_PG_-_Children                   5278 non-null   int64
 69  rating_PG-13_-_Teens_13_or_older       5278 non-null   int64
 70  rating_R_-_17+_(violence_&_profanity)  5278 non-null   int64
 71  rating_R+_-_Mild_Nudity                5278 non-null   int64
 72  prequel_type_Movie                     5278 non-null   int64
 73  prequel_type_Music                     5278 non-null   int64
 74  prequel_type_ONA                       5278 non-null   int64
 75  prequel_type_OVA                       5278 non-null   int64
 76  prequel_type_PV                        5278 non-null   int64
 77  prequel_type_Special                   5278 non-null   int64
 78  prequel_type_TV                        5278 non-null   int64
 79  prequel_type_TV_Special                5278 non-null   int64
dtypes: float64(4), int64(76)
memory usage: 3.2 MB
None
<class 'pandas.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 74 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   sequel                                 72 non-null     int64
 1   prequel_score                          72 non-null     float64
 2   prequel_members                        72 non-null     float64
 3   adaptation_score                       72 non-null     float64
 4   adaptation_members                     72 non-null     float64
 5   has_adaptation_score                   72 non-null     int64
 6   has_adaptation_members                 72 non-null     int64
 7   has_prequel_score                      72 non-null     int64
 8   has_prequel_members                    72 non-null     int64
 9   has_prequel_type                       72 non-null     int64
 10  genre_Action                           72 non-null     int64
 11  genre_Adventure                        72 non-null     int64
 12  genre_Comedy                           72 non-null     int64
 13  genre_Drama                            72 non-null     int64
 14  genre_Ecchi                            72 non-null     int64
 15  genre_Fantasy                          72 non-null     int64
 16  genre_Gourmet                          72 non-null     int64
 17  genre_Horror                           72 non-null     int64
 18  genre_Mystery                          72 non-null     int64
 19  genre_Other                            72 non-null     int64
 20  genre_Romance                          72 non-null     int64
 21  genre_Sci-Fi                           72 non-null     int64
 22  genre_Slice_of_Life                    72 non-null     int64
 23  genre_Sports                           72 non-null     int64
 24  genre_Supernatural                     72 non-null     int64
 25  genre_Suspense                         72 non-null     int64
 26  theme_Adult_Cast                       72 non-null     int64
 27  theme_Anthropomorphic                  72 non-null     int64
 28  theme_CGDCT                            72 non-null     int64
 29  theme_Detective                        72 non-null     int64
 30  theme_Gag_Humor                        72 non-null     int64
 31  theme_Gore                             72 non-null     int64
 32  theme_Harem                            72 non-null     int64
 33  theme_Historical                       72 non-null     int64
 34  theme_Idols_(Female)                   72 non-null     int64
 35  theme_Isekai                           72 non-null     int64
 36  theme_Iyashikei                        72 non-null     int64
 37  theme_Love_Polygon                     72 non-null     int64
 38  theme_Mahou_Shoujo                     72 non-null     int64
 39  theme_Martial_Arts                     72 non-null     int64
 40  theme_Mecha                            72 non-null     int64
 41  theme_Military                         72 non-null     int64
 42  theme_Music                            72 non-null     int64
 43  theme_Mythology                        72 non-null     int64
 44  theme_Organized_Crime                  72 non-null     int64
 45  theme_Otaku_Culture                    72 non-null     int64
 46  theme_Other                            72 non-null     int64
 47  theme_Parody                           72 non-null     int64
 48  theme_Performing_Arts                  72 non-null     int64
 49  theme_Pets                             72 non-null     int64
 50  theme_Psychological                    72 non-null     int64
 51  theme_Racing                           72 non-null     int64
 52  theme_Reincarnation                    72 non-null     int64
 53  theme_Samurai                          72 non-null     int64
 54  theme_School                           72 non-null     int64
 55  theme_Space                            72 non-null     int64
 56  theme_Strategy_Game                    72 non-null     int64
 57  theme_Super_Power                      72 non-null     int64
 58  theme_Team_Sports                      72 non-null     int64
 59  theme_Time_Travel                      72 non-null     int64
 60  theme_Urban_Fantasy                    72 non-null     int64
 61  theme_Vampire                          72 non-null     int64
 62  theme_Workplace                        72 non-null     int64
 63  demo_Josei                             72 non-null     int64
 64  demo_Kids                              72 non-null     int64
 65  demo_Seinen                            72 non-null     int64
 66  demo_Shoujo                            72 non-null     int64
 67  demo_Shounen                           72 non-null     int64
 68  rating_G_-_All_Ages                    72 non-null     int64
 69  rating_PG_-_Children                   72 non-null     int64
 70  rating_PG-13_-_Teens_13_or_older       72 non-null     int64
 71  rating_R_-_17+_(violence_&_profanity)  72 non-null     int64
 72  prequel_type_                          72 non-null     int64
 73  prequel_type_TV                        72 non-null     int64
dtypes: float64(4), int64(70)
memory usage: 41.8 KB
None

### Multicollinearity Test

In [67]:
def safe_boolean_vif(df):
    zero_variance_cols = df.columns[df.nunique() <= 1].tolist()
    if zero_variance_cols:
        print(f"Dropped zero-variance columns immediately: {zero_variance_cols}")
        df = df.drop(columns=zero_variance_cols)
        
    X = df.copy()
    X['constant'] = 1.0
    
    vif_data = pd.DataFrame()
    vif_data["feature"] = X.columns
    
    vifs = []
    for i in range(len(X.columns)):
        try:
            val = variance_inflation_factor(X.values, i)
            vifs.append(np.inf if np.isinf(val) or np.isnan(val) else val)
        except ZeroDivisionError:
            vifs.append(np.inf)
            
    vif_data["VIF"] = vifs
    
    return vif_data[vif_data["feature"] != 'constant'].reset_index(drop=True)

In [68]:
vif_results = safe_boolean_vif(X_other_pre)
print("\nFinal VIF Data:")
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(vif_results)

c:\Users\14793\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

Final VIF Data:

                                  feature         VIF
0                                  sequel         inf
1                           prequel_score  124.938246
2                         prequel_members   46.686421
3                        adaptation_score    2.990360
4                      adaptation_members    6.216886
5                    has_adaptation_score    4.525568
6                  has_adaptation_members    2.593336
7                       has_prequel_score  173.857083
8                     has_prequel_members         inf
9                        has_prequel_type         inf
10                           genre_Action    1.727659
11                        genre_Adventure    1.368650
12                           genre_Comedy    1.628614
13                            genre_Drama    1.306657
14                            genre_Ecchi    1.677835
15                          genre_Fantasy    1.810299
16                          genre_Gourmet    1.047870
17                           genre_Horror    1.376166
18                          genre_Mystery    1.503155
19                            genre_Other    1.104701
20                          genre_Romance    1.636558
21                           genre_Sci-Fi    1.621175
22                    genre_Slice_of_Life    1.832059
23                           genre_Sports    2.018221
24                     genre_Supernatural    1.589195
25                         genre_Suspense    2.364085
26                       theme_Adult_Cast    1.301608
27                  theme_Anthropomorphic    1.052047
28                            theme_CGDCT    1.198553
29                        theme_Detective    1.308574
30                        theme_Gag_Humor    1.156604
31                             theme_Gore    1.344812
32                            theme_Harem    1.507364
33                       theme_Historical    1.344491
34                   theme_Idols_(Female)    1.523643
35                           theme_Isekai    1.501415
36                        theme_Iyashikei    1.547735
37                     theme_Love_Polygon    1.129789
38                     theme_Mahou_Shoujo    1.137045
39                     theme_Martial_Arts    1.125520
40                            theme_Mecha    1.587328
41                         theme_Military    1.188334
42                            theme_Music    1.633086
43                        theme_Mythology    1.271163
44                  theme_Organized_Crime    1.100147
45                    theme_Otaku_Culture    1.054573
46                            theme_Other    1.180716
47                           theme_Parody    1.155939
48                  theme_Performing_Arts    1.097376
49                             theme_Pets    1.165803
50                    theme_Psychological    2.173233
51                           theme_Racing    1.081103
52                    theme_Reincarnation    1.234619
53                          theme_Samurai    1.255097
54                           theme_School    1.389050
55                            theme_Space    1.235567
56                    theme_Strategy_Game    1.111098
57                      theme_Super_Power    1.112630
58                      theme_Team_Sports    1.807899
59                      theme_Time_Travel    1.031969
60                    theme_Urban_Fantasy    1.218381
61                          theme_Vampire    1.107546
62                        theme_Workplace    1.140883
63                             demo_Josei    1.095049
64                              demo_Kids    1.503726
65                            demo_Seinen    1.345301
66                            demo_Shoujo    1.254536
67                           demo_Shounen    1.525803
68                   rating_PG_-_Children    1.505835
69       rating_PG-13_-_Teens_13_or_older    3.069175
70  rating_R_-_17+_(violence_&_profanity)    2.781613
71                rating_R+_-_Mild_Nudity    2.106510
72                     prequel_type_Movie         inf
73                     prequel_type_Music         inf
74                       prequel_type_ONA         inf
75                       prequel_type_OVA         inf
76                        prequel_type_PV         inf
77                   prequel_type_Special         inf
78                        prequel_type_TV         inf
79                prequel_type_TV_Special         inf

We can infer the following:
1. We have to remove the "has_prequel" variables. The main worry is that the neural network won't be able to learn from the imputed zeroes. However, since a zero is extremely rare or impossible for prequel score and prequel members, this should not be a big issue.
2. Prequel types will ruin our feature importance reliability. We can turn this into a "prequel_type_tv" bool instead since the only prequel type in the inference data is TV.

In [69]:
X_other_pre = X_other_pre.drop(columns=['has_prequel_score', 'has_prequel_members', 'has_prequel_type', 'prequel_type_Movie', 'prequel_type_Music',
                                        'prequel_type_ONA', 'prequel_type_OVA', 'prequel_type_PV', 'prequel_type_Special', 'prequel_type_TV', 'prequel_type_TV_Special'])

real_other_pre = real_other_pre.drop(columns=['has_prequel_score', 'has_prequel_members', 'has_prequel_type', 'prequel_type_'])

X_other_pre["prequel_type_tv"] = (df['prequel_type'] == "TV").astype(int)

X_other_pre["prequel_type_tv"].describe()

count    5278.000000
mean        0.214475
std         0.410497
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: prequel_type_tv, dtype: float64

Now lets run VIF one more time.

In [70]:
vif_results = safe_boolean_vif(X_other_pre)
print("\nFinal VIF Data:")
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(vif_results)

Final VIF Data:

                                  feature        VIF
0                                  sequel  42.016975
1                           prequel_score  64.468171
2                         prequel_members  40.722750
3                        adaptation_score   2.940022
4                      adaptation_members   6.201957
5                    has_adaptation_score   4.517740
6                  has_adaptation_members   2.589171
7                            genre_Action   1.725098
8                         genre_Adventure   1.364706
9                            genre_Comedy   1.628285
10                            genre_Drama   1.302102
11                            genre_Ecchi   1.676812
12                          genre_Fantasy   1.803248
13                          genre_Gourmet   1.047667
14                           genre_Horror   1.371214
15                          genre_Mystery   1.500732
16                            genre_Other   1.103627
17                          genre_Romance   1.635518
18                           genre_Sci-Fi   1.620610
19                    genre_Slice_of_Life   1.831293
20                           genre_Sports   2.016823
21                     genre_Supernatural   1.588228
22                         genre_Suspense   2.360337
23                       theme_Adult_Cast   1.299718
24                  theme_Anthropomorphic   1.051422
25                            theme_CGDCT   1.196080
26                        theme_Detective   1.306993
27                        theme_Gag_Humor   1.153882
28                             theme_Gore   1.342282
29                            theme_Harem   1.503985
30                       theme_Historical   1.343773
31                   theme_Idols_(Female)   1.521850
32                           theme_Isekai   1.494506
33                        theme_Iyashikei   1.546336
34                     theme_Love_Polygon   1.128179
35                     theme_Mahou_Shoujo   1.136744
36                     theme_Martial_Arts   1.124681
37                            theme_Mecha   1.585328
38                         theme_Military   1.186552
39                            theme_Music   1.631901
40                        theme_Mythology   1.270153
41                  theme_Organized_Crime   1.100081
42                    theme_Otaku_Culture   1.053016
43                            theme_Other   1.179458
44                           theme_Parody   1.149238
45                  theme_Performing_Arts   1.097218
46                             theme_Pets   1.165638
47                    theme_Psychological   2.169799
48                           theme_Racing   1.080928
49                    theme_Reincarnation   1.233054
50                          theme_Samurai   1.253095
51                           theme_School   1.384888
52                            theme_Space   1.234175
53                    theme_Strategy_Game   1.108510
54                      theme_Super_Power   1.110500
55                      theme_Team_Sports   1.807699
56                      theme_Time_Travel   1.031509
57                    theme_Urban_Fantasy   1.212056
58                          theme_Vampire   1.104832
59                        theme_Workplace   1.137421
60                             demo_Josei   1.094221
61                              demo_Kids   1.494948
62                            demo_Seinen   1.343497
63                            demo_Shoujo   1.252665
64                           demo_Shounen   1.521445
65                   rating_PG_-_Children   1.504128
66       rating_PG-13_-_Teens_13_or_older   3.063761
67  rating_R_-_17+_(violence_&_profanity)   2.779068
68                rating_R+_-_Mild_Nudity   2.102299
69                        prequel_type_tv   4.789015

In [71]:
real_other_pre = real_other_pre.reindex(columns=X_other_pre.columns, fill_value=0)

print(X_other_pre.info())
print(real_other_pre.info())

<class 'pandas.DataFrame'>
RangeIndex: 5278 entries, 0 to 5277
Data columns (total 70 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   sequel                                 5278 non-null   int64
 1   prequel_score                          5278 non-null   float64
 2   prequel_members                        5278 non-null   float64
 3   adaptation_score                       5278 non-null   float64
 4   adaptation_members                     5278 non-null   float64
 5   has_adaptation_score                   5278 non-null   int64
 6   has_adaptation_members                 5278 non-null   int64
 7   genre_Action                           5278 non-null   int64
 8   genre_Adventure                        5278 non-null   int64
 9   genre_Comedy                           5278 non-null   int64
 10  genre_Drama                            5278 non-null   int64
 11  genre_Ecchi                            5278 non-null   int64
 12  genre_Fantasy                          5278 non-null   int64
 13  genre_Gourmet                          5278 non-null   int64
 14  genre_Horror                           5278 non-null   int64
 15  genre_Mystery                          5278 non-null   int64
 16  genre_Other                            5278 non-null   int64
 17  genre_Romance                          5278 non-null   int64
 18  genre_Sci-Fi                           5278 non-null   int64
 19  genre_Slice_of_Life                    5278 non-null   int64
 20  genre_Sports                           5278 non-null   int64
 21  genre_Supernatural                     5278 non-null   int64
 22  genre_Suspense                         5278 non-null   int64
 23  theme_Adult_Cast                       5278 non-null   int64
 24  theme_Anthropomorphic                  5278 non-null   int64
 25  theme_CGDCT                            5278 non-null   int64
 26  theme_Detective                        5278 non-null   int64
 27  theme_Gag_Humor                        5278 non-null   int64
 28  theme_Gore                             5278 non-null   int64
 29  theme_Harem                            5278 non-null   int64
 30  theme_Historical                       5278 non-null   int64
 31  theme_Idols_(Female)                   5278 non-null   int64
 32  theme_Isekai                           5278 non-null   int64
 33  theme_Iyashikei                        5278 non-null   int64
 34  theme_Love_Polygon                     5278 non-null   int64
 35  theme_Mahou_Shoujo                     5278 non-null   int64
 36  theme_Martial_Arts                     5278 non-null   int64
 37  theme_Mecha                            5278 non-null   int64
 38  theme_Military                         5278 non-null   int64
 39  theme_Music                            5278 non-null   int64
 40  theme_Mythology                        5278 non-null   int64
 41  theme_Organized_Crime                  5278 non-null   int64
 42  theme_Otaku_Culture                    5278 non-null   int64
 43  theme_Other                            5278 non-null   int64
 44  theme_Parody                           5278 non-null   int64
 45  theme_Performing_Arts                  5278 non-null   int64
 46  theme_Pets                             5278 non-null   int64
 47  theme_Psychological                    5278 non-null   int64
 48  theme_Racing                           5278 non-null   int64
 49  theme_Reincarnation                    5278 non-null   int64
 50  theme_Samurai                          5278 non-null   int64
 51  theme_School                           5278 non-null   int64
 52  theme_Space                            5278 non-null   int64
 53  theme_Strategy_Game                    5278 non-null   int64
 54  theme_Super_Power                      5278 non-null   int64
 55  theme_Team_Sports                      5278 non-null   int64
 56  theme_Time_Travel                      5278 non-null   int64
 57  theme_Urban_Fantasy                    5278 non-null   int64
 58  theme_Vampire                          5278 non-null   int64
 59  theme_Workplace                        5278 non-null   int64
 60  demo_Josei                             5278 non-null   int64
 61  demo_Kids                              5278 non-null   int64
 62  demo_Seinen                            5278 non-null   int64
 63  demo_Shoujo                            5278 non-null   int64
 64  demo_Shounen                           5278 non-null   int64
 65  rating_PG_-_Children                   5278 non-null   int64
 66  rating_PG-13_-_Teens_13_or_older       5278 non-null   int64
 67  rating_R_-_17+_(violence_&_profanity)  5278 non-null   int64
 68  rating_R+_-_Mild_Nudity                5278 non-null   int64
 69  prequel_type_tv                        5278 non-null   int64
dtypes: float64(4), int64(66)
memory usage: 2.8 MB
None
<class 'pandas.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 70 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   sequel                                 72 non-null     int64
 1   prequel_score                          72 non-null     float64
 2   prequel_members                        72 non-null     float64
 3   adaptation_score                       72 non-null     float64
 4   adaptation_members                     72 non-null     float64
 5   has_adaptation_score                   72 non-null     int64
 6   has_adaptation_members                 72 non-null     int64
 7   genre_Action                           72 non-null     int64
 8   genre_Adventure                        72 non-null     int64
 9   genre_Comedy                           72 non-null     int64
 10  genre_Drama                            72 non-null     int64
 11  genre_Ecchi                            72 non-null     int64
 12  genre_Fantasy                          72 non-null     int64
 13  genre_Gourmet                          72 non-null     int64
 14  genre_Horror                           72 non-null     int64
 15  genre_Mystery                          72 non-null     int64
 16  genre_Other                            72 non-null     int64
 17  genre_Romance                          72 non-null     int64
 18  genre_Sci-Fi                           72 non-null     int64
 19  genre_Slice_of_Life                    72 non-null     int64
 20  genre_Sports                           72 non-null     int64
 21  genre_Supernatural                     72 non-null     int64
 22  genre_Suspense                         72 non-null     int64
 23  theme_Adult_Cast                       72 non-null     int64
 24  theme_Anthropomorphic                  72 non-null     int64
 25  theme_CGDCT                            72 non-null     int64
 26  theme_Detective                        72 non-null     int64
 27  theme_Gag_Humor                        72 non-null     int64
 28  theme_Gore                             72 non-null     int64
 29  theme_Harem                            72 non-null     int64
 30  theme_Historical                       72 non-null     int64
 31  theme_Idols_(Female)                   72 non-null     int64
 32  theme_Isekai                           72 non-null     int64
 33  theme_Iyashikei                        72 non-null     int64
 34  theme_Love_Polygon                     72 non-null     int64
 35  theme_Mahou_Shoujo                     72 non-null     int64
 36  theme_Martial_Arts                     72 non-null     int64
 37  theme_Mecha                            72 non-null     int64
 38  theme_Military                         72 non-null     int64
 39  theme_Music                            72 non-null     int64
 40  theme_Mythology                        72 non-null     int64
 41  theme_Organized_Crime                  72 non-null     int64
 42  theme_Otaku_Culture                    72 non-null     int64
 43  theme_Other                            72 non-null     int64
 44  theme_Parody                           72 non-null     int64
 45  theme_Performing_Arts                  72 non-null     int64
 46  theme_Pets                             72 non-null     int64
 47  theme_Psychological                    72 non-null     int64
 48  theme_Racing                           72 non-null     int64
 49  theme_Reincarnation                    72 non-null     int64
 50  theme_Samurai                          72 non-null     int64
 51  theme_School                           72 non-null     int64
 52  theme_Space                            72 non-null     int64
 53  theme_Strategy_Game                    72 non-null     int64
 54  theme_Super_Power                      72 non-null     int64
 55  theme_Team_Sports                      72 non-null     int64
 56  theme_Time_Travel                      72 non-null     int64
 57  theme_Urban_Fantasy                    72 non-null     int64
 58  theme_Vampire                          72 non-null     int64
 59  theme_Workplace                        72 non-null     int64
 60  demo_Josei                             72 non-null     int64
 61  demo_Kids                              72 non-null     int64
 62  demo_Seinen                            72 non-null     int64
 63  demo_Shoujo                            72 non-null     int64
 64  demo_Shounen                           72 non-null     int64
 65  rating_PG_-_Children                   72 non-null     int64
 66  rating_PG-13_-_Teens_13_or_older       72 non-null     int64
 67  rating_R_-_17+_(violence_&_profanity)  72 non-null     int64
 68  rating_R+_-_Mild_Nudity                72 non-null     int64
 69  prequel_type_tv                        72 non-null     int64
dtypes: float64(4), int64(66)
memory usage: 39.5 KB
None

In [72]:
assert list(X_other_pre.columns) == list(real_other_pre.columns), \
    set(X_other_pre.columns) ^ set(real_other_pre.columns)

## Baseline Model (Random Forest)

In [25]:
cols = ['score_z', 'wc_z', 'favorites_z', 'dropped_z', 'forum_z']

In [21]:
def multi_rf(X, y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    param_distributions = {
        'n_estimators':[150, 250, 400],
        'max_features': ['sqrt', 0.2, 0.3, 0.4],            
        'max_depth': [10, 15, 20, 25, None],                 
        'min_samples_split':[4, 6, 8],                  
        'min_samples_leaf': [2, 3, 4, 6]                     
    }

    rf_random_search = RandomizedSearchCV(
        estimator=RandomForestRegressor(random_state=42),
        param_distributions=param_distributions,
        n_iter=30,
        cv=5,
        scoring='neg_mean_squared_error',
        verbose=3,
        random_state=42,
        n_jobs=-1
    )

    print("Starting hyperparameter tuning...")
    rf_random_search.fit(X_train, y_train)

    print("\n--- Tuning Complete ---")
    print("Best Hyperparameters Found:", rf_random_search.best_params_)
    best_rf_model = rf_random_search.best_estimator_
    y_pred = best_rf_model.predict(X_test)

    mse_per_target = mean_squared_error(y_test, y_pred, multioutput='raw_values')
    r2_per_target = r2_score(y_test, y_pred, multioutput='raw_values')

    print("\n--- Test Set Evaluation Per Target ---")
    for i in range(y_test.shape[1]):
        print(f"Target {i+1} -> MSE: {mse_per_target[i]:.4f} | R² Score: {r2_per_target[i]:.4f}")

In [22]:
multi_rf(X_other_pre, df[cols])

Starting hyperparameter tuning...
Fitting 5 folds for each of 30 candidates, totalling 150 fits

--- Tuning Complete ---
Best Hyperparameters Found: {'n_estimators': 250, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 0.2, 'max_depth': 20}

--- Test Set Evaluation Per Target ---
Target 1 -> MSE: 0.4429 | R² Score: 0.5262
Target 2 -> MSE: 0.3282 | R² Score: 0.6355
Target 3 -> MSE: 0.3434 | R² Score: 0.6229
Target 4 -> MSE: 0.3673 | R² Score: 0.5991
Target 5 -> MSE: 0.4502 | R² Score: 0.5147

## Improved Model (XGBoost)

In [73]:
def xgboost(X, y, col):
    X_full_train, X_test, y_full_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    X_train, X_val, y_train, y_val = train_test_split(X_full_train, y_full_train, test_size=0.1, random_state=42)

    split_index = [-1] * len(X_train) + [0] * len(X_val)
    pds = PredefinedSplit(test_fold=split_index)

    X_search_g = cp.asarray(np.vstack((X_train, X_val)))
    y_search_g = cp.asarray(np.concatenate((y_train, y_val)))

    X_train_g = cp.asarray(X_train)
    y_train_g = cp.asarray(y_train)
    X_val_g = cp.asarray(X_val)
    y_val_g = cp.asarray(y_val)
    X_test_g = cp.asarray(X_test)

    param_distributions = {
    'n_estimators': [500, 1000, 1500, 2000, 3000],
    'learning_rate': [0.01, 0.02, 0.05, 0.1],
    'max_depth': [2, 3, 4, 5, 6, 8],
    'min_child_weight': [1, 3, 5, 7, 10],
    'subsample': [0.6, 0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.5, 0.7, 0.8, 0.9, 1.0],
    'gamma': [0, 0.01, 0.1, 0.5, 1],
    'reg_alpha': [0, 0.01, 0.1, 1, 10],
    'reg_lambda': [0.1, 1, 5, 10, 20],
    'tree_method': ['hist'] 
    }

    xgb_random_search = RandomizedSearchCV(
        estimator=XGBRegressor(
            device="cuda",
            random_state=42,
            eval_metric='rmse'
        ),
        param_distributions=param_distributions,
        n_iter=50,
        cv=pds,
        scoring='neg_mean_squared_error',
        verbose=2,
        random_state=42,
        n_jobs=1
    )

    xgb_random_search.fit(X_search_g, y_search_g)

    best_params = xgb_random_search.best_params_
    print("\n--- Tuning Complete ---")
    print("Best Hyperparameters Found:", best_params)

    best_xgb_model = XGBRegressor(
        **best_params,
        device="cuda",
        random_state=42,
        eval_metric='rmse',
        early_stopping_rounds=15
    )

    best_xgb_model.fit(
        X_train_g,
        y_train_g,
        eval_set=[(X_val_g, y_val_g)],
        verbose=100
    )

    y_pred_gpu = best_xgb_model.predict(X_test_g)
    y_pred_cpu = cp.asnumpy(y_pred_gpu)

    mse_per_target = mean_squared_error(y_test, y_pred_cpu)
    r2_per_target = r2_score(y_test, y_pred_cpu)

    print(f"Target {col} -> MSE: {mse_per_target:.4f} | R² Score: {r2_per_target:.4f}")

In [74]:
for col in cols:   
    print(f"Current column: {col}")
    xgboost(X_other_pre, df[col], col)

Current column: score_z
Fitting 1 folds for each of 50 candidates, totalling 50 fits
[CV] END colsample_bytree=0.5, gamma=0.01, learning_rate=0.05, max_depth=5, min_child_weight=1, n_estimators=500, reg_alpha=1, reg_lambda=1, subsample=0.9, tree_method=hist; total time=   1.4s
[CV] END colsample_bytree=0.7, gamma=0.5, learning_rate=0.1, max_depth=6, min_child_weight=7, n_estimators=3000, reg_alpha=0.01, reg_lambda=1, subsample=0.6, tree_method=hist; total time=   4.2s
[CV] END colsample_bytree=0.5, gamma=0.01, learning_rate=0.1, max_depth=2, min_child_weight=3, n_estimators=500, reg_alpha=0.1, reg_lambda=1, subsample=0.8, tree_method=hist; total time=   0.6s
[CV] END colsample_bytree=0.9, gamma=0.5, learning_rate=0.1, max_depth=4, min_child_weight=7, n_estimators=500, reg_alpha=0.01, reg_lambda=5, subsample=1.0, tree_method=hist; total time=   0.5s
[CV] END colsample_bytree=0.5, gamma=0.5, learning_rate=0.02, max_depth=6, min_child_weight=10, n_estimators=2000, reg_alpha=0.1, reg_lambda=0.1, subsample=0.9, tree_method=hist; total time=   2.6s
[CV] END colsample_bytree=1.0, gamma=0.1, learning_rate=0.05, max_depth=3, min_child_weight=7, n_estimators=1000, reg_alpha=10, reg_lambda=10, subsample=0.9, tree_method=hist; total time=   1.1s
[CV] END colsample_bytree=0.5, gamma=0.01, learning_rate=0.02, max_depth=8, min_child_weight=3, n_estimators=1500, reg_alpha=0, reg_lambda=10, subsample=0.9, tree_method=hist; total time=   5.5s
[CV] END colsample_bytree=0.7, gamma=1, learning_rate=0.1, max_depth=2, min_child_weight=3, n_estimators=1500, reg_alpha=0.1, reg_lambda=1, subsample=0.6, tree_method=hist; total time=   1.4s
[CV] END colsample_bytree=0.8, gamma=1, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=1500, reg_alpha=1, reg_lambda=5, subsample=0.8, tree_method=hist; total time=   1.5s
[CV] END colsample_bytree=0.5, gamma=0.01, learning_rate=0.1, max_depth=3, min_child_weight=10, n_estimators=2000, reg_alpha=1, reg_lambda=5, subsample=0.8, tree_method=hist; total time=   3.0s
[CV] END colsample_bytree=0.8, gamma=0.5, learning_rate=0.02, max_depth=3, min_child_weight=10, n_estimators=3000, reg_alpha=0, reg_lambda=10, subsample=0.6, tree_method=hist; total time=   4.3s
[CV] END colsample_bytree=1.0, gamma=0, learning_rate=0.1, max_depth=6, min_child_weight=5, n_estimators=500, reg_alpha=0, reg_lambda=1, subsample=0.7, tree_method=hist; total time=   1.4s
[CV] END colsample_bytree=0.9, gamma=0, learning_rate=0.01, max_depth=5, min_child_weight=5, n_estimators=2000, reg_alpha=0.1, reg_lambda=20, subsample=1.0, tree_method=hist; total time=   4.4s
[CV] END colsample_bytree=0.8, gamma=0.1, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=1500, reg_alpha=0, reg_lambda=1, subsample=0.7, tree_method=hist; total time=   4.0s
[CV] END colsample_bytree=0.5, gamma=0.1, learning_rate=0.02, max_depth=4, min_child_weight=1, n_estimators=1000, reg_alpha=1, reg_lambda=0.1, subsample=0.9, tree_method=hist; total time=   1.7s
[CV] END colsample_bytree=0.9, gamma=0.01, learning_rate=0.05, max_depth=2, min_child_weight=7, n_estimators=3000, reg_alpha=0.01, reg_lambda=5, subsample=0.7, tree_method=hist; total time=   3.2s
[CV] END colsample_bytree=0.5, gamma=0.5, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=500, reg_alpha=0.01, reg_lambda=10, subsample=0.8, tree_method=hist; total time=   0.9s
[CV] END colsample_bytree=0.5, gamma=0, learning_rate=0.05, max_depth=3, min_child_weight=1, n_estimators=2000, reg_alpha=1, reg_lambda=10, subsample=0.6, tree_method=hist; total time=   2.9s
[CV] END colsample_bytree=0.5, gamma=1, learning_rate=0.02, max_depth=5, min_child_weight=3, n_estimators=3000, reg_alpha=10, reg_lambda=10, subsample=0.6, tree_method=hist; total time=   3.2s
[CV] END colsample_bytree=0.8, gamma=1, learning_rate=0.1, max_depth=4, min_child_weight=3, n_estimators=1500, reg_alpha=0, reg_lambda=20, subsample=0.7, tree_method=hist; total time=   1.6s
[CV] END colsample_bytree=0.8, gamma=0, learning_rate=0.02, max_depth=8, min_child_weight=10, n_estimators=1500, reg_alpha=1, reg_lambda=0.1, subsample=0.7, tree_method=hist; total time=   5.6s
[CV] END colsample_bytree=0.9, gamma=0.5, learning_rate=0.02, max_depth=2, min_child_weight=5, n_estimators=2000, reg_alpha=1, reg_lambda=1, subsample=0.6, tree_method=hist; total time=   2.2s
[CV] END colsample_bytree=1.0, gamma=0.5, learning_rate=0.05, max_depth=3, min_child_weight=5, n_estimators=500, reg_alpha=0, reg_lambda=10, subsample=0.7, tree_method=hist; total time=   0.6s
[CV] END colsample_bytree=0.5, gamma=1, learning_rate=0.02, max_depth=4, min_child_weight=7, n_estimators=1000, reg_alpha=0.1, reg_lambda=10, subsample=1.0, tree_method=hist; total time=   1.1s
[CV] END colsample_bytree=1.0, gamma=1, learning_rate=0.02, max_depth=4, min_child_weight=1, n_estimators=3000, reg_alpha=0.1, reg_lambda=20, subsample=0.9, tree_method=hist; total time=   2.6s
[CV] END colsample_bytree=0.9, gamma=0.01, learning_rate=0.05, max_depth=5, min_child_weight=3, n_estimators=500, reg_alpha=10, reg_lambda=10, subsample=0.8, tree_method=hist; total time=   1.1s
[CV] END colsample_bytree=0.8, gamma=0, learning_rate=0.05, max_depth=3, min_child_weight=3, n_estimators=2000, reg_alpha=10, reg_lambda=10, subsample=0.9, tree_method=hist; total time=   2.7s
[CV] END colsample_bytree=0.5, gamma=0.01, learning_rate=0.02, max_depth=5, min_child_weight=1, n_estimators=1000, reg_alpha=10, reg_lambda=1, subsample=0.6, tree_method=hist; total time=   2.1s
[CV] END colsample_bytree=0.9, gamma=0.1, learning_rate=0.01, max_depth=4, min_child_weight=10, n_estimators=3000, reg_alpha=10, reg_lambda=20, subsample=0.8, tree_method=hist; total time=   5.1s
[CV] END colsample_bytree=0.9, gamma=0.01, learning_rate=0.1, max_depth=4, min_child_weight=1, n_estimators=1500, reg_alpha=0, reg_lambda=0.1, subsample=0.8, tree_method=hist; total time=   2.8s
[CV] END colsample_bytree=0.5, gamma=0.1, learning_rate=0.02, max_depth=8, min_child_weight=1, n_estimators=2000, reg_alpha=0.01, reg_lambda=0.1, subsample=1.0, tree_method=hist; total time=   3.0s
[CV] END colsample_bytree=0.9, gamma=0.5, learning_rate=0.05, max_depth=4, min_child_weight=7, n_estimators=2000, reg_alpha=0.01, reg_lambda=0.1, subsample=0.6, tree_method=hist; total time=   2.9s
[CV] END colsample_bytree=0.9, gamma=1, learning_rate=0.05, max_depth=4, min_child_weight=5, n_estimators=2000, reg_alpha=10, reg_lambda=5, subsample=0.6, tree_method=hist; total time=   1.9s
[CV] END colsample_bytree=0.8, gamma=0.5, learning_rate=0.01, max_depth=6, min_child_weight=7, n_estimators=500, reg_alpha=0.1, reg_lambda=5, subsample=0.7, tree_method=hist; total time=   1.2s
[CV] END colsample_bytree=0.9, gamma=0.1, learning_rate=0.02, max_depth=6, min_child_weight=3, n_estimators=2000, reg_alpha=10, reg_lambda=20, subsample=0.7, tree_method=hist; total time=   4.2s
[CV] END colsample_bytree=0.7, gamma=0.01, learning_rate=0.02, max_depth=8, min_child_weight=5, n_estimators=3000, reg_alpha=10, reg_lambda=1, subsample=0.8, tree_method=hist; total time=   7.9s
[CV] END colsample_bytree=0.8, gamma=0.1, learning_rate=0.01, max_depth=8, min_child_weight=5, n_estimators=1000, reg_alpha=0.01, reg_lambda=10, subsample=0.6, tree_method=hist; total time=   3.6s
[CV] END colsample_bytree=1.0, gamma=0, learning_rate=0.05, max_depth=5, min_child_weight=7, n_estimators=500, reg_alpha=0, reg_lambda=5, subsample=0.8, tree_method=hist; total time=   1.0s
[CV] END colsample_bytree=0.5, gamma=0.1, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=2000, reg_alpha=10, reg_lambda=1, subsample=0.6, tree_method=hist; total time=   3.4s
[CV] END colsample_bytree=0.9, gamma=1, learning_rate=0.01, max_depth=4, min_child_weight=7, n_estimators=1000, reg_alpha=0, reg_lambda=1, subsample=0.8, tree_method=hist; total time=   1.7s
[CV] END colsample_bytree=0.9, gamma=0, learning_rate=0.1, max_depth=8, min_child_weight=3, n_estimators=3000, reg_alpha=1, reg_lambda=0.1, subsample=1.0, tree_method=hist; total time=   4.0s
[CV] END colsample_bytree=0.7, gamma=0.5, learning_rate=0.05, max_depth=8, min_child_weight=5, n_estimators=2000, reg_alpha=0.1, reg_lambda=5, subsample=0.7, tree_method=hist; total time=   2.8s
[CV] END colsample_bytree=0.7, gamma=0.1, learning_rate=0.01, max_depth=2, min_child_weight=7, n_estimators=1000, reg_alpha=0.01, reg_lambda=5, subsample=0.6, tree_method=hist; total time=   1.1s
[CV] END colsample_bytree=0.7, gamma=0.5, learning_rate=0.05, max_depth=5, min_child_weight=5, n_estimators=500, reg_alpha=0, reg_lambda=10, subsample=0.9, tree_method=hist; total time=   0.8s
[CV] END colsample_bytree=1.0, gamma=0, learning_rate=0.01, max_depth=2, min_child_weight=3, n_estimators=1500, reg_alpha=0.1, reg_lambda=10, subsample=0.8, tree_method=hist; total time=   1.5s
[CV] END colsample_bytree=0.5, gamma=0, learning_rate=0.1, max_depth=5, min_child_weight=1, n_estimators=500, reg_alpha=10, reg_lambda=0.1, subsample=0.6, tree_method=hist; total time=   1.0s
[CV] END colsample_bytree=0.9, gamma=0, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=2000, reg_alpha=0.1, reg_lambda=1, subsample=0.8, tree_method=hist; total time=  10.8s
[CV] END colsample_bytree=0.5, gamma=0.01, learning_rate=0.01, max_depth=5, min_child_weight=1, n_estimators=1500, reg_alpha=0.01, reg_lambda=0.1, subsample=1.0, tree_method=hist; total time=   3.3s
[CV] END colsample_bytree=0.8, gamma=0.1, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=1000, reg_alpha=0.01, reg_lambda=0.1, subsample=0.8, tree_method=hist; total time=   2.9s
[CV] END colsample_bytree=0.7, gamma=0.1, learning_rate=0.1, max_depth=5, min_child_weight=3, n_estimators=2000, reg_alpha=1, reg_lambda=20, subsample=0.9, tree_method=hist; total time=   3.1s

--- Tuning Complete ---
Best Hyperparameters Found: {'tree_method': 'hist', 'subsample': 0.8, 'reg_lambda': 10, 'reg_alpha': 10, 'n_estimators': 500, 'min_child_weight': 3, 'max_depth': 5, 'learning_rate': 0.05, 'gamma': 0.01, 'colsample_bytree': 0.9}
[0]	validation_0-rmse:1.00736
[100]	validation_0-rmse:0.73245
[200]	validation_0-rmse:0.72270
[259]	validation_0-rmse:0.72090
Target score_z -> MSE: 0.4324 | R² Score: 0.5375
Current column: wc_z
Fitting 1 folds for each of 50 candidates, totalling 50 fits
[CV] END colsample_bytree=0.5, gamma=0.01, learning_rate=0.05, max_depth=5, min_child_weight=1, n_estimators=500, reg_alpha=1, reg_lambda=1, subsample=0.9, tree_method=hist; total time=   1.1s
[CV] END colsample_bytree=0.7, gamma=0.5, learning_rate=0.1, max_depth=6, min_child_weight=7, n_estimators=3000, reg_alpha=0.01, reg_lambda=1, subsample=0.6, tree_method=hist; total time=   3.8s
[CV] END colsample_bytree=0.5, gamma=0.01, learning_rate=0.1, max_depth=2, min_child_weight=3, n_estimators=500, reg_alpha=0.1, reg_lambda=1, subsample=0.8, tree_method=hist; total time=   0.5s
[CV] END colsample_bytree=0.9, gamma=0.5, learning_rate=0.1, max_depth=4, min_child_weight=7, n_estimators=500, reg_alpha=0.01, reg_lambda=5, subsample=1.0, tree_method=hist; total time=   0.5s
[CV] END colsample_bytree=0.5, gamma=0.5, learning_rate=0.02, max_depth=6, min_child_weight=10, n_estimators=2000, reg_alpha=0.1, reg_lambda=0.1, subsample=0.9, tree_method=hist; total time=   2.6s
[CV] END colsample_bytree=1.0, gamma=0.1, learning_rate=0.05, max_depth=3, min_child_weight=7, n_estimators=1000, reg_alpha=10, reg_lambda=10, subsample=0.9, tree_method=hist; total time=   1.1s
[CV] END colsample_bytree=0.5, gamma=0.01, learning_rate=0.02, max_depth=8, min_child_weight=3, n_estimators=1500, reg_alpha=0, reg_lambda=10, subsample=0.9, tree_method=hist; total time=   6.1s
[CV] END colsample_bytree=0.7, gamma=1, learning_rate=0.1, max_depth=2, min_child_weight=3, n_estimators=1500, reg_alpha=0.1, reg_lambda=1, subsample=0.6, tree_method=hist; total time=   1.4s
[CV] END colsample_bytree=0.8, gamma=1, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=1500, reg_alpha=1, reg_lambda=5, subsample=0.8, tree_method=hist; total time=   1.6s
[CV] END colsample_bytree=0.5, gamma=0.01, learning_rate=0.1, max_depth=3, min_child_weight=10, n_estimators=2000, reg_alpha=1, reg_lambda=5, subsample=0.8, tree_method=hist; total time=   3.0s
[CV] END colsample_bytree=0.8, gamma=0.5, learning_rate=0.02, max_depth=3, min_child_weight=10, n_estimators=3000, reg_alpha=0, reg_lambda=10, subsample=0.6, tree_method=hist; total time=   4.5s
[CV] END colsample_bytree=1.0, gamma=0, learning_rate=0.1, max_depth=6, min_child_weight=5, n_estimators=500, reg_alpha=0, reg_lambda=1, subsample=0.7, tree_method=hist; total time=   1.4s
[CV] END colsample_bytree=0.9, gamma=0, learning_rate=0.01, max_depth=5, min_child_weight=5, n_estimators=2000, reg_alpha=0.1, reg_lambda=20, subsample=1.0, tree_method=hist; total time=   4.9s
[CV] END colsample_bytree=0.8, gamma=0.1, learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=1500, reg_alpha=0, reg_lambda=1, subsample=0.7, tree_method=hist; total time=   3.9s
[CV] END colsample_bytree=0.5, gamma=0.1, learning_rate=0.02, max_depth=4, min_child_weight=1, n_estimators=1000, reg_alpha=1, reg_lambda=0.1, subsample=0.9, tree_method=hist; total time=   1.6s
[CV] END colsample_bytree=0.9, gamma=0.01, learning_rate=0.05, max_depth=2, min_child_weight=7, n_estimators=3000, reg_alpha=0.01, reg_lambda=5, subsample=0.7, tree_method=hist; total time=   4.0s
[CV] END colsample_bytree=0.5, gamma=0.5, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=500, reg_alpha=0.01, reg_lambda=10, subsample=0.8, tree_method=hist; total time=   1.0s
[CV] END colsample_bytree=0.5, gamma=0, learning_rate=0.05, max_depth=3, min_child_weight=1, n_estimators=2000, reg_alpha=1, reg_lambda=10, subsample=0.6, tree_method=hist; total time=   3.2s
[CV] END colsample_bytree=0.5, gamma=1, learning_rate=0.02, max_depth=5, min_child_weight=3, n_estimators=3000, reg_alpha=10, reg_lambda=10, subsample=0.6, tree_method=hist; total time=   3.3s
[CV] END colsample_bytree=0.8, gamma=1, learning_rate=0.1, max_depth=4, min_child_weight=3, n_estimators=1500, reg_alpha=0, reg_lambda=20, subsample=0.7, tree_method=hist; total time=   1.4s
[CV] END colsample_bytree=0.8, gamma=0, learning_rate=0.02, max_depth=8, min_child_weight=10, n_estimators=1500, reg_alpha=1, reg_lambda=0.1, subsample=0.7, tree_method=hist; total time=   5.5s
[CV] END colsample_bytree=0.9, gamma=0.5, learning_rate=0.02, max_depth=2, min_child_weight=5, n_estimators=2000, reg_alpha=1, reg_lambda=1, subsample=0.6, tree_method=hist; total time=   2.2s
[CV] END colsample_bytree=1.0, gamma=0.5, learning_rate=0.05, max_depth=3, min_child_weight=5, n_estimators=500, reg_alpha=0, reg_lambda=10, subsample=0.7, tree_method=hist; total time=   0.6s
[CV] END colsample_bytree=0.5, gamma=1, learning_rate=0.02, max_depth=4, min_child_weight=7, n_estimators=1000, reg_alpha=0.1, reg_lambda=10, subsample=1.0, tree_method=hist; total time=   1.2s
[CV] END colsample_bytree=1.0, gamma=1, learning_rate=0.02, max_depth=4, min_child_weight=1, n_estimators=3000, reg_alpha=0.1, reg_lambda=20, subsample=0.9, tree_method=hist; total time=   2.8s
[CV] END colsample_bytree=0.9, gamma=0.01, learning_rate=0.05, max_depth=5, min_child_weight=3, n_estimators=500, reg_alpha=10, reg_lambda=10, subsample=0.8, tree_method=hist; total time=   1.1s
[CV] END colsample_bytree=0.8, gamma=0, learning_rate=0.05, max_depth=3, min_child_weight=3, n_estimators=2000, reg_alpha=10, reg_lambda=10, subsample=0.9, tree_method=hist; total time=   2.7s
[CV] END colsample_bytree=0.5, gamma=0.01, learning_rate=0.02, max_depth=5, min_child_weight=1, n_estimators=1000, reg_alpha=10, reg_lambda=1, subsample=0.6, tree_method=hist; total time=   2.0s
[CV] END colsample_bytree=0.9, gamma=0.1, learning_rate=0.01, max_depth=4, min_child_weight=10, n_estimators=3000, reg_alpha=10, reg_lambda=20, subsample=0.8, tree_method=hist; total time=   4.6s
[CV] END colsample_bytree=0.9, gamma=0.01, learning_rate=0.1, max_depth=4, min_child_weight=1, n_estimators=1500, reg_alpha=0, reg_lambda=0.1, subsample=0.8, tree_method=hist; total time=   2.8s
[CV] END colsample_bytree=0.5, gamma=0.1, learning_rate=0.02, max_depth=8, min_child_weight=1, n_estimators=2000, reg_alpha=0.01, reg_lambda=0.1, subsample=1.0, tree_method=hist; total time=   3.0s
[CV] END colsample_bytree=0.9, gamma=0.5, learning_rate=0.05, max_depth=4, min_child_weight=7, n_estimators=2000, reg_alpha=0.01, reg_lambda=0.1, subsample=0.6, tree_method=hist; total time=   2.7s
[CV] END colsample_bytree=0.9, gamma=1, learning_rate=0.05, max_depth=4, min_child_weight=5, n_estimators=2000, reg_alpha=10, reg_lambda=5, subsample=0.6, tree_method=hist; total time=   1.8s
[CV] END colsample_bytree=0.8, gamma=0.5, learning_rate=0.01, max_depth=6, min_child_weight=7, n_estimators=500, reg_alpha=0.1, reg_lambda=5, subsample=0.7, tree_method=hist; total time=   1.1s
[CV] END colsample_bytree=0.9, gamma=0.1, learning_rate=0.02, max_depth=6, min_child_weight=3, n_estimators=2000, reg_alpha=10, reg_lambda=20, subsample=0.7, tree_method=hist; total time=   3.6s
[CV] END colsample_bytree=0.7, gamma=0.01, learning_rate=0.02, max_depth=8, min_child_weight=5, n_estimators=3000, reg_alpha=10, reg_lambda=1, subsample=0.8, tree_method=hist; total time=   7.3s
[CV] END colsample_bytree=0.8, gamma=0.1, learning_rate=0.01, max_depth=8, min_child_weight=5, n_estimators=1000, reg_alpha=0.01, reg_lambda=10, subsample=0.6, tree_method=hist; total time=   3.7s
[CV] END colsample_bytree=1.0, gamma=0, learning_rate=0.05, max_depth=5, min_child_weight=7, n_estimators=500, reg_alpha=0, reg_lambda=5, subsample=0.8, tree_method=hist; total time=   1.0s
[CV] END colsample_bytree=0.5, gamma=0.1, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=2000, reg_alpha=10, reg_lambda=1, subsample=0.6, tree_method=hist; total time=   3.5s
[CV] END colsample_bytree=0.9, gamma=1, learning_rate=0.01, max_depth=4, min_child_weight=7, n_estimators=1000, reg_alpha=0, reg_lambda=1, subsample=0.8, tree_method=hist; total time=   1.6s
[CV] END colsample_bytree=0.9, gamma=0, learning_rate=0.1, max_depth=8, min_child_weight=3, n_estimators=3000, reg_alpha=1, reg_lambda=0.1, subsample=1.0, tree_method=hist; total time=   3.8s
[CV] END colsample_bytree=0.7, gamma=0.5, learning_rate=0.05, max_depth=8, min_child_weight=5, n_estimators=2000, reg_alpha=0.1, reg_lambda=5, subsample=0.7, tree_method=hist; total time=   2.8s
[CV] END colsample_bytree=0.7, gamma=0.1, learning_rate=0.01, max_depth=2, min_child_weight=7, n_estimators=1000, reg_alpha=0.01, reg_lambda=5, subsample=0.6, tree_method=hist; total time=   1.1s
[CV] END colsample_bytree=0.7, gamma=0.5, learning_rate=0.05, max_depth=5, min_child_weight=5, n_estimators=500, reg_alpha=0, reg_lambda=10, subsample=0.9, tree_method=hist; total time=   0.7s
[CV] END colsample_bytree=1.0, gamma=0, learning_rate=0.01, max_depth=2, min_child_weight=3, n_estimators=1500, reg_alpha=0.1, reg_lambda=10, subsample=0.8, tree_method=hist; total time=   1.5s
[CV] END colsample_bytree=0.5, gamma=0, learning_rate=0.1, max_depth=5, min_child_weight=1, n_estimators=500, reg_alpha=10, reg_lambda=0.1, subsample=0.6, tree_method=hist; total time=   1.0s
[CV] END colsample_bytree=0.9, gamma=0, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=2000, reg_alpha=0.1, reg_lambda=1, subsample=0.8, tree_method=hist; total time=  10.5s
[CV] END colsample_bytree=0.5, gamma=0.01, learning_rate=0.01, max_depth=5, min_child_weight=1, n_estimators=1500, reg_alpha=0.01, reg_lambda=0.1, subsample=1.0, tree_method=hist; total time=   3.1s
[CV] END colsample_bytree=0.8, gamma=0.1, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=1000, reg_alpha=0.01, reg_lambda=0.1, subsample=0.8, tree_method=hist; total time=   2.2s

### Current Anime Prediction

In [2781]:
final_model.eval()

real_other_t = real_other.to(device)

with torch.no_grad():
    output = final_model(real_other_t)
    
    preds = output.cpu().numpy()



predictions = {}
for index, title in enumerate(real_df['title']):

    predictions[title] = [float(x) for x in preds[index]]

print(f"Collected predictions for {len(predictions)} items.")

sorted_predictions = dict(sorted(predictions.items(), key=lambda item: item[1][0], reverse=True))

from pprint import pprint
pprint(sorted_predictions, indent=4, sort_dicts=False)

Collected predictions for 72 items.
{   'Kusuriya no Hitorigoto 3rd Season': [   2.0891549587249756,
                                             1.2728078365325928,
                                             1.723383903503418,
                                             0.5110766291618347,
                                             1.04609215259552],
    'Ao Ashi Season 2': [   1.729020595550537,
                            1.0126206874847412,
                            1.2175542116165161,
                            0.3136860132217407,
                            0.8066071271896362],
    'Koori no Jouheki 2nd Season': [   1.6441385746002197,
                                       0.8017870187759399,
                                       1.066056728363037,
                                       0.0830940306186676,
                                       0.718880295753479],
    'Ao no Hako Season 2': [   1.4689122438430786,
                               1.2908415794372559,
                               1.4819031953811646,
                               0.7468129992485046,
                               0.8908654451370239],
    'Diamond no Ace: Act II Second Season Part 2': [   1.4265480041503906,
                                                       0.652708888053894,
                                                       0.7731223702430725,
                                                       0.027238860726356506,
                                                       0.4983537495136261],
    'Hotaru no Yomeiri': [   1.2782400846481323,
                             0.953704833984375,
                             1.27018141746521,
                             0.8728868365287781,
                             0.8869791626930237],
    'Tokyo Revengers: Santen Sensou-hen': [   1.1972553730010986,
                                              1.1881413459777832,
                                              1.3011229038238525,
                                              0.7903941869735718,
                                              0.9194205403327942],
    'Black Clover 2nd Season': [   1.1309418678283691,
                                   1.8785829544067383,
                                   1.8500943183898926,
                                   1.4566493034362793,
                                   1.100203275680542],
    'Kanata kara': [   1.0393530130386353,
                       0.9683401584625244,
                       1.1069238185882568,
                       0.8182682394981384,
                       0.6919735670089722],
    'Hitozukiai ga Nigate na Miboujin no Yukionna-san to Noroi no Yubiwa': [   1.0147716999053955,
                                                                               0.8870682120323181,
                                                                               1.0885772705078125,
                                                                               0.8228582739830017,
                                                                               0.7516100406646729],
    'Mezametara Saikyou Soubi to Uchuusenmochi Datta node, Ikkodate Mezashite Youhei toshite Jiyuu ni Ikitai': [   0.9981551766395569,
                                                                                                                   1.05925452709198,
                                                                                                                   1.1821413040161133,
                                                                                                                   1.0469732284545898,
                                                                                                                   1.056174397468567],
    'Ranma ½ (2024) 3rd Season': [   0.8656225800514221,
                                     0.9210649132728577,
                                     0.8768160343170166,
                                     0.6320348978042603,
                                     0.7534362077713013],
    'Seitokai ni mo Ana wa Aru!': [   0.861449122428894,
                                      0.773360550403595,
                                      0.8410993814468384,
                                      0.7995331883430481,
                                      0.6403296589851379],
    'Psyren': [   0.8531315922737122,
                  1.2872157096862793,
                  1.4254202842712402,
                  1.302964448928833,
                  0.9951160550117493],
    'Yozakura-san Chi no Daisakusen 2nd Season Part 2': [   0.8389914631843567,
                                                            0.7923518419265747,
                                                            0.7006171941757202,
                                                            0.5557340979576111,
                                                            0.6623503565788269],
    'Keroro Gunsou☆': [   0.6966317296028137,
                          0.5632469058036804,
                          0.595080554485321,
                          0.6563182473182678,
                          0.4968477785587311],
    'Tempal: Item no Chikara': [   0.6518111824989319,
                                   0.8614135384559631,
                                   0.896546483039856,
                                   0.9548714756965637,
                                   0.7254171371459961],
    'Magic Knight Rayearth (2026)': [   0.6406944990158081,
                                        0.8027510046958923,
                                        0.7927247285842896,
                                        0.7877796292304993,
                                        0.5832005739212036],
    'Tensei shitara Ken deshita II': [   0.6177585124969482,
                                         1.0903916358947754,
                                         0.928083062171936,
                                         0.8061037659645081,
                                         0.7089458703994751],
    'Sekai Saikyou no Majo, Hajimemashita': [   0.6014313697814941,
                                                0.5296593904495239,
                                                0.5399649739265442,
                                                0.5864675641059875,
                                                0.4458063840866089],
    'Tank Chair': [   0.572412371635437,
                      0.7958398461341858,
                      0.9201953411102295,
                      0.9137489795684814,
                      0.7675536870956421],
    'Yasei no Last Boss ga Arawareta! 2nd Season': [   0.5545712113380432,
                                                       0.7999197244644165,
                                                       0.6413933634757996,
                                                       0.5526085495948792,
                                                       0.6060172319412231],
    'Mahou Shoujo Ikusei Keikaku: Restart': [   0.5276073217391968,
                                                1.124211072921753,
                                                1.0847151279449463,
                                                1.0418604612350464,
                                                0.876237154006958],
    'Shiotaiou no Satou-san ga Ore ni dake Amai': [   0.4155765473842621,
                                                      0.8404513597488403,
                                                      0.7987568974494934,
                                                      0.9755421280860901,
                                                      0.7427669763565063],
    'Doumo, Suki na Hito ni Horegusuri wo Irai sareta Majo desu.': [   0.3909221589565277,
                                                                       0.4385360777378082,
                                                                       0.4462662935256958,
                                                                       0.40834665298461914,
                                                                       0.4144779145717621],
    'Yowaki Max Reijou nanoni, Ratsuwan Konyakusha-sama no Kake ni Notte Shimatta': [   0.37645959854125977,
                                                                                        0.4021989703178406,
                                                                                        0.4095386266708374,
                                                                                        0.3627862334251404,
                                                                                        0.3925667703151703],
    'Ojisan wa Kawaii Mono ga Osuki.': [   0.3380810618400574,
                                           0.07169482856988907,
                                           0.059615358710289,
                                           0.12270881235599518,
                                           0.12350206077098846],
    'Kikansha no Mahou wa Tokubetsu desu 2nd Season': [   0.27641376852989197,
                                                          0.877866804599762,
                                                          0.7187153100967407,
                                                          0.8057981133460999,
                                                          0.6822381019592285],
    'Chitose-kun wa Ramune Bin no Naka Part 2': [   0.27388009428977966,
                                                    0.7385390400886536,
                                                    0.5481007099151611,
                                                    0.5979977250099182,
                                                    0.6077044010162354],
    'FX Senshi Kurumi-chan': [   0.27132073044776917,
                                 0.10551808774471283,
                                 0.1294957399368286,
                                 0.18788643181324005,
                                 0.25082704424858093],
    'Kyouran Reijou Nia Liston: Byoujaku Reijou ni Tensei shita Kamigoroshi no Bujin no Karei Naru Musouroku': [   0.1922571212053299,
                                                                                                                   -0.2969454526901245,
                                                                                                                   -0.23277385532855988,
                                                                                                                   -0.33920711278915405,
                                                                                                                   -0.3090929687023163],
    'Gensou Suikoden': [   0.18305779993534088,
                           0.06626376509666443,
                           0.060711488127708435,
                           0.18433605134487152,
                           0.029882483184337616],
    'Choujun! Choujou-senpai': [   0.11132205277681351,
                                   0.16176694631576538,
                                   0.1234816163778305,
                                   0.34317827224731445,
                                   0.21860584616661072],
    'Shinja Zero no Megami-sama to Hajimeru Isekai Kouryaku': [   0.10746344178915024,
                                                                  0.7296242713928223,
                                                                  0.5997358560562134,
                                                                  0.739044189453125,
                                                                  0.5902668237686157],
    'Tantei wa Mou, Shindeiru. Season 2': [   0.032755859196186066,
                                              0.9225629568099976,
                                              0.7582157850265503,
                                              0.992704451084137,
                                              0.6915600299835205],
    'Nezumi-kun no Chokki (TV) 2nd Season': [   0.030606156215071678,
                                                -0.8129028081893921,
                                                -0.7057628631591797,
                                                -1.0854259729385376,
                                                -0.8397253751754761],
    'Toaru Anbu no Item': [   0.01982523687183857,
                              0.5350246429443359,
                              0.5012015700340271,
                              0.7444060444831848,
                              0.5254459977149963],
    'Dark Summoner to Dekiteiru': [   0.010098962113261223,
                                      0.34930652379989624,
                                      0.2815186381340027,
                                      0.5103978514671326,
                                      0.3228795826435089],
    'Tensei shita Daiseijo wa, Seijo de Aru Koto wo Hitakakusu': [   -0.05072071775794029,
                                                                     0.2413160651922226,
                                                                     0.16614679992198944,
                                                                     0.438707172870636,
                                                                     0.1435903012752533],
    'Shin Tennis no Oujisama: U-17 World Cup Kesshou Member Ketteisen': [   -0.05953602492809296,
                                                                            -0.00427659135311842,
                                                                            -0.19962312281131744,
                                                                            -0.07824154943227768,
                                                                            -0.0008498057723045349],
    '#Zombie Sagashitemasu': [   -0.06015174090862274,
                                 0.048075925558805466,
                                 -0.0755324512720108,
                                 0.12840063869953156,
                                 0.12913906574249268],
    'Tetsuryou! Meet with Tetsudou Musume': [   -0.07693447917699814,
                                                -0.5461214184761047,
                                                -0.31758540868759155,
                                                -0.5075973868370056,
                                                -0.2960072457790375],
    'Magical★Explorer': [   -0.09995822608470917,
                            0.5214350819587708,
                            0.31978315114974976,
                            0.6072519421577454,
                            0.4939613342285156],
    'Tougen Anki: Nikko Kegon no Taki-hen': [   -0.18572868406772614,
                                                0.6009228229522705,
                                                0.3687223792076111,
                                                0.7472885251045227,
                                                0.4694635570049286],
    'Punirunes: Puni 4': [   -0.21223492920398712,
                             -1.008665680885315,
                             -0.8551146984100342,
                             -1.1404659748077393,
                             -1.1149511337280273],
    'Junket Bank': [   -0.29495248198509216,
                       -0.04766819253563881,
                       -0.06765473634004593,
                       0.2619931697845459,
                       0.22612270712852478],
    'Dragon Ball Super: Beerus': [   -0.3023304343223572,
                                     -0.14962339401245117,
                                     -0.19026745855808258,
                                     0.008785650134086609,
                                     -0.08343394845724106],
    'Tensei Kizoku, Kantei Skill de Nariagaru 3rd Season': [   -0.3151335120201111,
                                                               0.45734694600105286,
                                                               0.18961967527866364,
                                                               0.4844275116920471,
                                                               0.37883004546165466],
    'Hotel Inhumans 2nd Season': [   -0.322640061378479,
                                     0.022220995277166367,
                                     -0.1418982595205307,
                                     0.07454179227352142,
                                     0.11409170925617218],
    'Kyoufu Collector': [   -0.3796740770339966,
                            -0.6601214408874512,
                            -0.6223421692848206,
                            -0.5462604761123657,
                            -0.5498147010803223],
    'Kizu darake Seijo yori Houfuku wo Komete Season 2': [   -0.38196635246276855,
                                                             -0.23263265192508698,
                                                             -0.4229864478111267,
                                                             -0.23411789536476135,
                                                             -0.16595199704170227],
    'Sasaki to Pii-chan Season 2': [   -0.4279744327068329,
                                       0.42832642793655396,
                                       0.1607978194952011,
                                       0.5461711287498474,
                                       0.3751251995563507],
    'Tsuihou sareta Cheat Fuyo Majutsushi wa Kimama na Second Life wo Ouka suru. Ore wa Buki dake ja Naku, Arayuru Mono ni "Kyouka Point" wo Fuyo Dekiru shi, Ore no Ishi de Itsudemo Kouka wo Kaijo Dekiru kedo, Nokotta Hitotachi Daijoubu?': [   -0.4671771228313446,
                                                                                                                                                                                                                                                    0.17505007982254028,
                                                                                                                                                                                                                                                    0.01065770536661148,
                                                                                                                                                                                                                                                    0.3817829489707947,
                                                                                                                                                                                                                                                    0.2003757655620575],
    'Kanojo no Tomodachi': [   -0.4851071834564209,
                               0.30701327323913574,
                               0.18372498452663422,
                               0.5530493855476379,
                               0.40267619490623474],
    'Mahou no Shimai Lulutto Lilly Part 2': [   -0.4929969310760498,
                                                -0.8160185813903809,
                                                -0.8304358720779419,
                                                -1.0330029726028442,
                                                -0.8054652214050293],
    'Yuusanchi! from Yuu-hachi': [   -0.5081411600112915,
                                     -1.203430414199829,
                                     -1.0328452587127686,
                                     -1.116528868675232,
                                     -1.2094098329544067],
    'Kashita Maryoku wa "Revo Barai" de Kyousei Choushuu': [   -0.5109808444976807,
                                                               -0.5092209577560425,
                                                               -0.47376394271850586,

In [2782]:
target_dir = "..\data\processed"
file_name = "overall_predictions.json" 
file_path = os.path.join(target_dir, file_name)

with open(file_path, "w", encoding="utf-8") as file:
    json.dump(sorted_predictions, file, indent=4)

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\14793\AppData\Local\Temp\ipykernel_19312\1413168248.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  target_dir = "..\data\processed"